// =============================================================================
// Finance & Supply Chain — Static Mock Data
// Single source of truth for all static data in this module.
// Each api.ts file imports from here instead of making real HTTP calls.
// =============================================================================

// ─── MASTERS ─────────────────────────────────────────────────────────────────

export const FINANCIAL_YEARS = [
  {
    id: 1,
    name: '2021-22',
    startDate: '2021-04-01',
    endDate: '2022-03-31',
    isCurrent: false,
    isActive: true,
  },
  {
    id: 2,
    name: '2022-23',
    startDate: '2022-04-01',
    endDate: '2023-03-31',
    isCurrent: false,
    isActive: true,
  },
  {
    id: 3,
    name: '2023-24',
    startDate: '2023-04-01',
    endDate: '2024-03-31',
    isCurrent: false,
    isActive: true,
  },
  {
    id: 4,
    name: '2024-25',
    startDate: '2024-04-01',
    endDate: '2025-03-31',
    isCurrent: true,
    isActive: true,
  },
  {
    id: 5,
    name: '2025-26',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    isCurrent: false,
    isActive: true,
  },
];

export const CHART_OF_ACCOUNTS = [
  {
    id: 1,
    code: '1001',
    name: 'Cash in Hand',
    accountType: 'Asset',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 2,
    code: '1002',
    name: 'Bank - SBI Main Account',
    accountType: 'Asset',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 3,
    code: '1003',
    name: 'Bank - PNB Account',
    accountType: 'Asset',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 4,
    code: '2001',
    name: 'Accounts Payable',
    accountType: 'Liability',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 5,
    code: '2002',
    name: 'Salary Payable',
    accountType: 'Liability',
    parentAccount: 'Accounts Payable',
    isActive: true,
  },
  {
    id: 6,
    code: '2003',
    name: 'TDS Payable',
    accountType: 'Liability',
    parentAccount: 'Accounts Payable',
    isActive: true,
  },
  {
    id: 7,
    code: '3001',
    name: 'General Fund',
    accountType: 'Equity',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 8,
    code: '3002',
    name: 'Building Fund',
    accountType: 'Equity',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 9,
    code: '4001',
    name: 'Tuition Fee Income',
    accountType: 'Income',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 10,
    code: '4002',
    name: 'Exam Fee Income',
    accountType: 'Income',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 11,
    code: '4003',
    name: 'Grant Income - UGC',
    accountType: 'Income',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 12,
    code: '5001',
    name: 'Salary Expenditure',
    accountType: 'Expense',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 13,
    code: '5002',
    name: 'Travelling Expenditure',
    accountType: 'Expense',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 14,
    code: '5003',
    name: 'Office Supplies',
    accountType: 'Expense',
    parentAccount: '',
    isActive: true,
  },
  {
    id: 15,
    code: '5004',
    name: 'Maintenance & Repair',
    accountType: 'Expense',
    parentAccount: '',
    isActive: true,
  },
];

export const COST_CENTRES = [
  {
    id: 1,
    code: 'CC-001',
    name: 'Administration',
    department: 'Administration',
    isActive: true,
  },
  {
    id: 2,
    code: 'CC-002',
    name: 'Engineering Dept.',
    department: 'Engineering',
    isActive: true,
  },
  {
    id: 3,
    code: 'CC-003',
    name: 'Science Dept.',
    department: 'Science',
    isActive: true,
  },
  {
    id: 4,
    code: 'CC-004',
    name: 'Commerce Dept.',
    department: 'Commerce',
    isActive: true,
  },
  {
    id: 5,
    code: 'CC-005',
    name: 'Library',
    department: 'Library',
    isActive: true,
  },
  {
    id: 6,
    code: 'CC-006',
    name: 'Sports & Recreation',
    department: 'Sports',
    isActive: false,
  },
  {
    id: 7,
    code: 'CC-007',
    name: 'Research Division',
    department: 'Research',
    isActive: true,
  },
];

export const BUDGET_CATEGORIES = [
  {
    id: 1,
    categoryCode: 'BC-01',
    name: 'Academic',
    description: 'Academic activities and programmes',
    isActive: true,
  },
  {
    id: 2,
    categoryCode: 'BC-02',
    name: 'Administrative',
    description: 'Administrative and office expenses',
    isActive: true,
  },
  {
    id: 3,
    categoryCode: 'BC-03',
    name: 'Infrastructure',
    description: 'Buildings, civil works, infrastructure',
    isActive: true,
  },
  {
    id: 4,
    categoryCode: 'BC-04',
    name: 'Research',
    description: 'Research grants and projects',
    isActive: true,
  },
  {
    id: 5,
    categoryCode: 'BC-05',
    name: 'Student Welfare',
    description: 'Student scholarships and support',
    isActive: true,
  },
  {
    id: 6,
    categoryCode: 'BC-06',
    name: 'IT & Technology',
    description: 'IT infrastructure and software',
    isActive: true,
  },
];

export const BUDGET_HEADS = [
  {
    id: 1,
    headCode: 'BH-001',
    name: 'Salary & Wages',
    category: 'Administrative',
    budgetCategory: 'BC-02',
    isActive: true,
  },
  {
    id: 2,
    headCode: 'BH-002',
    name: 'Travelling Allowance',
    category: 'Administrative',
    budgetCategory: 'BC-02',
    isActive: true,
  },
  {
    id: 3,
    headCode: 'BH-003',
    name: 'Office Stationery',
    category: 'Administrative',
    budgetCategory: 'BC-02',
    isActive: true,
  },
  {
    id: 4,
    headCode: 'BH-004',
    name: 'Lab Equipment',
    category: 'Academic',
    budgetCategory: 'BC-01',
    isActive: true,
  },
  {
    id: 5,
    headCode: 'BH-005',
    name: 'Library Books',
    category: 'Academic',
    budgetCategory: 'BC-01',
    isActive: true,
  },
  {
    id: 6,
    headCode: 'BH-006',
    name: 'Building Repair',
    category: 'Infrastructure',
    budgetCategory: 'BC-03',
    isActive: true,
  },
  {
    id: 7,
    headCode: 'BH-007',
    name: 'IT Hardware',
    category: 'IT & Technology',
    budgetCategory: 'BC-06',
    isActive: true,
  },
  {
    id: 8,
    headCode: 'BH-008',
    name: 'Software Licenses',
    category: 'IT & Technology',
    budgetCategory: 'BC-06',
    isActive: true,
  },
];

export const BANK_ACCOUNTS = [
  {
    id: 1,
    accountNo: '10234567890',
    bankName: 'State Bank of India',
    branch: 'University Main Branch',
    ifscCode: 'SBIN0001234',
    accountType: 'Current',
    isActive: true,
  },
  {
    id: 2,
    accountNo: '20198765432',
    bankName: 'Punjab National Bank',
    branch: 'City Branch',
    ifscCode: 'PUNB0056789',
    accountType: 'Current',
    isActive: true,
  },
  {
    id: 3,
    accountNo: '30112233445',
    bankName: 'Bank of Baroda',
    branch: 'Main Road Branch',
    ifscCode: 'BARB0UNIVCC',
    accountType: 'Savings',
    isActive: true,
  },
  {
    id: 4,
    accountNo: '40556677889',
    bankName: 'HDFC Bank',
    branch: 'Electronic City Branch',
    ifscCode: 'HDFC0004567',
    accountType: 'Current',
    isActive: false,
  },
];

export const TAX_GST_CONFIG = [
  {
    id: 1,
    taxName: 'GST 5%',
    rate: 5,
    type: 'GST',
    hsnCode: '9992',
    description: 'Educational Services',
    isActive: true,
  },
  {
    id: 2,
    taxName: 'GST 12%',
    rate: 12,
    type: 'GST',
    hsnCode: '4901',
    description: 'Printed Books & Publications',
    isActive: true,
  },
  {
    id: 3,
    taxName: 'GST 18%',
    rate: 18,
    type: 'GST',
    hsnCode: '8471',
    description: 'Computers & IT Equipment',
    isActive: true,
  },
  {
    id: 4,
    taxName: 'GST 28%',
    rate: 28,
    type: 'GST',
    hsnCode: '8708',
    description: 'Automobile Parts',
    isActive: false,
  },
  {
    id: 5,
    taxName: 'TDS 10%',
    rate: 10,
    type: 'TDS',
    hsnCode: '',
    description: 'Professional Services TDS',
    isActive: true,
  },
  {
    id: 6,
    taxName: 'TDS 2%',
    rate: 2,
    type: 'TDS',
    hsnCode: '',
    description: 'Contractor TDS',
    isActive: true,
  },
];

// ─── BUDGET MANAGEMENT ───────────────────────────────────────────────────────

export const BUDGETS = [
  {
    id: 1,
    budgetCode: 'BDG-2024-001',
    title: 'Annual Budget 2024-25',
    financialYear: '2024-25',
    totalAmount: 25000000,
    status: 'Approved',
    preparedBy: 'Dr. R. Sharma',
    approvedBy: 'VC Office',
    createdDate: '2024-03-15',
  },
  {
    id: 2,
    budgetCode: 'BDG-2024-002',
    title: 'Supplementary Budget Q2 2024',
    financialYear: '2024-25',
    totalAmount: 3500000,
    status: 'Approved',
    preparedBy: 'Mr. P. Gupta',
    approvedBy: 'Finance Comm.',
    createdDate: '2024-09-10',
  },
  {
    id: 3,
    budgetCode: 'BDG-2025-001',
    title: 'Annual Budget 2025-26',
    financialYear: '2025-26',
    totalAmount: 28000000,
    status: 'Draft',
    preparedBy: 'Dr. R. Sharma',
    approvedBy: '-',
    createdDate: '2025-02-20',
  },
];

export const BUDGET_ALLOCATIONS = [
  {
    id: 1,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Salary & Wages',
    costCentre: 'Administration',
    allocatedAmount: 12000000,
    utilizedAmount: 9500000,
    balance: 2500000,
    status: 'Active',
  },
  {
    id: 2,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Lab Equipment',
    costCentre: 'Engineering Dept.',
    allocatedAmount: 2000000,
    utilizedAmount: 1800000,
    balance: 200000,
    status: 'Active',
  },
  {
    id: 3,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Library Books',
    costCentre: 'Library',
    allocatedAmount: 800000,
    utilizedAmount: 750000,
    balance: 50000,
    status: 'Active',
  },
  {
    id: 4,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Building Repair',
    costCentre: 'Administration',
    allocatedAmount: 3000000,
    utilizedAmount: 1200000,
    balance: 1800000,
    status: 'Active',
  },
  {
    id: 5,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'IT Hardware',
    costCentre: 'Administration',
    allocatedAmount: 1500000,
    utilizedAmount: 1450000,
    balance: 50000,
    status: 'Active',
  },
  {
    id: 6,
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Office Stationery',
    costCentre: 'Administration',
    allocatedAmount: 500000,
    utilizedAmount: 320000,
    balance: 180000,
    status: 'Active',
  },
];

export const BUDGET_REVISIONS = [
  {
    id: 1,
    revisionNo: 'REV-2024-001',
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Lab Equipment',
    revisedAmount: 2500000,
    originalAmount: 2000000,
    reason: 'Additional equipment procurement needed',
    status: 'Approved',
    date: '2024-07-15',
  },
  {
    id: 2,
    revisionNo: 'REV-2024-002',
    budgetCode: 'BDG-2024-001',
    budgetHead: 'IT Hardware',
    revisedAmount: 2000000,
    originalAmount: 1500000,
    reason: 'Server upgrade required',
    status: 'Approved',
    date: '2024-08-22',
  },
  {
    id: 3,
    revisionNo: 'REV-2024-003',
    budgetCode: 'BDG-2024-001',
    budgetHead: 'Building Repair',
    revisedAmount: 2500000,
    originalAmount: 3000000,
    reason: 'Reduced scope of civil work',
    status: 'Pending',
    date: '2025-01-10',
  },
];

export const BUDGET_TRANSFERS = [
  {
    id: 1,
    transferNo: 'BT-2024-001',
    fromHead: 'Building Repair',
    toHead: 'Lab Equipment',
    amount: 500000,
    reason: 'Surplus from civil work',
    status: 'Approved',
    date: '2024-10-05',
  },
  {
    id: 2,
    transferNo: 'BT-2024-002',
    fromHead: 'Office Stationery',
    toHead: 'IT Hardware',
    amount: 100000,
    reason: 'Digital transformation',
    status: 'Approved',
    date: '2024-11-18',
  },
  {
    id: 3,
    transferNo: 'BT-2025-001',
    fromHead: 'Travelling Allowance',
    toHead: 'Library Books',
    amount: 80000,
    reason: 'Online conference budget',
    status: 'Pending',
    date: '2025-03-01',
  },
];

// ─── ACCOUNTING ───────────────────────────────────────────────────────────────

export const RECEIPT_VOUCHERS = [
  {
    id: 1,
    voucherNo: 'RV-2024-0001',
    date: '2024-04-05',
    receivedFrom: 'Student Fee Collection',
    account: 'Tuition Fee Income',
    amount: 450000,
    mode: 'Online Transfer',
    narration: 'Semester I Fee Collection',
    status: 'Posted',
  },
  {
    id: 2,
    voucherNo: 'RV-2024-0002',
    date: '2024-04-12',
    receivedFrom: 'UGC Grant Disbursement',
    account: 'Grant Income - UGC',
    amount: 1200000,
    mode: 'NEFT',
    narration: 'UGC Research Grant Q1',
    status: 'Posted',
  },
  {
    id: 3,
    voucherNo: 'RV-2024-0003',
    date: '2024-05-10',
    receivedFrom: 'Exam Fee Collection',
    account: 'Exam Fee Income',
    amount: 95000,
    mode: 'Online Transfer',
    narration: 'End Semester Exam Fee Collection',
    status: 'Posted',
  },
  {
    id: 4,
    voucherNo: 'RV-2024-0004',
    date: '2024-06-01',
    receivedFrom: 'Student Fee Collection',
    account: 'Tuition Fee Income',
    amount: 380000,
    mode: 'DD',
    narration: 'Semester II Fee Collection',
    status: 'Posted',
  },
  {
    id: 5,
    voucherNo: 'RV-2024-0005',
    date: '2024-08-20',
    receivedFrom: 'State Govt. Grant',
    account: 'Grant Income - UGC',
    amount: 2500000,
    mode: 'RTGS',
    narration: 'State Govt Infrastructure Grant',
    status: 'Posted',
  },
];

export const PAYMENT_VOUCHERS = [
  {
    id: 1,
    voucherNo: 'PV-2024-0001',
    date: '2024-04-30',
    paidTo: 'Faculty Salary',
    account: 'Salary Expenditure',
    amount: 850000,
    mode: 'Bank Transfer',
    narration: 'April 2024 Salary',
    status: 'Posted',
  },
  {
    id: 2,
    voucherNo: 'PV-2024-0002',
    date: '2024-05-02',
    paidTo: 'Scientific Suppliers Ltd',
    account: 'Lab Equipment',
    amount: 125000,
    mode: 'Cheque',
    narration: 'Lab Microscopes Purchase',
    status: 'Posted',
  },
  {
    id: 3,
    voucherNo: 'PV-2024-0003',
    date: '2024-05-15',
    paidTo: 'Electricity Board',
    account: 'Maintenance & Repair',
    amount: 48000,
    mode: 'Online',
    narration: 'April Electricity Bill',
    status: 'Posted',
  },
  {
    id: 4,
    voucherNo: 'PV-2024-0004',
    date: '2024-05-31',
    paidTo: 'Faculty Salary',
    account: 'Salary Expenditure',
    amount: 850000,
    mode: 'Bank Transfer',
    narration: 'May 2024 Salary',
    status: 'Posted',
  },
  {
    id: 5,
    voucherNo: 'PV-2024-0005',
    date: '2024-06-10',
    paidTo: 'XYZ Stationery Mart',
    account: 'Office Supplies',
    amount: 15000,
    mode: 'Cash',
    narration: 'Office Stationery Q1',
    status: 'Posted',
  },
];

export const JOURNAL_VOUCHERS = [
  {
    id: 1,
    voucherNo: 'JV-2024-0001',
    date: '2024-04-01',
    narration: 'Opening Balance Entry',
    debitAccount: 'Cash in Hand',
    creditAccount: 'General Fund',
    amount: 50000,
    status: 'Posted',
  },
  {
    id: 2,
    voucherNo: 'JV-2024-0002',
    date: '2024-05-31',
    narration: 'Salary payable provision',
    debitAccount: 'Salary Expenditure',
    creditAccount: 'Salary Payable',
    amount: 850000,
    status: 'Posted',
  },
  {
    id: 3,
    voucherNo: 'JV-2024-0003',
    date: '2024-06-30',
    narration: 'TDS deduction on contractor',
    debitAccount: 'Accounts Payable',
    creditAccount: 'TDS Payable',
    amount: 12500,
    status: 'Posted',
  },
  {
    id: 4,
    voucherNo: 'JV-2024-0004',
    date: '2024-09-30',
    narration: 'Depreciation for Q2',
    debitAccount: 'Salary Expenditure',
    creditAccount: 'General Fund',
    amount: 180000,
    status: 'Posted',
  },
];

export const CONTRA_VOUCHERS = [
  {
    id: 1,
    voucherNo: 'CV-2024-0001',
    date: '2024-04-10',
    type: 'Cash Deposit',
    fromAccount: 'Cash in Hand',
    toAccount: 'Bank - SBI Main Account',
    amount: 200000,
    narration: 'Cash deposited in SBI',
    status: 'Posted',
  },
  {
    id: 2,
    voucherNo: 'CV-2024-0002',
    date: '2024-05-08',
    type: 'Cash Withdrawal',
    fromAccount: 'Bank - SBI Main Account',
    toAccount: 'Cash in Hand',
    amount: 50000,
    narration: 'Petty cash withdrawal',
    status: 'Posted',
  },
  {
    id: 3,
    voucherNo: 'CV-2024-0003',
    date: '2024-07-20',
    type: 'Fund Transfer',
    fromAccount: 'Bank - SBI Main Account',
    toAccount: 'Bank - PNB Account',
    amount: 500000,
    narration: 'Inter-bank fund transfer',
    status: 'Posted',
  },
];

export const LEDGER_ENTRIES = [
  {
    id: 1,
    date: '2024-04-01',
    voucherNo: 'JV-2024-0001',
    narration: 'Opening Balance',
    account: 'Cash in Hand',
    debit: 50000,
    credit: 0,
    balance: 50000,
  },
  {
    id: 2,
    date: '2024-04-05',
    voucherNo: 'RV-2024-0001',
    narration: 'Tuition Fee Collection',
    account: 'Tuition Fee Income',
    debit: 0,
    credit: 450000,
    balance: 450000,
  },
  {
    id: 3,
    date: '2024-04-10',
    voucherNo: 'CV-2024-0001',
    narration: 'Cash Deposited to Bank',
    account: 'Bank - SBI Main Account',
    debit: 200000,
    credit: 0,
    balance: 200000,
  },
  {
    id: 4,
    date: '2024-04-12',
    voucherNo: 'RV-2024-0002',
    narration: 'UGC Grant Receipt',
    account: 'Grant Income - UGC',
    debit: 0,
    credit: 1200000,
    balance: 1200000,
  },
  {
    id: 5,
    date: '2024-04-30',
    voucherNo: 'PV-2024-0001',
    narration: 'April Salary Payment',
    account: 'Salary Expenditure',
    debit: 850000,
    credit: 0,
    balance: 850000,
  },
  {
    id: 6,
    date: '2024-05-02',
    voucherNo: 'PV-2024-0002',
    narration: 'Lab Equipment Purchase',
    account: 'Lab Equipment',
    debit: 125000,
    credit: 0,
    balance: 125000,
  },
  {
    id: 7,
    date: '2024-05-10',
    voucherNo: 'RV-2024-0003',
    narration: 'Exam Fee Collection',
    account: 'Exam Fee Income',
    debit: 0,
    credit: 95000,
    balance: 95000,
  },
  {
    id: 8,
    date: '2024-05-31',
    voucherNo: 'PV-2024-0004',
    narration: 'May Salary Payment',
    account: 'Salary Expenditure',
    debit: 850000,
    credit: 0,
    balance: 1700000,
  },
];

export const BANK_RECONCILIATION = [
  {
    id: 1,
    date: '2024-04-10',
    description: 'Fee Collection Deposit',
    bankAmount: 450000,
    ledgerAmount: 450000,
    status: 'Matched',
    referenceNo: 'NEFT/24041/001',
  },
  {
    id: 2,
    date: '2024-04-12',
    description: 'UGC Grant Credit',
    bankAmount: 1200000,
    ledgerAmount: 1200000,
    status: 'Matched',
    referenceNo: 'RTGS/24041/002',
  },
  {
    id: 3,
    date: '2024-04-28',
    description: 'Electricity Bill Payment',
    bankAmount: 48000,
    ledgerAmount: 0,
    status: 'Unmatched',
    referenceNo: 'ACH/24042/003',
  },
  {
    id: 4,
    date: '2024-04-30',
    description: 'Salary Disbursement',
    bankAmount: 850000,
    ledgerAmount: 850000,
    status: 'Matched',
    referenceNo: 'BULK/24043/001',
  },
  {
    id: 5,
    date: '2024-05-05',
    description: 'Bank Charges',
    bankAmount: 1200,
    ledgerAmount: 0,
    status: 'Unmatched',
    referenceNo: 'CHG/24050/001',
  },
  {
    id: 6,
    date: '2024-05-10',
    description: 'Exam Fee Deposit',
    bankAmount: 95000,
    ledgerAmount: 95000,
    status: 'Matched',
    referenceNo: 'NEFT/24051/002',
  },
];

// ─── PROCUREMENT ─────────────────────────────────────────────────────────────

export const VENDORS = [
  {
    id: 1,
    vendorCode: 'VND-001',
    name: 'Scientific Suppliers Ltd.',
    gstin: '27AABCS1234P1Z5',
    pan: 'AABCS1234P',
    contactPerson: 'Mr. Ramesh Iyer',
    phone: '9876543210',
    email: 'sales@scientificsuppliers.com',
    category: 'Lab Equipment',
    city: 'Mumbai',
    isActive: true,
  },
  {
    id: 2,
    vendorCode: 'VND-002',
    name: 'TechWorld Solutions Pvt Ltd',
    gstin: '06AADCT5678Q1Z1',
    pan: 'AADCT5678Q',
    contactPerson: 'Ms. Priya Sharma',
    phone: '9988776655',
    email: 'info@techworldsol.com',
    category: 'IT Equipment',
    city: 'Gurugram',
    isActive: true,
  },
  {
    id: 3,
    vendorCode: 'VND-003',
    name: 'Edu Books & Publications',
    gstin: '07AACCE9012R1Z4',
    pan: 'AACCE9012R',
    contactPerson: 'Mr. Sunil Verma',
    phone: '8877665544',
    email: 'orders@edubooksind.com',
    category: 'Books',
    city: 'New Delhi',
    isActive: true,
  },
  {
    id: 4,
    vendorCode: 'VND-004',
    name: 'BuildRight Contractors',
    gstin: '24AAACB3456S1Z7',
    pan: 'AAACB3456S',
    contactPerson: 'Mr. Kiran Patel',
    phone: '7766554433',
    email: 'kiran@buildrightco.com',
    category: 'Civil Works',
    city: 'Ahmedabad',
    isActive: true,
  },
  {
    id: 5,
    vendorCode: 'VND-005',
    name: 'Stationery World',
    gstin: '09AAAAS7890T1Z2',
    pan: 'AAAAS7890T',
    contactPerson: 'Mrs. Anita Gupta',
    phone: '6655443322',
    email: 'anita@stationeryworld.in',
    category: 'Stationery',
    city: 'Lucknow',
    isActive: true,
  },
  {
    id: 6,
    vendorCode: 'VND-006',
    name: 'UniClean Housekeeping',
    gstin: '29AAATU1234U1Z9',
    pan: 'AAATU1234U',
    contactPerson: 'Mr. Sanjay Hegde',
    phone: '5544332211',
    email: 'contracts@uniclean.co.in',
    category: 'Housekeeping',
    city: 'Bengaluru',
    isActive: false,
  },
];

export const PURCHASE_REQUISITIONS = [
  {
    id: 1,
    prNo: 'PR-2024-001',
    date: '2024-06-01',
    department: 'Engineering Dept.',
    item: 'Digital Oscilloscopes',
    quantity: 5,
    estimatedCost: 125000,
    budgetHead: 'Lab Equipment',
    priority: 'High',
    status: 'Approved',
    requestedBy: 'Dr. A. Mehta',
  },
  {
    id: 2,
    prNo: 'PR-2024-002',
    date: '2024-06-10',
    department: 'Library',
    item: 'Reference Books (Engineering)',
    quantity: 200,
    estimatedCost: 60000,
    budgetHead: 'Library Books',
    priority: 'Medium',
    status: 'Approved',
    requestedBy: 'Mr. K. Sharma',
  },
  {
    id: 3,
    prNo: 'PR-2024-003',
    date: '2024-07-05',
    department: 'Administration',
    item: 'Office Chairs',
    quantity: 20,
    estimatedCost: 40000,
    budgetHead: 'Office Stationery',
    priority: 'Low',
    status: 'Pending',
    requestedBy: 'Mrs. R. Singh',
  },
  {
    id: 4,
    prNo: 'PR-2024-004',
    date: '2024-08-15',
    department: 'Administration',
    item: 'Laptop Computers',
    quantity: 10,
    estimatedCost: 750000,
    budgetHead: 'IT Hardware',
    priority: 'High',
    status: 'Approved',
    requestedBy: 'Mr. P. Gupta',
  },
  {
    id: 5,
    prNo: 'PR-2024-005',
    date: '2024-09-01',
    department: 'Science Dept.',
    item: 'Chemical Reagents',
    quantity: 50,
    estimatedCost: 35000,
    budgetHead: 'Lab Equipment',
    priority: 'Medium',
    status: 'Rejected',
    requestedBy: 'Dr. S. Nair',
  },
];

export const RFQS = [
  {
    id: 1,
    rfqNo: 'RFQ-2024-001',
    date: '2024-06-15',
    prReference: 'PR-2024-001',
    item: 'Digital Oscilloscopes',
    vendors: ['VND-001', 'VND-002'],
    dueDate: '2024-06-30',
    status: 'Closed',
    createdBy: 'Mr. P. Gupta',
  },
  {
    id: 2,
    rfqNo: 'RFQ-2024-002',
    date: '2024-06-20',
    prReference: 'PR-2024-002',
    item: 'Reference Books',
    vendors: ['VND-003'],
    dueDate: '2024-07-05',
    status: 'Closed',
    createdBy: 'Mr. P. Gupta',
  },
  {
    id: 3,
    rfqNo: 'RFQ-2024-003',
    date: '2024-08-20',
    prReference: 'PR-2024-004',
    item: 'Laptop Computers',
    vendors: ['VND-002'],
    dueDate: '2024-09-05',
    status: 'Open',
    createdBy: 'Mr. P. Gupta',
  },
];

export const QUOTATION_COMPARISONS = [
  {
    id: 1,
    rfqNo: 'RFQ-2024-001',
    vendor: 'Scientific Suppliers Ltd.',
    itemName: 'Digital Oscilloscopes',
    unitPrice: 24000,
    quantity: 5,
    totalAmount: 120000,
    deliveryDays: 14,
    warranty: '2 Years',
    recommended: true,
  },
  {
    id: 2,
    rfqNo: 'RFQ-2024-001',
    vendor: 'TechWorld Solutions Pvt Ltd',
    itemName: 'Digital Oscilloscopes',
    unitPrice: 26500,
    quantity: 5,
    totalAmount: 132500,
    deliveryDays: 10,
    warranty: '3 Years',
    recommended: false,
  },
  {
    id: 3,
    rfqNo: 'RFQ-2024-002',
    vendor: 'Edu Books & Publications',
    itemName: 'Reference Books',
    unitPrice: 290,
    quantity: 200,
    totalAmount: 58000,
    deliveryDays: 7,
    warranty: 'N/A',
    recommended: true,
  },
];

export const PURCHASE_ORDERS = [
  {
    id: 1,
    poNo: 'PO-2024-001',
    date: '2024-07-02',
    vendor: 'Scientific Suppliers Ltd.',
    item: 'Digital Oscilloscopes',
    quantity: 5,
    unitPrice: 24000,
    totalAmount: 120000,
    deliveryDate: '2024-07-16',
    status: 'Delivered',
    prReference: 'PR-2024-001',
  },
  {
    id: 2,
    poNo: 'PO-2024-002',
    date: '2024-07-08',
    vendor: 'Edu Books & Publications',
    item: 'Reference Books',
    quantity: 200,
    unitPrice: 290,
    totalAmount: 58000,
    deliveryDate: '2024-07-15',
    status: 'Delivered',
    prReference: 'PR-2024-002',
  },
  {
    id: 3,
    poNo: 'PO-2024-003',
    date: '2024-09-10',
    vendor: 'TechWorld Solutions Pvt Ltd',
    item: 'Laptop Computers',
    quantity: 10,
    unitPrice: 72000,
    totalAmount: 720000,
    deliveryDate: '2024-09-25',
    status: 'Pending',
    prReference: 'PR-2024-004',
  },
  {
    id: 4,
    poNo: 'PO-2024-004',
    date: '2024-10-01',
    vendor: 'Stationery World',
    item: 'Office Chairs',
    quantity: 20,
    unitPrice: 2100,
    totalAmount: 42000,
    deliveryDate: '2024-10-10',
    status: 'Delivered',
    prReference: 'PR-2024-003',
  },
];

export const GOODS_RECEIPTS = [
  {
    id: 1,
    grnNo: 'GRN-2024-001',
    date: '2024-07-17',
    poNo: 'PO-2024-001',
    vendor: 'Scientific Suppliers Ltd.',
    item: 'Digital Oscilloscopes',
    quantityOrdered: 5,
    quantityReceived: 5,
    unitPrice: 24000,
    totalAmount: 120000,
    condition: 'Good',
    receivedBy: 'Mr. A. Kumar',
  },
  {
    id: 2,
    grnNo: 'GRN-2024-002',
    date: '2024-07-14',
    poNo: 'PO-2024-002',
    vendor: 'Edu Books & Publications',
    item: 'Reference Books',
    quantityOrdered: 200,
    quantityReceived: 198,
    unitPrice: 290,
    totalAmount: 57420,
    condition: 'Good',
    receivedBy: 'Mr. K. Sharma',
  },
  {
    id: 3,
    grnNo: 'GRN-2024-003',
    date: '2024-10-12',
    poNo: 'PO-2024-004',
    vendor: 'Stationery World',
    item: 'Office Chairs',
    quantityOrdered: 20,
    quantityReceived: 20,
    unitPrice: 2100,
    totalAmount: 42000,
    condition: 'Good',
    receivedBy: 'Mrs. R. Singh',
  },
];

export const VENDOR_BILLS = [
  {
    id: 1,
    billNo: 'VB-2024-001',
    billDate: '2024-07-18',
    vendor: 'Scientific Suppliers Ltd.',
    grnReference: 'GRN-2024-001',
    amount: 120000,
    gst: 21600,
    totalAmount: 141600,
    dueDate: '2024-08-17',
    paymentStatus: 'Paid',
    poNo: 'PO-2024-001',
  },
  {
    id: 2,
    billNo: 'VB-2024-002',
    billDate: '2024-07-15',
    vendor: 'Edu Books & Publications',
    grnReference: 'GRN-2024-002',
    amount: 57420,
    gst: 2871,
    totalAmount: 60291,
    dueDate: '2024-08-14',
    paymentStatus: 'Paid',
    poNo: 'PO-2024-002',
  },
  {
    id: 3,
    billNo: 'VB-2024-003',
    billDate: '2024-10-13',
    vendor: 'Stationery World',
    grnReference: 'GRN-2024-003',
    amount: 42000,
    gst: 7560,
    totalAmount: 49560,
    dueDate: '2024-11-12',
    paymentStatus: 'Pending',
    poNo: 'PO-2024-004',
  },
  {
    id: 4,
    billNo: 'VB-2024-004',
    billDate: '2024-11-05',
    vendor: 'BuildRight Contractors',
    grnReference: '',
    amount: 350000,
    gst: 63000,
    totalAmount: 413000,
    dueDate: '2024-12-05',
    paymentStatus: 'Overdue',
    poNo: '',
  },
];

// ─── INVENTORY ────────────────────────────────────────────────────────────────

export const ITEMS = [
  {
    id: 1,
    itemCode: 'ITM-001',
    name: 'Digital Oscilloscope 100MHz',
    category: 'Lab Equipment',
    uom: 'Nos',
    reorderLevel: 2,
    currentStock: 5,
    location: 'Physics Lab',
    isActive: true,
  },
  {
    id: 2,
    itemCode: 'ITM-002',
    name: 'HP Laptop 15" i5',
    category: 'IT Equipment',
    uom: 'Nos',
    reorderLevel: 5,
    currentStock: 10,
    location: 'IT Store',
    isActive: true,
  },
  {
    id: 3,
    itemCode: 'ITM-003',
    name: 'A4 Paper Ream 75 GSM',
    category: 'Stationery',
    uom: 'Reams',
    reorderLevel: 50,
    currentStock: 120,
    location: 'Stationery Store',
    isActive: true,
  },
  {
    id: 4,
    itemCode: 'ITM-004',
    name: 'Office Chair (Revolving)',
    category: 'Furniture',
    uom: 'Nos',
    reorderLevel: 5,
    currentStock: 20,
    location: 'Furniture Store',
    isActive: true,
  },
  {
    id: 5,
    itemCode: 'ITM-005',
    name: 'HCl (Hydrochloric Acid) 1L',
    category: 'Chemicals',
    uom: 'Bottles',
    reorderLevel: 10,
    currentStock: 25,
    location: 'Chemistry Lab',
    isActive: true,
  },
  {
    id: 6,
    itemCode: 'ITM-006',
    name: 'Toner Cartridge HP 85A',
    category: 'IT Consumables',
    uom: 'Nos',
    reorderLevel: 10,
    currentStock: 8,
    location: 'IT Store',
    isActive: true,
  },
  {
    id: 7,
    itemCode: 'ITM-007',
    name: 'Engineering Reference Books',
    category: 'Books',
    uom: 'Nos',
    reorderLevel: 20,
    currentStock: 198,
    location: 'Library',
    isActive: true,
  },
  {
    id: 8,
    itemCode: 'ITM-008',
    name: 'Whiteboard Marker (Pack 12)',
    category: 'Stationery',
    uom: 'Packs',
    reorderLevel: 20,
    currentStock: 45,
    location: 'Stationery Store',
    isActive: true,
  },
];

export const STOCK_ISSUES = [
  {
    id: 1,
    issueNo: 'SI-2024-001',
    date: '2024-07-20',
    item: 'Digital Oscilloscope 100MHz',
    quantity: 5,
    issuedTo: 'Physics Lab',
    purpose: 'Lab Practical Sessions',
    issuedBy: 'Mr. A. Kumar',
    status: 'Issued',
  },
  {
    id: 2,
    issueNo: 'SI-2024-002',
    date: '2024-07-22',
    item: 'A4 Paper Ream 75 GSM',
    quantity: 30,
    issuedTo: 'Administration',
    purpose: 'Office Printing',
    issuedBy: 'Mrs. R. Singh',
    status: 'Issued',
  },
  {
    id: 3,
    issueNo: 'SI-2024-003',
    date: '2024-08-01',
    item: 'Toner Cartridge HP 85A',
    quantity: 3,
    issuedTo: 'Admin Office',
    purpose: 'Printer Maintenance',
    issuedBy: 'Mr. P. Gupta',
    status: 'Issued',
  },
  {
    id: 4,
    issueNo: 'SI-2024-004',
    date: '2024-10-15',
    item: 'Office Chair (Revolving)',
    quantity: 20,
    issuedTo: 'Administration Dept.',
    purpose: 'Office Furnishing',
    issuedBy: 'Mrs. R. Singh',
    status: 'Issued',
  },
];

export const STOCK_TRANSFERS = [
  {
    id: 1,
    transferNo: 'ST-2024-001',
    date: '2024-08-05',
    item: 'HP Laptop 15" i5',
    quantity: 2,
    fromLocation: 'IT Store',
    toLocation: 'Computer Lab 1',
    reason: 'Lab Setup',
    status: 'Completed',
    transferredBy: 'Mr. P. Gupta',
  },
  {
    id: 2,
    transferNo: 'ST-2024-002',
    date: '2024-09-10',
    item: 'A4 Paper Ream 75 GSM',
    quantity: 20,
    fromLocation: 'Stationery Store',
    toLocation: 'Library',
    reason: 'Monthly Replenishment',
    status: 'Completed',
    transferredBy: 'Mr. A. Kumar',
  },
  {
    id: 3,
    transferNo: 'ST-2024-003',
    date: '2024-11-01',
    item: 'Whiteboard Marker (Pack 12)',
    quantity: 10,
    fromLocation: 'Stationery Store',
    toLocation: 'Classrooms Block A',
    reason: 'Semester Start',
    status: 'Pending',
    transferredBy: 'Mr. K. Sharma',
  },
];

// ─── ASSET MANAGEMENT ────────────────────────────────────────────────────────

export const ASSETS = [
  {
    id: 1,
    assetCode: 'AST-001',
    name: 'Server - Dell PowerEdge R740',
    category: 'IT Equipment',
    purchaseDate: '2022-05-10',
    purchaseCost: 450000,
    currentValue: 315000,
    location: 'Data Centre',
    status: 'In Use',
    depreciationMethod: 'SLM',
  },
  {
    id: 2,
    assetCode: 'AST-002',
    name: 'UPS System 20KVA',
    category: 'IT Equipment',
    purchaseDate: '2022-05-10',
    purchaseCost: 180000,
    currentValue: 126000,
    location: 'Data Centre',
    status: 'In Use',
    depreciationMethod: 'SLM',
  },
  {
    id: 3,
    assetCode: 'AST-003',
    name: 'Projector - Epson EB-2250U',
    category: 'AV Equipment',
    purchaseDate: '2023-01-15',
    purchaseCost: 85000,
    currentValue: 68000,
    location: 'Seminar Hall',
    status: 'In Use',
    depreciationMethod: 'WDV',
  },
  {
    id: 4,
    assetCode: 'AST-004',
    name: 'AC 2 Ton Split Unit',
    category: 'HVAC',
    purchaseDate: '2021-03-20',
    purchaseCost: 65000,
    currentValue: 32500,
    location: 'Principal Office',
    status: 'In Use',
    depreciationMethod: 'SLM',
  },
  {
    id: 5,
    assetCode: 'AST-005',
    name: 'Photocopier - Ricoh MP 2014',
    category: 'Office Equipment',
    purchaseDate: '2023-06-01',
    purchaseCost: 72000,
    currentValue: 57600,
    location: 'Admin Office',
    status: 'In Use',
    depreciationMethod: 'WDV',
  },
  {
    id: 6,
    assetCode: 'AST-006',
    name: 'Digital Oscilloscope (Batch of 5)',
    category: 'Lab Equipment',
    purchaseDate: '2024-07-17',
    purchaseCost: 120000,
    currentValue: 120000,
    location: 'Physics Lab',
    status: 'In Use',
    depreciationMethod: 'SLM',
  },
  {
    id: 7,
    assetCode: 'AST-007',
    name: 'Library Building Extension',
    category: 'Building',
    purchaseDate: '2019-04-01',
    purchaseCost: 8500000,
    currentValue: 5950000,
    location: 'Main Campus',
    status: 'In Use',
    depreciationMethod: 'SLM',
  },
  {
    id: 8,
    assetCode: 'AST-008',
    name: 'University Van - TATA Winger',
    category: 'Vehicles',
    purchaseDate: '2020-08-15',
    purchaseCost: 950000,
    currentValue: 475000,
    location: 'Transport Pool',
    status: 'In Use',
    depreciationMethod: 'WDV',
  },
];

export const ASSET_ALLOCATIONS = [
  {
    id: 1,
    allocationNo: 'AL-2024-001',
    assetCode: 'AST-003',
    assetName: 'Projector - Epson EB-2250U',
    allocatedTo: 'Prof. D. Sharma',
    department: 'Engineering',
    allocationDate: '2024-01-20',
    returnDate: '',
    status: 'Allocated',
  },
  {
    id: 2,
    allocationNo: 'AL-2024-002',
    assetCode: 'AST-005',
    assetName: 'Photocopier - Ricoh MP 2014',
    allocatedTo: 'Admin Department',
    department: 'Administration',
    allocationDate: '2023-07-01',
    returnDate: '',
    status: 'Allocated',
  },
  {
    id: 3,
    allocationNo: 'AL-2023-001',
    assetCode: 'AST-004',
    assetName: 'AC 2 Ton Split Unit',
    allocatedTo: 'Principal Office',
    department: 'Administration',
    allocationDate: '2021-04-01',
    returnDate: '',
    status: 'Allocated',
  },
  {
    id: 4,
    allocationNo: 'AL-2022-001',
    assetCode: 'AST-008',
    assetName: 'University Van',
    allocatedTo: 'Transport Pool',
    department: 'Administration',
    allocationDate: '2020-09-01',
    returnDate: '',
    status: 'Allocated',
  },
];

export const DEPRECIATION_SCHEDULE = [
  {
    id: 1,
    assetCode: 'AST-001',
    assetName: 'Server - Dell PowerEdge R740',
    financialYear: '2024-25',
    openingValue: 360000,
    rate: 15,
    depreciationAmount: 54000,
    closingValue: 306000,
    method: 'SLM',
  },
  {
    id: 2,
    assetCode: 'AST-002',
    assetName: 'UPS System 20KVA',
    financialYear: '2024-25',
    openingValue: 144000,
    rate: 15,
    depreciationAmount: 21600,
    closingValue: 122400,
    method: 'SLM',
  },
  {
    id: 3,
    assetCode: 'AST-003',
    assetName: 'Projector - Epson EB-2250U',
    financialYear: '2024-25',
    openingValue: 72000,
    rate: 20,
    depreciationAmount: 14400,
    closingValue: 57600,
    method: 'WDV',
  },
  {
    id: 4,
    assetCode: 'AST-004',
    assetName: 'AC 2 Ton Split Unit',
    financialYear: '2024-25',
    openingValue: 39000,
    rate: 15,
    depreciationAmount: 5850,
    closingValue: 33150,
    method: 'SLM',
  },
  {
    id: 5,
    assetCode: 'AST-005',
    assetName: 'Photocopier - Ricoh MP 2014',
    financialYear: '2024-25',
    openingValue: 64800,
    rate: 20,
    depreciationAmount: 12960,
    closingValue: 51840,
    method: 'WDV',
  },
  {
    id: 6,
    assetCode: 'AST-007',
    assetName: 'Library Building Extension',
    financialYear: '2024-25',
    openingValue: 6375000,
    rate: 5,
    depreciationAmount: 318750,
    closingValue: 6056250,
    method: 'SLM',
  },
  {
    id: 7,
    assetCode: 'AST-008',
    assetName: 'University Van - TATA Winger',
    financialYear: '2024-25',
    openingValue: 570000,
    rate: 25,
    depreciationAmount: 142500,
    closingValue: 427500,
    method: 'WDV',
  },
];

// ─── GST & COMPLIANCE ────────────────────────────────────────────────────────

export const GST_TRANSACTIONS = [
  {
    id: 1,
    date: '2024-04-05',
    invoiceNo: 'PV-2024-0002',
    vendorName: 'Scientific Suppliers Ltd.',
    description: 'Lab Microscopes',
    taxableAmount: 125000,
    cgst: 9000,
    sgst: 9000,
    igst: 0,
    totalGst: 18000,
    totalAmount: 143000,
    gstType: 'CGST+SGST',
  },
  {
    id: 2,
    date: '2024-05-15',
    invoiceNo: 'PV-2024-0003',
    vendorName: 'Electricity Board',
    description: 'Electricity Bill',
    taxableAmount: 48000,
    cgst: 2400,
    sgst: 2400,
    igst: 0,
    totalGst: 4800,
    totalAmount: 52800,
    gstType: 'CGST+SGST',
  },
  {
    id: 3,
    date: '2024-07-18',
    invoiceNo: 'VB-2024-001',
    vendorName: 'Scientific Suppliers Ltd.',
    description: 'Oscilloscopes',
    taxableAmount: 120000,
    cgst: 0,
    sgst: 0,
    igst: 21600,
    totalGst: 21600,
    totalAmount: 141600,
    gstType: 'IGST',
  },
  {
    id: 4,
    date: '2024-07-15',
    invoiceNo: 'VB-2024-002',
    vendorName: 'Edu Books & Publications',
    description: 'Reference Books',
    taxableAmount: 57420,
    cgst: 1436,
    sgst: 1436,
    igst: 0,
    totalGst: 2871,
    totalAmount: 60291,
    gstType: 'CGST+SGST',
  },
  {
    id: 5,
    date: '2024-10-13',
    invoiceNo: 'VB-2024-003',
    vendorName: 'Stationery World',
    description: 'Office Chairs',
    taxableAmount: 42000,
    cgst: 3780,
    sgst: 3780,
    igst: 0,
    totalGst: 7560,
    totalAmount: 49560,
    gstType: 'CGST+SGST',
  },
];

export const GSTR_REPORTS = {
  gstr1: [
    {
      id: 1,
      invoiceNo: 'RI-2024-001',
      invoiceDate: '2024-04-30',
      customerName: 'N/A (Collected from Students)',
      gstin: 'URP',
      taxableAmount: 450000,
      cgst: 0,
      sgst: 0,
      igst: 0,
      totalTax: 0,
      totalAmount: 450000,
      placeOfSupply: '05-Uttarakhand',
    },
    {
      id: 2,
      invoiceNo: 'RI-2024-002',
      invoiceDate: '2024-05-31',
      customerName: 'N/A (Collected from Students)',
      gstin: 'URP',
      taxableAmount: 380000,
      cgst: 0,
      sgst: 0,
      igst: 0,
      totalTax: 0,
      totalAmount: 380000,
      placeOfSupply: '05-Uttarakhand',
    },
  ],
  gstr2a: [
    {
      id: 1,
      supplierName: 'Scientific Suppliers Ltd.',
      gstin: '27AABCS1234P1Z5',
      invoiceDate: '2024-07-18',
      invoiceNo: 'SSL/2024/456',
      taxableAmount: 120000,
      igst: 21600,
      totalAmount: 141600,
    },
    {
      id: 2,
      supplierName: 'Edu Books & Publications',
      gstin: '07AACCE9012R1Z4',
      invoiceDate: '2024-07-15',
      invoiceNo: 'EBP/2024/789',
      taxableAmount: 57420,
      cgst: 1436,
      sgst: 1436,
      totalAmount: 60291,
    },
  ],
  gstr3b: {
    month: 'July 2024',
    outwardSupplies: { taxableAmount: 830000, cgst: 0, sgst: 0, igst: 0 },
    inwardSupplies: {
      taxableAmount: 177420,
      cgst: 1436,
      sgst: 1436,
      igst: 21600,
    },
    taxPayable: { cgst: 1436, sgst: 1436, igst: 21600 },
    itcAvailable: { cgst: 1436, sgst: 1436, igst: 21600 },
    netTaxPayable: { cgst: 0, sgst: 0, igst: 0 },
  },
};

export const TAX_REPORTS = [
  {
    id: 1,
    month: 'April 2024',
    tdsDeducted: 85000,
    tdsDeposited: 85000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 2,
    month: 'May 2024',
    tdsDeducted: 90000,
    tdsDeposited: 90000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 3,
    month: 'June 2024',
    tdsDeducted: 88000,
    tdsDeposited: 88000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 4,
    month: 'July 2024',
    tdsDeducted: 92000,
    tdsDeposited: 92000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 5,
    month: 'August 2024',
    tdsDeducted: 87000,
    tdsDeposited: 87000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 6,
    month: 'September 2024',
    tdsDeducted: 94000,
    tdsDeposited: 94000,
    tdsBalance: 0,
    tcsCollected: 0,
    deposited: true,
  },
  {
    id: 7,
    month: 'October 2024',
    tdsDeducted: 89000,
    tdsDeposited: 0,
    tdsBalance: 89000,
    tcsCollected: 0,
    deposited: false,
  },
];

// ─── FINANCIAL REPORTS ────────────────────────────────────────────────────────

export const TRIAL_BALANCE = [
  {
    id: 1,
    accountCode: '1001',
    accountName: 'Cash in Hand',
    debit: 50000,
    credit: 0,
  },
  {
    id: 2,
    accountCode: '1002',
    accountName: 'Bank - SBI Main Account',
    debit: 3450000,
    credit: 0,
  },
  {
    id: 3,
    accountCode: '1003',
    accountName: 'Bank - PNB Account',
    debit: 500000,
    credit: 0,
  },
  {
    id: 4,
    accountCode: '2001',
    accountName: 'Accounts Payable',
    debit: 0,
    credit: 413000,
  },
  {
    id: 5,
    accountCode: '2002',
    accountName: 'Salary Payable',
    debit: 0,
    credit: 850000,
  },
  {
    id: 6,
    accountCode: '2003',
    accountName: 'TDS Payable',
    debit: 0,
    credit: 89000,
  },
  {
    id: 7,
    accountCode: '3001',
    accountName: 'General Fund',
    debit: 0,
    credit: 8500000,
  },
  {
    id: 8,
    accountCode: '3002',
    accountName: 'Building Fund',
    debit: 0,
    credit: 2000000,
  },
  {
    id: 9,
    accountCode: '4001',
    accountName: 'Tuition Fee Income',
    debit: 0,
    credit: 830000,
  },
  {
    id: 10,
    accountCode: '4002',
    accountName: 'Exam Fee Income',
    debit: 0,
    credit: 95000,
  },
  {
    id: 11,
    accountCode: '4003',
    accountName: 'Grant Income - UGC',
    debit: 0,
    credit: 3700000,
  },
  {
    id: 12,
    accountCode: '5001',
    accountName: 'Salary Expenditure',
    debit: 5950000,
    credit: 0,
  },
  {
    id: 13,
    accountCode: '5002',
    accountName: 'Travelling Expenditure',
    debit: 32000,
    credit: 0,
  },
  {
    id: 14,
    accountCode: '5003',
    accountName: 'Office Supplies',
    debit: 57000,
    credit: 0,
  },
  {
    id: 15,
    accountCode: '5004',
    accountName: 'Maintenance & Repair',
    debit: 438000,
    credit: 0,
  },
];

export const BALANCE_SHEET = {
  assets: {
    currentAssets: [
      { name: 'Cash in Hand', amount: 50000 },
      { name: 'Bank - SBI Main Account', amount: 3450000 },
      { name: 'Bank - PNB Account', amount: 500000 },
    ],
    fixedAssets: [
      { name: 'IT Equipment (Net)', amount: 428400 },
      { name: 'Lab Equipment (Net)', amount: 120000 },
      { name: 'Buildings (Net)', amount: 6056250 },
      { name: 'Vehicles (Net)', amount: 427500 },
      { name: 'Other Fixed Assets', amount: 109440 },
    ],
    totalAssets: 11141590,
  },
  liabilities: {
    currentLiabilities: [
      { name: 'Accounts Payable', amount: 413000 },
      { name: 'Salary Payable', amount: 850000 },
      { name: 'TDS Payable', amount: 89000 },
    ],
    equity: [
      { name: 'General Fund', amount: 8500000 },
      { name: 'Building Fund', amount: 2000000 },
      { name: 'Surplus for the Year', amount: -710410 },
    ],
    totalLiabilities: 11141590,
  },
};

export const INCOME_EXPENDITURE = {
  income: [
    { head: 'Tuition Fee', amount: 830000 },
    { head: 'Exam Fee', amount: 95000 },
    { head: 'UGC Grant', amount: 3700000 },
    { head: 'State Govt. Grant', amount: 2500000 },
    { head: 'Other Income', amount: 45000 },
  ],
  totalIncome: 7170000,
  expenditure: [
    { head: 'Salaries & Wages', amount: 5950000 },
    { head: 'Travelling Allowance', amount: 32000 },
    { head: 'Office Supplies', amount: 57000 },
    { head: 'Maintenance & Repair', amount: 438000 },
    { head: 'Depreciation', amount: 570060 },
    { head: 'Other Expenditure', amount: 33350 },
  ],
  totalExpenditure: 7080410,
  surplus: 89590,
};

export const CASH_FLOW = {
  operating: [
    { description: 'Fees Collected from Students', amount: 925000 },
    { description: 'Grants Received', amount: 6200000 },
    { description: 'Salary & Wages Paid', amount: -5950000 },
    // { description: 'Office & Admin Expenses Paid', amount: -527000 },
  ],
  operatingTotal: 648000,
  investing: [
    { description: 'Purchase of Lab Equipment', amount: -120000 },
    { description: 'Purchase of IT Equipment', amount: -720000 },
    // { description: 'Purchase of Furniture', amount: -42000 },
  ],
  investingTotal: -882000,
  financing: [{ description: 'TDS Deposited', amount: -616000 }],
  financingTotal: -616000,
  netChange: -850000,
  openingBalance: 4850000,
  closingBalance: 4000000,
};

export const FUND_FLOW = {
  sources: [
    { description: 'Tuition & Exam Fee Collections', amount: 925000 },
    { description: 'UGC Grant', amount: 3700000 },
    { description: 'State Govt. Grant', amount: 2500000 },
    { description: 'Depreciation (Non-cash Add-back)', amount: 570060 },
  ],
  totalSources: 7695060,
  applications: [
    { description: 'Capital Expenditure (Equipment)', amount: 882000 },
    { description: 'Salary & Wages', amount: 5950000 },
    { description: 'Operating Expenses', amount: 620350 },
    { description: 'TDS Deposited', amount: 616000 },
  ],
  totalApplications: 8068350,
  netChange: -373290,
};

export const BUDGET_REPORTS = [
  {
    id: 1,
    budgetHead: 'Salary & Wages',
    costCentre: 'Administration',
    originalAmount: 12000000,
    revisedAmount: 12000000,
    allocatedAmount: 12000000,
    actualExpenditure: 9500000,
    transferIn: 0,
    transferOut: 0,
    variance: 2500000,
    variancePct: 20.8,
    status: 'Under Budget',
  },
  {
    id: 2,
    budgetHead: 'Lab Equipment',
    costCentre: 'Engineering Dept.',
    originalAmount: 2000000,
    revisedAmount: 2500000,
    allocatedAmount: 2000000,
    actualExpenditure: 1925000,
    transferIn: 500000,
    transferOut: 0,
    variance: 575000,
    variancePct: 23.0,
    status: 'Under Budget',
  },
  {
    id: 3,
    budgetHead: 'Library Books',
    costCentre: 'Library',
    originalAmount: 800000,
    revisedAmount: 880000,
    allocatedAmount: 800000,
    actualExpenditure: 808000,
    transferIn: 80000,
    transferOut: 0,
    variance: 72000,
    variancePct: 8.1,
    status: 'Under Budget',
  },
  {
    id: 4,
    budgetHead: 'Building Repair',
    costCentre: 'Administration',
    originalAmount: 3000000,
    revisedAmount: 2500000,
    allocatedAmount: 3000000,
    actualExpenditure: 1200000,
    transferIn: 0,
    transferOut: 500000,
    variance: 1300000,
    variancePct: 52.0,
    status: 'Under Budget',
  },
  {
    id: 5,
    budgetHead: 'IT Hardware',
    costCentre: 'Administration',
    originalAmount: 1500000,
    revisedAmount: 2000000,
    allocatedAmount: 1500000,
    actualExpenditure: 1720000,
    transferIn: 100000,
    transferOut: 0,
    variance: 280000,
    variancePct: 14.0,
    status: 'Under Budget',
  },
  {
    id: 6,
    budgetHead: 'Office Stationery',
    costCentre: 'Administration',
    originalAmount: 500000,
    revisedAmount: 400000,
    allocatedAmount: 500000,
    actualExpenditure: 320000,
    transferIn: 0,
    transferOut: 100000,
    variance: 80000,
    variancePct: 20.0,
    status: 'Under Budget',
  },
  {
    id: 7,
    budgetHead: 'Travelling Allowance',
    costCentre: 'Administration',
    originalAmount: 300000,
    revisedAmount: 220000,
    allocatedAmount: 300000,
    actualExpenditure: 32000,
    transferIn: 0,
    transferOut: 80000,
    variance: 188000,
    variancePct: 85.4,
    status: 'Under Budget',
  },
  {
    id: 8,
    budgetHead: 'Software Licenses',
    costCentre: 'IT Dept.',
    originalAmount: 400000,
    revisedAmount: 400000,
    allocatedAmount: 400000,
    actualExpenditure: 410000,
    transferIn: 0,
    transferOut: 0,
    variance: -10000,
    variancePct: -2.5,
    status: 'Over Budget',
  },
];

export const BUDGET_SUMMARY = {
  totalOriginal: 20500000,
  totalRevised: 20900000,
  totalActual: 15915000,
  totalVariance: 4985000,
  utilizationPct: 76.1,
};

export const GST_REPORT_SUMMARY = {
  totalTaxableAmount: 1007420,
  totalCgst: 1436,
  totalSgst: 1436,
  totalIgst: 21600,
  totalGstPaid: 24472,
  itcAvailable: 24472,
  netTaxPayable: 0,
};

export const TDS_SUMMARY = {
  tdsDeducted: 625000,
  tdsDeposited: 536000,
  tdsBalance: 89000,
};

// ─── DASHBOARD KPIs ───────────────────────────────────────────────────────────

export const DASHBOARD_KPIS = {
  totalBudget: 25000000,
  totalExpenditure: 15905000,
  remainingBudget: 9095000,
  totalReceipts: 7170000,
  pendingPayables: 413000,
  overduePayables: 413000,
  pendingPRs: 1,
  openPOs: 1,
  pendingGRNs: 0,
  totalAssets: 8,
  totalVendors: 6,
  budgetUtilizationPct: 63.6,
};

export const GST_RETURNS = [
  {
    id: 1,
    returnType: 'GSTR-1',
    month: 'April',
    year: 2024,
    dueDate: '2024-05-11',
    filingDate: '2024-05-10',
    arn: 'AA0705240001234',
    taxPaid: 0,
    status: 'Filed',
  },
  {
    id: 2,
    returnType: 'GSTR-3B',
    month: 'April',
    year: 2024,
    dueDate: '2024-05-20',
    filingDate: '2024-05-18',
    arn: 'AA0705240001235',
    taxPaid: 45000,
    status: 'Filed',
  },
  {
    id: 3,
    returnType: 'GSTR-1',
    month: 'May',
    year: 2024,
    dueDate: '2024-06-11',
    filingDate: '',
    arn: '',
    taxPaid: 0,
    status: 'Pending',
  },
];

export const TDS_TCS_REPORTS = [
  {
    id: 1,
    section: '194J',
    vendor: 'Global Tech Services',
    amountPaid: 150000,
    tdsAmount: 15000,
    challanNo: 'CHL-123456',
    paymentDate: '2024-05-05',
    status: 'Deposited',
  },
  {
    id: 2,
    section: '194C',
    vendor: 'ABC Contractors',
    amountPaid: 80000,
    tdsAmount: 1600,
    challanNo: 'CHL-123457',
    paymentDate: '2024-05-05',
    status: 'Deposited',
  },
  {
    id: 3,
    section: '194J',
    vendor: 'Global Tech Services',
    amountPaid: 50000,
    tdsAmount: 5000,
    challanNo: '',
    paymentDate: '',
    status: 'Pending',
  },
];

export const RECENT_TRANSACTIONS = [
  {
    id: 1,
    type: 'Receipt',
    transactionId: 'RV-2024-045',
    date: '2024-05-18',
    amount: 250000,
    status: 'Approved',
  },
  {
    id: 2,
    type: 'Purchase Order',
    transactionId: 'PO-2024-112',
    date: '2024-05-17',
    amount: 45000,
    status: 'Pending',
  },
  {
    id: 3,
    type: 'Payment',
    transactionId: 'PV-2024-089',
    date: '2024-05-16',
    amount: 12000,
    status: 'Approved',
  },
  {
    id: 4,
    type: 'Journal',
    transactionId: 'JV-2024-034',
    date: '2024-05-15',
    amount: 8000,
    status: 'Draft',
  },
  {
    id: 5,
    type: 'Receipt',
    transactionId: 'RV-2024-044',
    date: '2024-05-14',
    amount: 150000,
    status: 'Approved',
  },
];

export const DASHBOARD_ALERTS = [
  {
    id: 1,
    module: 'Inventory',
    message: '12 items below reorder level',
    severity: 'high',
  },
  {
    id: 2,
    module: 'Procurement',
    message: '5 Purchase Requisitions awaiting approval',
    severity: 'medium',
  },
  {
    id: 3,
    module: 'Compliance',
    message: 'GST Return filing due in 4 days',
    severity: 'high',
  },
  {
    id: 4,
    module: 'Assets',
    message: 'Run monthly depreciation process',
    severity: 'medium',
  },
];

// ─── NEW INVENTORY MODULES (STOCK REGISTER, TRANSFER, VERIFICATION, DISPOSAL) ───

export const STOCK_REGISTER = [
  {
    id: 1,
    assetId: 'FURN-2024-001',
    name: 'Executive Office Chair',
    category: 'Furniture',
    department: 'Administration',
    location: 'Admin Block, Rm 101',
    dateOfPurchase: '2024-01-15',
    poReference: 'PO-2024-012',
    unitValue: 12000,
    condition: 'Good',
    custodian: 'Mr. A. Kumar',
    status: 'Active',
  },
  {
    id: 2,
    assetId: 'FURN-2024-002',
    name: 'Conference Table',
    category: 'Furniture',
    department: 'Administration',
    location: 'Admin Block, Board Room',
    dateOfPurchase: '2024-01-15',
    poReference: 'PO-2024-012',
    unitValue: 45000,
    condition: 'Good',
    custodian: 'Mr. A. Kumar',
    status: 'Active',
  },
  {
    id: 3,
    assetId: 'COMP-2023-045',
    name: 'Dell Optiplex 7090',
    category: 'IT Equipment',
    department: 'Computer Science',
    location: 'Lab 3',
    dateOfPurchase: '2023-08-20',
    poReference: 'PO-2023-088',
    unitValue: 65000,
    condition: 'Good',
    custodian: 'Dr. S. Verma',
    status: 'Active',
  },
  {
    id: 4,
    assetId: 'COMP-2021-012',
    name: 'HP ProBook 450',
    category: 'IT Equipment',
    department: 'Library',
    location: 'Librarian Office',
    dateOfPurchase: '2021-05-10',
    poReference: 'PO-2021-034',
    unitValue: 55000,
    condition: 'Damaged',
    custodian: 'Mrs. K. Sharma',
    status: 'Active',
  },
  {
    id: 5,
    assetId: 'LAB-2022-008',
    name: 'Digital Oscilloscope',
    category: 'Lab Equipment',
    department: 'Electronics',
    location: 'ECE Lab 1',
    dateOfPurchase: '2022-11-05',
    poReference: 'PO-2022-105',
    unitValue: 35000,
    condition: 'Condemned',
    custodian: 'Prof. R. Singh',
    status: 'Disposed',
  },
];

export const STOCK_TRANSFER_REQUESTS = [
  {
    id: 1,
    transferNo: 'TRF-2024-001',
    date: '2024-03-12',
    assetId: 'COMP-2023-045',
    assetName: 'Dell Optiplex 7090',
    fromDepartment: 'Computer Science',
    toDepartment: 'IT Cell',
    quantity: 1,
    reason: 'Reallocation of resources',
    requestedBy: 'Dr. S. Verma',
    approvedBy: 'Dean of Sciences',
    status: 'Approved',
  },
  {
    id: 2,
    transferNo: 'TRF-2024-002',
    date: '2024-05-20',
    assetId: 'FURN-2022-015',
    assetName: 'Filing Cabinet',
    fromDepartment: 'Administration',
    toDepartment: 'Examination',
    quantity: 2,
    reason: 'Storage shortage in Exam dept',
    requestedBy: 'Mr. P. Gupta',
    approvedBy: '-',
    status: 'Pending',
  },
];

export const STOCK_VERIFICATIONS = [
  {
    id: 1,
    auditYear: '2023-24',
    department: 'Computer Science',
    assetId: 'COMP-2023-045',
    assetName: 'Dell Optiplex 7090',
    location: 'Lab 3',
    verifiedDate: '2024-03-25',
    status: 'Verified',
    remarks: 'Good working condition',
  },
  {
    id: 2,
    auditYear: '2023-24',
    department: 'Library',
    assetId: 'COMP-2021-012',
    assetName: 'HP ProBook 450',
    location: 'Librarian Office',
    verifiedDate: '2024-03-26',
    status: 'Verified',
    remarks: 'Screen damaged, needs repair',
  },
  {
    id: 3,
    auditYear: '2023-24',
    department: 'Electronics',
    assetId: 'LAB-2019-022',
    assetName: 'Multimeter Set',
    location: 'ECE Lab 2',
    verifiedDate: '2024-03-28',
    status: 'Missing',
    remarks: 'Not found during physical count',
  },
];

export const DISPOSAL_ITEMS = [
  {
    id: 1,
    disposalNo: 'DSP-2024-001',
    date: '2024-04-10',
    assetId: 'LAB-2022-008',
    assetName: 'Digital Oscilloscope',
    department: 'Electronics',
    reason: 'Beyond Repair',
    method: 'E-Waste Scrap',
    writeOffValue: 0,
    requestedBy: 'Prof. R. Singh',
    approvedBy: 'Finance Comm.',
    status: 'Approved',
  },
  {
    id: 2,
    disposalNo: 'DSP-2024-002',
    date: '2024-06-15',
    assetId: 'FURN-2015-055',
    assetName: 'Wooden Desk',
    department: 'Administration',
    reason: 'Broken/Termite Damaged',
    method: 'Auction',
    writeOffValue: 500,
    requestedBy: 'Mr. A. Kumar',
    approvedBy: '-',
    status: 'Pending',
  },
];

export const TDS_GST_REPORT_DATA = [
  {
    id: 1,
    sno: 1,
    officeName: 'Main Campus',
    partyName: 'ABC Corp',
    gstNo: '07AABCU9603R1Z2',
    totalBillAmount: 500000,
    paymentAmount: 490000,
    basicAmount: 400000,
    gstTdsAmount: 10000,
    cgst: 5000,
    sgst: 5000,
    igst: 0,
  },
  {
    id: 2,
    sno: 2,
    officeName: 'North Block',
    partyName: 'XYZ Tech',
    gstNo: '09AABCU9603R1Z3',
    totalBillAmount: 118000,
    paymentAmount: 115640,
    basicAmount: 100000,
    gstTdsAmount: 2360,
    cgst: 0,
    sgst: 0,
    igst: 2360,
  },
  {
    id: 3,
    sno: 3,
    officeName: 'South Campus',
    partyName: 'Alpha Supply',
    gstNo: '27AABCU9603R1Z4',
    totalBillAmount: 236000,
    paymentAmount: 231280,
    basicAmount: 200000,
    gstTdsAmount: 4720,
    cgst: 2360,
    sgst: 2360,
    igst: 0,
  },
  {
    id: 4,
    sno: 4,
    officeName: 'Main Campus',
    partyName: 'Beta Build',
    gstNo: '07AABCU9603R1Z5',
    totalBillAmount: 850000,
    paymentAmount: 833000,
    basicAmount: 720000,
    gstTdsAmount: 17000,
    cgst: 8500,
    sgst: 8500,
    igst: 0,
  },
];
