export const mockData = {
  // Mock endpoints and data for the CMS Management feature
  'cms/departments': [
    {
      id: 1,
      name: 'Computer Science',
      shortName: 'CS',
      icon: 'desktop',
      colorHex: '#3b82f6',
      totalCourses: 5,
      totalFaculty: 20,
      totalStudents: 450,
      description: 'CS Dept',
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      name: 'Mechanical Engineering',
      shortName: 'ME',
      icon: 'cog',
      colorHex: '#ef4444',
      totalCourses: 3,
      totalFaculty: 15,
      totalStudents: 300,
      description: 'ME Dept',
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/courses': [
    {
      id: 1,
      name: 'B.Tech CSE',
      icon: 'code',
      level: 'UG',
      departmentId: 1,
      departmentName: 'Computer Science',
      duration: '4 Years',
      eligibilityCriteria: '12th Pass',
      annualFees: 120000,
      totalSeats: 120,
      badgeColor: '#3b82f6',
      description: 'B.Tech in CS',
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      name: 'M.Tech CSE',
      icon: 'laptop',
      level: 'PG',
      departmentId: 1,
      departmentName: 'Computer Science',
      duration: '2 Years',
      eligibilityCriteria: 'B.Tech Pass',
      annualFees: 150000,
      totalSeats: 60,
      badgeColor: '#10b981',
      description: 'M.Tech in CS',
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/faculty': [
    {
      id: 1,
      fullName: 'Dr. Anand Tiwari',
      initials: 'AT',
      departmentId: 1,
      departmentName: 'Computer Science',
      designation: 'Professor',
      qualification: 'Ph.D in AI',
      experienceYears: 15,
      researchPapers: 42,
      email: 'anand@example.com',
      profileImageUrl: null,
      avatarColorHex: '#3b82f6',
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      fullName: 'Dr. Smriti Irani',
      initials: 'SI',
      departmentId: 2,
      departmentName: 'Mechanical Engineering',
      designation: 'Associate Professor',
      qualification: 'Ph.D in Thermal',
      experienceYears: 10,
      researchPapers: 12,
      email: 'smriti@example.com',
      profileImageUrl: null,
      avatarColorHex: '#ef4444',
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/news': [
    {
      id: 1,
      title: 'Campus Drive 2026',
      description: 'Placement drive for final year',
      category: 'Placements',
      publishedDate: '2026-07-01',
      externalLink: null,
      imageUrl: null,
      isPublished: true,
      displayOrder: 1,
    },
    {
      id: 2,
      title: 'Alumni Meet',
      description: 'Annual alumni get together',
      category: 'Events',
      publishedDate: '2026-08-15',
      externalLink: null,
      imageUrl: null,
      isPublished: true,
      displayOrder: 2,
    },
  ],
  'cms/downloads': [
    {
      id: 1,
      name: 'Academic Calendar',
      icon: 'calendar',
      fileType: 'PDF',
      fileSizeDisplay: '2 MB',
      fileUrl: null,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      name: 'Syllabus CSE',
      icon: 'book',
      fileType: 'PDF',
      fileSizeDisplay: '5 MB',
      fileUrl: null,
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/gallery': [
    {
      id: 1,
      label: 'Convocation 2025',
      emoji: '🎓',
      backgroundColor: '#3b82f6',
      imageUrl: null,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      label: 'Tech Fest',
      emoji: '🚀',
      backgroundColor: '#10b981',
      imageUrl: null,
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/facilities': [
    {
      id: 1,
      name: 'Central Library',
      icon: 'book',
      description: 'Main campus library with 1M books',
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      name: 'Sports Complex',
      icon: 'trophy',
      description: 'Indoor and outdoor stadium',
      isActive: true,
      displayOrder: 2,
    },
  ],
  'cms/stats': [
    {
      id: 1,
      label: 'Total Students',
      value: '15,000+',
      icon: 'users',
      displayOrder: 1,
    },
    {
      id: 2,
      label: 'Total Faculty',
      value: '850+',
      icon: 'user-tie',
      displayOrder: 2,
    },
  ],
  'cms/notices': [
    {
      id: 1,
      text: 'Fee Submission Deadline is 30th June 2026',
      isActive: true,
      expiresAt: '2026-06-30',
      displayOrder: 1,
    },
    {
      id: 2,
      text: 'Holiday List Updated for Q3',
      isActive: true,
      expiresAt: '2026-07-01',
      displayOrder: 2,
    },
  ],
};
