import type { SpecialServiceApprovalItem } from './types';

export const mockSpecialServiceApprovals: SpecialServiceApprovalItem[] = [
  {
    id: 'SSR-001',
    applicationNo: 'SR-2026-4821',
    collegeCode: 'COL001',
    collegeName: 'Global Institute of Technology & Management',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 1,
    serviceCode: 'LOCATION_CHANGE',
    serviceName: 'Change of College Location / Premises',
    baseFee: 150000,
    gstAmount: 27000,
    feeAmount: 177000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_849201',
    paymentDate: '18 Sep 2026',
    submissionDate: '18 Sep 2026',
    status: 'Pending Scrutiny',
    declarationAccepted: true,
    documents: [
      {
        id: 'doc-1',
        name: 'Registered_30Year_Lease_Deed.pdf',
        documentType:
          '1. Registered 30-Year Lease / Land Registry Deed (PDF Item 9)',
        fileSize: '4.2 MB',
        isVerified: true,
      },
      {
        id: 'doc-2',
        name: 'Certified_Building_Map_Plan.pdf',
        documentType: '2. Certified Building Map & Plan (PDF Item 10)',
        fileSize: '5.1 MB',
        isVerified: false,
      },
    ],
    details: {
      currentAddress: '12, MG Road, Indore - 452001',
      state: 'Madhya Pradesh',
      district: 'Indore',
      tehsil: 'Sanwer',
      pinCode: '453551',
      proposedAddress: 'Khasra No 14/2, Super Corridor, Sanwer Road',
      landArea: '6.50',
      khasraNo: '14/2, 14/3, 15/1',
      builtUpArea: '48000',
    },
  },
  {
    id: 'SSR-002',
    applicationNo: 'SR-2026-3194',
    collegeCode: 'COL008',
    collegeName: 'Holkar Science College',
    collegeType: 'govt',
    academicYear: '2025-2026',
    serviceId: 1,
    serviceCode: 'LOCATION_CHANGE',
    serviceName: 'Change of College Location / Premises',
    baseFee: 0,
    gstAmount: 0,
    feeAmount: 0,
    isFeeExempted: true,
    paymentStatus: 'Exempted',
    transactionId: 'EXEMPTED_GOVT_COLLEGE',
    paymentDate: '10 Sep 2026',
    submissionDate: '10 Sep 2026',
    status: 'Pending Scrutiny',
    declarationAccepted: true,
    documents: [
      {
        id: 'doc-4',
        name: 'Govt_Land_Allotment_Order.pdf',
        documentType: 'Govt Land Allotment & Possession Deed',
        fileSize: '3.8 MB',
        isVerified: true,
      },
      {
        id: 'doc-5',
        name: 'PWD_Certified_Building_Plan.pdf',
        documentType: 'PWD Certified Building Map & Plan',
        fileSize: '6.2 MB',
        isVerified: true,
      },
    ],
    details: {
      currentAddress: 'AB Road, Bhawarkua, Indore - 452001',
      state: 'Madhya Pradesh',
      district: 'Indore',
      tehsil: 'Sanwer',
      pinCode: '453551',
      proposedAddress:
        'New Campus, Khasra No 18/4, Super Corridor, Sanwer Road, Indore',
      landArea: '10.00',
      khasraNo: '18/4, 18/5',
      builtUpArea: '65000',
    },
  },
  {
    id: 'SSR-003',
    applicationNo: 'SR-2026-7731',
    collegeCode: 'COL014',
    collegeName: 'Renaissance College of Commerce & Management',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 3,
    serviceCode: 'SOCIETY_CHANGE',
    serviceName: 'Change of Trust / Society / Company',
    baseFee: 300000,
    gstAmount: 54000,
    feeAmount: 354000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_612874',
    paymentDate: '08 Sep 2026',
    submissionDate: '08 Sep 2026',
    status: 'Approved',
    declarationAccepted: true,
    committeeOrderNo: 'DAVV/AFF/2026/SP-402',
    scrutinyRemarks:
      'Society bylaws, Registrar of Societies certificate, and transfer deed verified by Standing Committee. Handover approved.',
    reviewedBy: 'Dr. R. K. Sharma (DCDC Member)',
    reviewedDate: '14 Sep 2026',
    documents: [
      {
        id: 'doc-6',
        name: 'New_Society_Reg_Certificate.pdf',
        documentType: 'Society Registration Certificate',
        fileSize: '1.2 MB',
        isVerified: true,
      },
      {
        id: 'doc-7',
        name: 'Transfer_Deed_Handover_NOC.pdf',
        documentType: 'Transfer Deed & Governing Body Resolution',
        fileSize: '3.6 MB',
        isVerified: true,
      },
    ],
    details: {
      currentSocietyName: 'Shri Balaji Educational Society',
      proposedSocietyName: 'Vidyasagar Higher Education Foundation',
      societyRegNo: 'SOC/IND/2026/9821',
    },
  },
  {
    id: 'SSR-004',
    applicationNo: 'SR-2026-5510',
    collegeCode: 'COL022',
    collegeName: 'Prestige Institute of Management & Research',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 4,
    serviceCode: 'SEAT_REDUCTION',
    serviceName: 'Course Seat Capacity Reduction',
    baseFee: 50000,
    gstAmount: 9000,
    feeAmount: 59000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_451908',
    paymentDate: '05 Sep 2026',
    submissionDate: '05 Sep 2026',
    status: 'Approved',
    declarationAccepted: true,
    committeeOrderNo: 'DAVV/AFF/2026/SP-389',
    scrutinyRemarks:
      'Reduction from 120 to 60 seats in B.Com (Computer Applications) approved as per college request and faculty balance.',
    reviewedBy: 'Prof. Anjali Saxena (Dean Academics)',
    reviewedDate: '11 Sep 2026',
    documents: [
      {
        id: 'doc-8',
        name: 'Governing_Body_Seat_Reduction.pdf',
        documentType: 'College Governing Body Resolution',
        fileSize: '1.5 MB',
        isVerified: true,
      },
    ],
    details: {
      courseName: 'B.Com (Computer Applications)',
      currentSeats: 120,
      proposedSeats: 60,
      seatReductionReason:
        'Declining student admissions in computing subjects and optimization of infrastructure.',
    },
  },
  {
    id: 'SSR-005',
    applicationNo: 'SR-2026-9024',
    collegeCode: 'COL035',
    collegeName: 'Shri Gujarati Samaj College',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 5,
    serviceCode: 'COURSE_CLOSURE',
    serviceName: 'Course / Programme Progressive Closure',
    baseFee: 50000,
    gstAmount: 9000,
    feeAmount: 59000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_982110',
    paymentDate: '02 Sep 2026',
    submissionDate: '02 Sep 2026',
    status: 'Pending Scrutiny',
    declarationAccepted: true,
    scrutinyRemarks:
      'Student transfer plan lacks signed undertaking from receiving college for 3rd semester electronics lab practicals.',
    reviewedBy: 'Dr. M. L. Verma',
    reviewedDate: '09 Sep 2026',
    documents: [
      {
        id: 'doc-9',
        name: 'Progressive_Closure_Plan.pdf',
        documentType: 'Closure Roadmap & Governing Body Resolution',
        fileSize: '2.1 MB',
        isVerified: true,
      },
      {
        id: 'doc-10',
        name: 'Student_Exam_Undertaking.pdf',
        documentType: 'Student Exam Completion & Fee Clearance',
        fileSize: '1.1 MB',
        isVerified: false,
      },
    ],
    details: {
      closureCourseName: 'B.Sc (Electronics)',
      batchYear: '2024-2027 (Last enrolled batch)',
      studentTransferPlan:
        'All existing 18 students will complete exams with no fresh intake.',
    },
  },
  {
    id: 'SSR-006',
    applicationNo: 'SR-2026-6182',
    collegeCode: 'COL041',
    collegeName: 'Indore Institute of Science & Technology',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 7,
    serviceCode: 'ADD_ON_COURSE',
    serviceName:
      'Add-on Course (Certificate / Diploma / Adv. Diploma - 1 Year)',
    baseFee: 50000,
    gstAmount: 9000,
    feeAmount: 59000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_761203',
    paymentDate: '01 Sep 2026',
    submissionDate: '01 Sep 2026',
    status: 'Pending Scrutiny',
    declarationAccepted: true,
    documents: [
      {
        id: 'doc-11',
        name: 'Curriculum_Syllabus_Proposal.pdf',
        documentType: 'Detailed Syllabus & NEP Framework',
        fileSize: '3.4 MB',
        isVerified: true,
      },
      {
        id: 'doc-12',
        name: 'Faculty_Profile_Lab_Setup.pdf',
        documentType: 'College Academic Council / BOS Recommendation',
        fileSize: '2.8 MB',
        isVerified: true,
      },
    ],
    details: {
      addonCourseTitle: 'Certificate Course in AI & Data Science',
      addonCourseType: 'Certificate',
      addonIntake: 40,
    },
  },
  {
    id: 'SSR-007',
    applicationNo: 'SR-2026-1190',
    collegeCode: 'COL050',
    collegeName: 'Malwa Professional Institute',
    collegeType: 'private',
    academicYear: '2025-2026',
    serviceId: 6,
    serviceCode: 'COLLEGE_CLOSURE',
    serviceName: 'Complete College Closure',
    baseFee: 50000,
    gstAmount: 9000,
    feeAmount: 59000,
    isFeeExempted: false,
    paymentStatus: 'Paid',
    transactionId: 'TXN_MPONLINE_341902',
    paymentDate: '28 Aug 2026',
    submissionDate: '28 Aug 2026',
    status: 'Deficiency Raised',
    declarationAccepted: true,
    scrutinyRemarks:
      'Staff gratuity clearance undertaking does not cover 4 non-teaching personnel who filed petition. Rectification required.',
    deficiencyDetails: {
      remarks:
        'Staff gratuity clearance undertaking does not cover 4 non-teaching personnel who filed petition. Rectification required.',
      raisedDate: '06 Sep 2026',
      raisedBy: 'Standing Committee DCDC',
    },
    reviewedBy: 'Standing Committee DCDC',
    reviewedDate: '06 Sep 2026',
    documents: [
      {
        id: 'doc-13',
        name: 'Staff_NOC_Gratuity.pdf',
        documentType: 'Staff Gratuity & PF Settlement Undertaking / NOC',
        fileSize: '2.0 MB',
        isVerified: false,
      },
    ],
    details: {
      collegeClosureReason:
        'Financial consolidation and lack of eligible admissions over 3 consecutive academic years.',
      staffSettlementNoc:
        'All 24 staff members gratuity and provident funds fully settled.',
    },
  },
];
