// =============================================================================
// Bill Management & Tracking — Static Mock Data
// Single source of truth for all static data in this module.
// Each api.ts file imports from here instead of making real HTTP calls.
// =============================================================================

// ─── VENDORS ─────────────────────────────────────────────────────────────────
export const BT_VENDORS = [
  { id: 1, name: 'Sharma Stationery Pvt. Ltd.', gstin: '07AAACS1234A1Z5' },
  { id: 2, name: 'TechServe Solutions', gstin: '27AABCT5432B2Z1' },
  { id: 3, name: 'National Builders & Contractors', gstin: '09AABCN2345C3Z7' },
  { id: 4, name: 'Office Supplies Co.', gstin: '06AABCO6789D4Z3' },
  { id: 5, name: 'Rajdhani Electricals', gstin: '07AABCR4567E5Z9' },
  { id: 6, name: 'Infra Works Ltd.', gstin: '19AABCI3456F6Z2' },
  { id: 7, name: 'Green Clean Services', gstin: '27AABCG5678G7Z4' },
  { id: 8, name: 'Modern Furniture House', gstin: '09AABCM7890H8Z6' },
];

// ─── EMPLOYEES ───────────────────────────────────────────────────────────────
export const BT_EMPLOYEES = [
  { id: 1, name: 'Dr. Anil Kumar', empId: 'EMP001', dept: 'Physics' },
  { id: 2, name: 'Prof. Sunita Sharma', empId: 'EMP002', dept: 'Chemistry' },
  { id: 3, name: 'Mr. Ramesh Gupta', empId: 'EMP003', dept: 'Administration' },
  { id: 4, name: 'Dr. Priya Mehta', empId: 'EMP004', dept: 'Mathematics' },
  { id: 5, name: 'Mr. Vijay Sinha', empId: 'EMP005', dept: 'Accounts' },
  { id: 6, name: 'Dr. Neha Verma', empId: 'EMP006', dept: 'Computer Science' },
  { id: 7, name: 'Prof. Alok Tiwari', empId: 'EMP007', dept: 'English' },
  { id: 8, name: 'Ms. Pooja Yadav', empId: 'EMP008', dept: 'Library' },
];

// ─── BANK ACCOUNTS ───────────────────────────────────────────────────────────
export const BT_BANK_ACCOUNTS = [
  {
    id: 1,
    name: 'SBI Main Account',
    accountNo: 'SB10023456789',
    ifsc: 'SBIN0001234',
  },
  {
    id: 2,
    name: 'PNB Payroll Account',
    accountNo: 'PNB20034567890',
    ifsc: 'PUNB0123456',
  },
  {
    id: 3,
    name: 'Canara Bank Account',
    accountNo: 'CAN30045678901',
    ifsc: 'CNRB0002345',
  },
  {
    id: 4,
    name: 'HDFC Vendor Account',
    accountNo: 'HDFC40056789012',
    ifsc: 'HDFC0003456',
  },
];

// ─── BUDGET HEADS ─────────────────────────────────────────────────────────────
export const BT_BUDGET_HEADS = [
  { id: 1, code: 'BH-101', name: 'Office Stationery & Supplies' },
  { id: 2, code: 'BH-102', name: 'IT Equipment & Maintenance' },
  { id: 3, code: 'BH-103', name: 'Civil Works & Infrastructure' },
  { id: 4, code: 'BH-104', name: 'Electrical Works' },
  { id: 5, code: 'BH-105', name: 'Housekeeping & Sanitation' },
  { id: 6, code: 'BH-106', name: 'Furniture & Fixtures' },
  { id: 7, code: 'BH-107', name: 'Travel & Conveyance' },
  { id: 8, code: 'BH-108', name: 'Medical Reimbursement' },
  { id: 9, code: 'BH-109', name: 'Training & Development' },
  { id: 10, code: 'BH-110', name: 'Miscellaneous Expenditure' },
];

// ─── BILL RECEIPTS ────────────────────────────────────────────────────────────
export const BT_BILL_RECEIPTS = [
  {
    id: 1,
    receiptNo: 'BRC-2025-001',
    billType: 'Vendor',
    partyName: 'Sharma Stationery Pvt. Ltd.',
    invoiceNo: 'INV-SS-2025-101',
    invoiceDate: '2025-04-05',
    invoiceAmount: 45000,
    receivedDate: '2025-04-07',
    receivedBy: 'Mr. Ramesh Gupta',
    status: 'In Verification',
    remarks: 'Stationery for semester 1',
  },
  {
    id: 2,
    receiptNo: 'BRC-2025-002',
    billType: 'Vendor',
    partyName: 'TechServe Solutions',
    invoiceNo: 'INV-TS-2025-056',
    invoiceDate: '2025-04-10',
    invoiceAmount: 185000,
    receivedDate: '2025-04-12',
    receivedBy: 'Mr. Vijay Sinha',
    status: 'Received',
    remarks: 'Annual server maintenance',
  },
  {
    id: 3,
    receiptNo: 'BRC-2025-003',
    billType: 'Employee',
    partyName: 'Dr. Anil Kumar',
    invoiceNo: 'CLAIM-EMP001-APR',
    invoiceDate: '2025-04-15',
    invoiceAmount: 12500,
    receivedDate: '2025-04-16',
    receivedBy: 'Ms. Pooja Yadav',
    status: 'Received',
    remarks: 'TA-DA for conference Delhi',
  },
  {
    id: 4,
    receiptNo: 'BRC-2025-004',
    billType: 'Vendor',
    partyName: 'National Builders & Contractors',
    invoiceNo: 'INV-NBC-2025-012',
    invoiceDate: '2025-04-18',
    invoiceAmount: 750000,
    receivedDate: '2025-04-20',
    receivedBy: 'Mr. Ramesh Gupta',
    status: 'In Verification',
    remarks: 'Civil repair work Block-B',
  },
  {
    id: 5,
    receiptNo: 'BRC-2025-005',
    billType: 'Employee',
    partyName: 'Prof. Sunita Sharma',
    invoiceNo: 'CLAIM-EMP002-APR',
    invoiceDate: '2025-04-20',
    invoiceAmount: 8500,
    receivedDate: '2025-04-21',
    receivedBy: 'Ms. Pooja Yadav',
    status: 'Draft',
    remarks: 'Medical reimbursement',
  },
  {
    id: 6,
    receiptNo: 'BRC-2025-006',
    billType: 'Vendor',
    partyName: 'Rajdhani Electricals',
    invoiceNo: 'INV-RE-2025-034',
    invoiceDate: '2025-04-22',
    invoiceAmount: 95000,
    receivedDate: '2025-04-24',
    receivedBy: 'Mr. Vijay Sinha',
    status: 'Received',
    remarks: 'Electrical fittings lab block',
  },
  {
    id: 7,
    receiptNo: 'BRC-2025-007',
    billType: 'Vendor',
    partyName: 'Green Clean Services',
    invoiceNo: 'INV-GCS-2025-089',
    invoiceDate: '2025-05-01',
    invoiceAmount: 38000,
    receivedDate: '2025-05-02',
    receivedBy: 'Mr. Ramesh Gupta',
    status: 'In Verification',
    remarks: 'Monthly housekeeping April',
  },
  {
    id: 8,
    receiptNo: 'BRC-2025-008',
    billType: 'Vendor',
    partyName: 'Modern Furniture House',
    invoiceNo: 'INV-MFH-2025-007',
    invoiceDate: '2025-05-05',
    invoiceAmount: 320000,
    receivedDate: '2025-05-07',
    receivedBy: 'Mr. Vijay Sinha',
    status: 'Received',
    remarks: 'Furniture for new classrooms',
  },
];

// ─── VENDOR BILLS ─────────────────────────────────────────────────────────────
export const BT_VENDOR_BILLS = [
  {
    id: 1,
    billNo: 'VB-2025-001',
    billDate: '2025-04-08',
    vendor: 'Sharma Stationery Pvt. Ltd.',
    invoiceNo: 'INV-SS-2025-101',
    invoiceDate: '2025-04-05',
    baseAmount: 45000,
    gstType: 'CGST+SGST',
    gstPct: 12,
    gstAmount: 5400,
    tdsPct: 2,
    tdsAmount: 900,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 0,
    netPayable: 49500,
    budgetHead: 'Office Stationery & Supplies',
    dueDate: '2025-04-30',
    status: 'Approved',
  },
  {
    id: 2,
    billNo: 'VB-2025-002',
    billDate: '2025-04-13',
    vendor: 'TechServe Solutions',
    invoiceNo: 'INV-TS-2025-056',
    invoiceDate: '2025-04-10',
    baseAmount: 185000,
    gstType: 'IGST',
    gstPct: 18,
    gstAmount: 33300,
    tdsPct: 10,
    tdsAmount: 18500,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 5000,
    netPayable: 194800,
    budgetHead: 'IT Equipment & Maintenance',
    dueDate: '2025-05-13',
    status: 'Paid',
  },
  {
    id: 3,
    billNo: 'VB-2025-003',
    billDate: '2025-04-21',
    vendor: 'National Builders & Contractors',
    invoiceNo: 'INV-NBC-2025-012',
    invoiceDate: '2025-04-18',
    baseAmount: 750000,
    gstType: 'CGST+SGST',
    gstPct: 18,
    gstAmount: 135000,
    tdsPct: 2,
    tdsAmount: 15000,
    cessPct: 1,
    cessAmount: 1350,
    securityDeposit: 37500,
    netPayable: 831150,
    budgetHead: 'Civil Works & Infrastructure',
    dueDate: '2025-05-21',
    status: 'Verified',
  },
  {
    id: 4,
    billNo: 'VB-2025-004',
    billDate: '2025-04-25',
    vendor: 'Rajdhani Electricals',
    invoiceNo: 'INV-RE-2025-034',
    invoiceDate: '2025-04-22',
    baseAmount: 95000,
    gstType: 'CGST+SGST',
    gstPct: 18,
    gstAmount: 17100,
    tdsPct: 1,
    tdsAmount: 950,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 0,
    netPayable: 111150,
    budgetHead: 'Electrical Works',
    dueDate: '2025-05-25',
    status: 'Submitted',
  },
  {
    id: 5,
    billNo: 'VB-2025-005',
    billDate: '2025-05-03',
    vendor: 'Green Clean Services',
    invoiceNo: 'INV-GCS-2025-089',
    invoiceDate: '2025-05-01',
    baseAmount: 38000,
    gstType: 'CGST+SGST',
    gstPct: 18,
    gstAmount: 6840,
    tdsPct: 2,
    tdsAmount: 760,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 0,
    netPayable: 44080,
    budgetHead: 'Housekeeping & Sanitation',
    dueDate: '2025-05-31',
    status: 'Submitted',
  },
  {
    id: 6,
    billNo: 'VB-2025-006',
    billDate: '2025-05-08',
    vendor: 'Modern Furniture House',
    invoiceNo: 'INV-MFH-2025-007',
    invoiceDate: '2025-05-05',
    baseAmount: 320000,
    gstType: 'IGST',
    gstPct: 28,
    gstAmount: 89600,
    tdsPct: 2,
    tdsAmount: 6400,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 16000,
    netPayable: 387200,
    budgetHead: 'Furniture & Fixtures',
    dueDate: '2025-06-08',
    status: 'Draft',
  },
  {
    id: 7,
    billNo: 'VB-2025-007',
    billDate: '2025-05-12',
    vendor: 'Office Supplies Co.',
    invoiceNo: 'INV-OSC-2025-145',
    invoiceDate: '2025-05-10',
    baseAmount: 22500,
    gstType: 'CGST+SGST',
    gstPct: 12,
    gstAmount: 2700,
    tdsPct: 1,
    tdsAmount: 225,
    cessPct: 0,
    cessAmount: 0,
    securityDeposit: 0,
    netPayable: 24975,
    budgetHead: 'Office Stationery & Supplies',
    dueDate: '2025-06-10',
    status: 'Approved',
  },
  {
    id: 8,
    billNo: 'VB-2025-008',
    billDate: '2025-05-20',
    vendor: 'Infra Works Ltd.',
    invoiceNo: 'INV-IW-2025-023',
    invoiceDate: '2025-05-18',
    baseAmount: 1250000,
    gstType: 'CGST+SGST',
    gstPct: 18,
    gstAmount: 225000,
    tdsPct: 2,
    tdsAmount: 25000,
    cessPct: 1,
    cessAmount: 2250,
    securityDeposit: 62500,
    netPayable: 1389750,
    budgetHead: 'Civil Works & Infrastructure',
    dueDate: '2025-06-20',
    status: 'Paid',
  },
];

// ─── EMPLOYEE CLAIMS ──────────────────────────────────────────────────────────
export const BT_EMPLOYEE_CLAIMS = [
  {
    id: 1,
    claimNo: 'EC-2025-001',
    employeeName: 'Dr. Anil Kumar',
    employeeId: 'EMP001',
    claimType: 'TA-DA',
    claimDate: '2025-04-16',
    claimAmount: 12500,
    description: 'TA-DA for National Physics Conference, New Delhi (14-15 Apr)',
    budgetHead: 'Travel & Conveyance',
    status: 'Paid',
  },
  {
    id: 2,
    claimNo: 'EC-2025-002',
    employeeName: 'Prof. Sunita Sharma',
    employeeId: 'EMP002',
    claimType: 'Medical',
    claimDate: '2025-04-21',
    claimAmount: 8500,
    description: 'Medical reimbursement - hospitalization April 2025',
    budgetHead: 'Medical Reimbursement',
    status: 'Submitted',
  },
  {
    id: 3,
    claimNo: 'EC-2025-003',
    employeeName: 'Mr. Ramesh Gupta',
    employeeId: 'EMP003',
    claimType: 'Travel',
    claimDate: '2025-04-28',
    claimAmount: 4200,
    description: 'Travel to Lucknow for procurement meeting',
    budgetHead: 'Travel & Conveyance',
    status: 'Approved',
  },
  {
    id: 4,
    claimNo: 'EC-2025-004',
    employeeName: 'Dr. Priya Mehta',
    employeeId: 'EMP004',
    claimType: 'TA-DA',
    claimDate: '2025-05-02',
    claimAmount: 18000,
    description: 'TA-DA for International Math Workshop, Bengaluru',
    budgetHead: 'Travel & Conveyance',
    status: 'Verified',
  },
  {
    id: 5,
    claimNo: 'EC-2025-005',
    employeeName: 'Dr. Neha Verma',
    employeeId: 'EMP006',
    claimType: 'Training',
    claimDate: '2025-05-10',
    claimAmount: 25000,
    description: 'Online AI/ML certification course fee',
    budgetHead: 'Training & Development',
    status: 'Submitted',
  },
  {
    id: 6,
    claimNo: 'EC-2025-006',
    employeeName: 'Prof. Alok Tiwari',
    employeeId: 'EMP007',
    claimType: 'Conveyance',
    claimDate: '2025-05-15',
    claimAmount: 2800,
    description: 'Local conveyance - exam duty May 2025',
    budgetHead: 'Travel & Conveyance',
    status: 'Draft',
  },
  {
    id: 7,
    claimNo: 'EC-2025-007',
    employeeName: 'Mr. Vijay Sinha',
    employeeId: 'EMP005',
    claimType: 'Medical',
    claimDate: '2025-05-18',
    claimAmount: 6300,
    description: 'Medical reimbursement - diagnostics and medicines',
    budgetHead: 'Medical Reimbursement',
    status: 'Approved',
  },
  {
    id: 8,
    claimNo: 'EC-2025-008',
    employeeName: 'Ms. Pooja Yadav',
    employeeId: 'EMP008',
    claimType: 'Other',
    claimDate: '2025-05-22',
    claimAmount: 3500,
    description: 'Book purchase for library section',
    budgetHead: 'Miscellaneous Expenditure',
    status: 'Submitted',
  },
];

// ─── PAYMENT VOUCHERS ─────────────────────────────────────────────────────────
export const BT_PAYMENT_VOUCHERS = [
  {
    id: 1,
    voucherNo: 'PV-2025-001',
    billRef: 'VB-2025-002',
    party: 'TechServe Solutions',
    paymentDate: '2025-04-25',
    bankAccount: 'SBI Main Account',
    paymentMode: 'NEFT',
    transactionRef: 'NEFT25115001234',
    amount: 194800,
    remarks: 'Full payment against IT maintenance bill',
    status: 'Paid',
  },
  {
    id: 2,
    voucherNo: 'PV-2025-002',
    billRef: 'EC-2025-001',
    party: 'Dr. Anil Kumar',
    paymentDate: '2025-04-28',
    bankAccount: 'PNB Payroll Account',
    paymentMode: 'NEFT',
    transactionRef: 'NEFT25118002345',
    amount: 12500,
    remarks: 'TA-DA reimbursement',
    status: 'Paid',
  },
  {
    id: 3,
    voucherNo: 'PV-2025-003',
    billRef: 'VB-2025-001',
    party: 'Sharma Stationery Pvt. Ltd.',
    paymentDate: '2025-04-29',
    bankAccount: 'HDFC Vendor Account',
    paymentMode: 'RTGS',
    transactionRef: 'RTGS25119003456',
    amount: 49500,
    remarks: 'Stationery bill payment',
    status: 'Paid',
  },
  {
    id: 4,
    voucherNo: 'PV-2025-004',
    billRef: 'VB-2025-008',
    party: 'Infra Works Ltd.',
    paymentDate: '2025-05-30',
    bankAccount: 'SBI Main Account',
    paymentMode: 'RTGS',
    transactionRef: 'RTGS25150004567',
    amount: 1389750,
    remarks: 'Civil construction first installment',
    status: 'Paid',
  },
  {
    id: 5,
    voucherNo: 'PV-2025-005',
    billRef: 'EC-2025-003',
    party: 'Mr. Ramesh Gupta',
    paymentDate: '2025-06-02',
    bankAccount: 'PNB Payroll Account',
    paymentMode: 'NEFT',
    transactionRef: 'NEFT25153005678',
    amount: 4200,
    remarks: 'Travel reimbursement',
    status: 'Paid',
  },
  {
    id: 6,
    voucherNo: 'PV-2025-006',
    billRef: 'VB-2025-007',
    party: 'Office Supplies Co.',
    paymentDate: '2025-06-05',
    bankAccount: 'HDFC Vendor Account',
    paymentMode: 'Cheque',
    transactionRef: 'CHQ-234567',
    amount: 24975,
    remarks: 'Office supplies payment',
    status: 'Paid',
  },
  {
    id: 7,
    voucherNo: 'PV-2025-007',
    billRef: 'EC-2025-007',
    party: 'Mr. Vijay Sinha',
    paymentDate: '2025-06-10',
    bankAccount: 'PNB Payroll Account',
    paymentMode: 'NEFT',
    transactionRef: 'NEFT25161006789',
    amount: 6300,
    remarks: 'Medical reimbursement',
    status: 'Paid',
  },
];

// ─── CANCELLED BILLS ──────────────────────────────────────────────────────────
export const BT_CANCELLED_BILLS = [
  {
    id: 1,
    billNo: 'VB-2025-C01',
    billType: 'Vendor',
    party: 'ABC Traders',
    amount: 55000,
    cancelledAtStage: 'Verification',
    cancelledBy: 'Mr. Vijay Sinha',
    reason: 'Invoice amount mismatch with purchase order. Vendor to resubmit.',
    cancelledDate: '2025-04-19',
  },
  {
    id: 2,
    billNo: 'EC-2025-C01',
    billType: 'Employee',
    party: 'Dr. K.L. Singh',
    amount: 35000,
    cancelledAtStage: 'Approval',
    cancelledBy: 'Finance Director',
    reason: 'Travel not pre-approved by HOD. Claim rejected as per policy.',
    cancelledDate: '2025-04-30',
  },
  {
    id: 3,
    billNo: 'VB-2025-C02',
    billType: 'Vendor',
    party: 'XYZ Engineering',
    amount: 420000,
    cancelledAtStage: 'Verification',
    cancelledBy: 'Mr. Ramesh Gupta',
    reason:
      'Work completion certificate not submitted. Bill held for resubmission.',
    cancelledDate: '2025-05-08',
  },
  {
    id: 4,
    billNo: 'EC-2025-C02',
    billType: 'Employee',
    party: 'Prof. R.K. Jain',
    amount: 12000,
    cancelledAtStage: 'Approval',
    cancelledBy: 'Finance Director',
    reason: 'Budget head exhausted for this financial year.',
    cancelledDate: '2025-05-22',
  },
  {
    id: 5,
    billNo: 'VB-2025-C03',
    billType: 'Vendor',
    party: 'Quick Print Services',
    amount: 18500,
    cancelledAtStage: 'Receipt',
    cancelledBy: 'Mr. Vijay Sinha',
    reason: 'Duplicate invoice submitted. Original already processed.',
    cancelledDate: '2025-06-01',
  },
];

// ─── DASHBOARD KPIs ───────────────────────────────────────────────────────────
export const BT_DASHBOARD_KPIS = {
  totalBillsThisMonth: 23,
  pendingApproval: 7,
  paidThisMonth: 2461275,
  overdueBills: 3,
  vendorBillsCount: 15,
  employeeClaimsCount: 8,
  cancelledBillsCount: 5,
  totalDeductions: 398725,
};

// ─── TRACKING TIMELINES ───────────────────────────────────────────────────────
export const BT_TRACKING_DATA = [
  {
    billRef: 'VB-2025-001',
    currentStage: 3, // 0: Received, 1: Verified, 2: Approved, 3: Paid
    events: [
      {
        status: 'Received',
        date: '2025-04-07',
        remarks: 'Bill received at finance desk by Mr. Ramesh Gupta',
      },
      {
        status: 'Verified',
        date: '2025-04-12',
        remarks: 'Amount and taxes verified. Sent for approval.',
      },
      {
        status: 'Approved',
        date: '2025-04-20',
        remarks: 'Approved by Finance Director.',
      },
      {
        status: 'Paid',
        date: '2025-04-29',
        remarks: 'Payment processed via RTGS (Ref: RTGS25119003456).',
      },
    ],
  },
  {
    billRef: 'VB-2025-006',
    currentStage: 0,
    events: [
      {
        status: 'Received',
        date: '2025-05-07',
        remarks: 'Bill received at finance desk. Pending verification.',
      },
    ],
  },
  {
    billRef: 'VB-2025-C01',
    currentStage: -1, // Cancelled
    events: [
      {
        status: 'Received',
        date: '2025-04-15',
        remarks: 'Bill received at finance desk',
      },
      {
        status: 'Cancelled',
        date: '2025-04-19',
        remarks:
          'Invoice amount mismatch with purchase order. Vendor to resubmit.',
      },
    ],
  },
  {
    billRef: 'EC-2025-001',
    currentStage: 3,
    events: [
      {
        status: 'Received',
        date: '2025-04-16',
        remarks: 'Claim submitted online',
      },
      { status: 'Verified', date: '2025-04-18', remarks: 'Documents verified' },
      { status: 'Approved', date: '2025-04-22', remarks: 'Approved by HOD' },
      {
        status: 'Paid',
        date: '2025-04-28',
        remarks: 'Payment processed via NEFT',
      },
    ],
  },
];
