export const clubsList = [
  {
    id: 1,
    name: 'Robotics Club',
    category: 'Technical',
    status: 'Active',
    president: 'Rahul Sharma',
    memberCount: 120,
    establishedYear: 2018,
  },
  {
    id: 2,
    name: 'Cultural Committee',
    category: 'Cultural',
    status: 'Active',
    president: 'Sneha Patel',
    memberCount: 250,
    establishedYear: 2015,
  },
  {
    id: 3,
    name: 'Debating Society',
    category: 'Literary',
    status: 'Active',
    president: 'Arjun Verma',
    memberCount: 85,
    establishedYear: 2019,
  },
  {
    id: 4,
    name: 'Photography Club',
    category: 'Arts',
    status: 'Active',
    president: 'Nidhi Gupta',
    memberCount: 150,
    establishedYear: 2020,
  },
  {
    id: 5,
    name: 'Sports Club',
    category: 'Sports',
    status: 'Inactive',
    president: 'Vikram Singh',
    memberCount: 300,
    establishedYear: 2014,
  },
];

export const clubEvents = [
  {
    id: 1,
    title: 'RoboWars 2024',
    club: 'Robotics Club',
    date: '2024-10-15',
    venue: 'Main Auditorium',
    status: 'Upcoming',
    attendees: 150,
  },
  {
    id: 2,
    title: 'Annual Cultural Fest',
    club: 'Cultural Committee',
    date: '2024-11-20',
    venue: 'Campus Grounds',
    status: 'Planned',
    attendees: 500,
  },
  {
    id: 3,
    title: 'Inter-college Debate',
    club: 'Debating Society',
    date: '2024-09-05',
    venue: 'Seminar Hall A',
    status: 'Completed',
    attendees: 100,
  },
];

export const clubMembers = [
  {
    id: 101,
    studentName: 'Amit Kumar',
    enrollmentNo: 'EN2024001',
    club: 'Robotics Club',
    role: 'Member',
    joinDate: '2024-08-01',
  },
  {
    id: 102,
    studentName: 'Priya Singh',
    enrollmentNo: 'EN2024002',
    club: 'Cultural Committee',
    role: 'Coordinator',
    joinDate: '2023-08-15',
  },
  {
    id: 103,
    studentName: 'Rohit Das',
    enrollmentNo: 'EN2024003',
    club: 'Debating Society',
    role: 'Member',
    joinDate: '2024-09-01',
  },
];
