import type { Company } from '../types';

export const seedCompanies: Company[] = [
  {
    id: 'co-infosys',
    companyName: 'Infosys Technologies Ltd',
    companyDetails:
      'Global leader in next-generation digital services and consulting.',
    headOffice: 'Electronic City, Bangalore, Karnataka',
    website: 'https://www.infosys.com',
    hrName: 'Priya Sharma',
    hrContact: '+91-9876543210',
    hrEmail: 'priya.sharma@infosys.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-08-15T10:00:00Z',
  },
  {
    id: 'co-tcs',
    companyName: 'Tata Consultancy Services',
    companyDetails:
      'IT services, consulting and business solutions organization.',
    headOffice: 'Bandra Kurla Complex, Mumbai',
    website: 'https://www.tcs.com',
    hrName: 'Rajesh Kumar',
    hrContact: '+91-9876543211',
    hrEmail: 'campus.recruitment@tcs.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-08-20T10:00:00Z',
  },
  {
    id: 'co-amazon',
    companyName: 'Amazon Development Centre',
    companyDetails: 'E-commerce and cloud computing pioneer.',
    headOffice: 'Manyata Tech Park, Bangalore',
    website: 'https://www.amazon.jobs',
    hrName: 'Ananya Reddy',
    hrContact: '+91-9876543212',
    hrEmail: 'ananya.reddy@amazon.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'co-wipro',
    companyName: 'Wipro Limited',
    companyDetails: 'Leading technology services and consulting company.',
    headOffice: 'Sarjapur Road, Bangalore',
    website: 'https://www.wipro.com',
    hrName: 'Suresh Menon',
    hrContact: '+91-9876543213',
    hrEmail: 'suresh.menon@wipro.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-09-05T10:00:00Z',
  },
  {
    id: 'co-zoho',
    companyName: 'Zoho Corporation',
    companyDetails: 'Cloud software suite for businesses.',
    headOffice: 'Estancia, Chennai',
    website: 'https://www.zoho.com',
    hrName: 'Kavitha Iyer',
    hrContact: '+91-9876543214',
    hrEmail: 'kavitha.iyer@zoho.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-09-10T10:00:00Z',
  },
  {
    id: 'co-startup-alpha',
    companyName: 'AlphaTech Solutions',
    companyDetails: 'Early-stage AI startup focused on campus hiring.',
    headOffice: 'HITEC City, Hyderabad',
    website: 'https://alphatech.example.com',
    hrName: 'Neha Gupta',
    hrContact: '+91-9876543215',
    hrEmail: 'hr@alphatech.example.com',
    verificationStatus: 'Pending',
    profileComplete: false,
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'co-startup-beta',
    companyName: 'Beta Innovations Pvt Ltd',
    companyDetails: 'Product-based startup in fintech space.',
    headOffice: 'Sector 62, Noida',
    hrName: 'Arjun Singh',
    hrContact: '+91-9876543216',
    hrEmail: 'careers@betainnov.example.com',
    verificationStatus: 'Pending',
    profileComplete: false,
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'co-deloitte',
    companyName: 'Deloitte Consulting',
    companyDetails: 'Professional services network.',
    headOffice: 'Connaught Place, New Delhi',
    website: 'https://www2.deloitte.com',
    hrName: 'Meera Nair',
    hrContact: '+91-9876543217',
    hrEmail: 'meera.nair@deloitte.com',
    verificationStatus: 'Approved',
    profileComplete: true,
    createdAt: '2024-10-01T10:00:00Z',
  },
];
