import type {
  CompanySeason,
  Opportunity,
  Application,
  TpStudent,
} from '../types';

export const seedCompanySeasons: CompanySeason[] = [
  {
    id: 'cs-1',
    companyId: 'co-infosys',
    seasonId: 'season-2025-jun',
    feeAmount: 25000,
    paymentStatus: 'Paid',
    status: 'Applied',
  },
  {
    id: 'cs-2',
    companyId: 'co-tcs',
    seasonId: 'season-2025-jun',
    feeAmount: 25000,
    paymentStatus: 'Paid',
    status: 'Applied',
  },
  {
    id: 'co-amazon-cs',
    companyId: 'co-amazon',
    seasonId: 'season-2025-dec',
    feeAmount: 15000,
    paymentStatus: 'Pending',
    status: 'Applied',
  },
  {
    id: 'cs-4',
    companyId: 'co-wipro',
    seasonId: 'season-2025-jun',
    feeAmount: 25000,
    paymentStatus: 'Paid',
    status: 'Applied',
  },
  {
    id: 'cs-5',
    companyId: 'co-zoho',
    seasonId: 'season-2025-dec',
    feeAmount: 15000,
    paymentStatus: 'Paid',
    status: 'Applied',
  },
];

export const seedOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    companyId: 'co-infosys',
    title: 'Systems Engineer — Campus Hire',
    opportunityType: 'Placement',
    description: 'Join Infosys as a Systems Engineer through campus placement.',
    seasonId: 'season-2025-jun',
    designation: 'Systems Engineer',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: ['prog-btech-cse', 'prog-btech-ece'],
    eligibility: 'CGPA ≥ 7.0, no active backlogs',
    skillSet: ['Java', 'Data Structures', 'Communication'],
    experience: 'Fresher',
    ctc: '₹4.5 LPA',
    location: 'Bangalore',
    vacancies: 25,
    openingDate: '2025-06-01',
    closingDate: '2025-07-15',
    writtenTest: true,
    interview: true,
    groupDiscussion: true,
    selectionCriteria: 'Aptitude, technical interview, HR round',
    showPost: true,
    status: 'Active',
    applicantCount: 48,
    publishedAt: '2025-06-02T09:00:00Z',
  },
  {
    id: 'opp-2',
    companyId: 'co-tcs',
    title: 'Ninja Hiring — Digital Profile',
    opportunityType: 'Placement',
    description: 'TCS Ninja program for engineering graduates.',
    seasonId: 'season-2025-jun',
    designation: 'Assistant System Engineer',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: [
      'prog-btech-cse',
      'prog-btech-ece',
      'prog-btech-me',
    ],
    eligibility: 'CGPA ≥ 6.5',
    skillSet: ['Programming', 'Aptitude'],
    experience: 'Fresher',
    ctc: '₹3.36 LPA',
    location: 'Pan India',
    vacancies: 40,
    openingDate: '2025-06-05',
    closingDate: '2025-07-20',
    writtenTest: true,
    interview: true,
    groupDiscussion: false,
    selectionCriteria: 'TCS NQT score and interview',
    showPost: true,
    status: 'Active',
    applicantCount: 62,
    publishedAt: '2025-06-06T09:00:00Z',
  },
  {
    id: 'opp-3',
    companyId: 'co-amazon',
    title: 'SDE Intern — Summer 2025',
    opportunityType: 'Internship',
    description: '6-month SDE internship with PPO opportunity.',
    seasonId: 'season-2025-dec',
    designation: 'SDE Intern',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: ['prog-btech-cse', 'prog-mca'],
    eligibility: 'Pre-final year, CGPA ≥ 7.5',
    skillSet: ['DSA', 'System Design', 'Python/Java'],
    experience: 'Fresher',
    ctc: '₹1.2 LPM stipend',
    location: 'Bangalore',
    vacancies: 10,
    openingDate: '2025-11-01',
    closingDate: '2025-12-15',
    writtenTest: true,
    interview: true,
    groupDiscussion: false,
    selectionCriteria: 'Online assessment + 2 technical interviews',
    showPost: true,
    status: 'Active',
    applicantCount: 35,
    publishedAt: '2025-11-02T09:00:00Z',
  },
  {
    id: 'opp-4',
    companyId: 'co-wipro',
    title: 'Project Engineer Trainee',
    opportunityType: 'Placement',
    description: 'Wipro campus hiring for engineering graduates.',
    seasonId: 'season-2025-jun',
    designation: 'Project Engineer',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: ['prog-btech-cse', 'prog-btech-ece'],
    eligibility: 'CGPA ≥ 6.0',
    skillSet: ['C', 'Java', '.NET'],
    experience: 'Fresher',
    ctc: '₹3.5 LPA',
    location: 'Hyderabad',
    vacancies: 20,
    openingDate: '2025-06-10',
    closingDate: '2025-07-25',
    writtenTest: true,
    interview: true,
    groupDiscussion: true,
    selectionCriteria: 'Written test, GD, PI',
    showPost: true,
    status: 'Active',
    applicantCount: 29,
    publishedAt: '2025-06-11T09:00:00Z',
  },
  {
    id: 'opp-5',
    companyId: 'co-zoho',
    title: 'Software Developer — Zoho Corp',
    opportunityType: 'Placement',
    description: 'Direct placement at Zoho Chennai campus.',
    seasonId: 'season-2025-dec',
    designation: 'Member Technical Staff',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: ['prog-btech-cse', 'prog-mca', 'prog-bca'],
    eligibility: 'Strong programming fundamentals',
    skillSet: ['C', 'Java', 'Problem Solving'],
    experience: 'Fresher',
    ctc: '₹7.0 LPA',
    location: 'Chennai',
    vacancies: 15,
    openingDate: '2025-11-05',
    closingDate: '2025-12-20',
    writtenTest: true,
    interview: true,
    groupDiscussion: false,
    selectionCriteria: 'Zoho technical round',
    showPost: true,
    status: 'Active',
    applicantCount: 22,
    publishedAt: '2025-11-06T09:00:00Z',
  },
  {
    id: 'opp-6',
    companyId: 'co-deloitte',
    title: 'Analyst — Consulting',
    opportunityType: 'Placement',
    description: 'Deloitte analyst role for MBA graduates.',
    seasonId: 'season-2025-jun',
    designation: 'Analyst',
    opportunityNature: 'Full time',
    processType: 'On-Campus',
    essentialQualification: ['prog-mba'],
    eligibility: 'MBA final year, CGPA ≥ 7.0',
    skillSet: ['Analytics', 'Communication', 'Excel'],
    experience: 'Fresher',
    ctc: '₹12 LPA',
    location: 'New Delhi',
    vacancies: 5,
    openingDate: '2025-06-15',
    closingDate: '2025-07-30',
    writtenTest: true,
    interview: true,
    groupDiscussion: true,
    selectionCriteria: 'Case study, group discussion, partner interview',
    showPost: true,
    status: 'Draft',
    applicantCount: 0,
  },
];

export const seedStudents: TpStudent[] = [
  {
    id: 'stu-1',
    name: 'Aarav Patel',
    rollNumber: 'CSE21001',
    programmeId: 'prog-btech-cse',
    programmeName: 'B.Tech Computer Science',
    ouId: 'ou-cse',
    batch: '2021-25',
    gender: 'Male',
    category: 'General',
    email: 'aarav.patel@student.edu',
    registered: true,
  },
  {
    id: 'stu-2',
    name: 'Sneha Krishnan',
    rollNumber: 'CSE21045',
    programmeId: 'prog-btech-cse',
    programmeName: 'B.Tech Computer Science',
    ouId: 'ou-cse',
    batch: '2021-25',
    gender: 'Female',
    category: 'OBC',
    email: 'sneha.krishnan@student.edu',
    registered: true,
  },
  {
    id: 'stu-3',
    name: 'Rahul Verma',
    rollNumber: 'ECE21012',
    programmeId: 'prog-btech-ece',
    programmeName: 'B.Tech Electronics',
    ouId: 'ou-ece',
    batch: '2021-25',
    gender: 'Male',
    category: 'SC',
    email: 'rahul.verma@student.edu',
    registered: true,
  },
  {
    id: 'stu-4',
    name: 'Priya Das',
    rollNumber: 'MBA22008',
    programmeId: 'prog-mba',
    programmeName: 'MBA',
    ouId: 'ou-mba',
    batch: '2022-24',
    gender: 'Female',
    category: 'General',
    email: 'priya.das@student.edu',
    registered: true,
  },
];

export const seedApplications: Application[] = [
  {
    id: 'app-1',
    studentId: 'stu-1',
    opportunityId: 'opp-1',
    companyId: 'co-infosys',
    seasonId: 'season-2025-jun',
    appliedAt: '2025-06-10T14:30:00Z',
    hiringStatus: 'Shortlisted',
  },
  {
    id: 'app-2',
    studentId: 'stu-2',
    opportunityId: 'opp-1',
    companyId: 'co-infosys',
    seasonId: 'season-2025-jun',
    appliedAt: '2025-06-11T09:15:00Z',
    hiringStatus: 'Interview Scheduled',
  },
  {
    id: 'app-3',
    studentId: 'stu-1',
    opportunityId: 'opp-2',
    companyId: 'co-tcs',
    seasonId: 'season-2025-jun',
    appliedAt: '2025-06-12T11:00:00Z',
    hiringStatus: 'Applied',
  },
  {
    id: 'app-4',
    studentId: 'stu-3',
    opportunityId: 'opp-2',
    companyId: 'co-tcs',
    seasonId: 'season-2025-jun',
    appliedAt: '2025-06-13T16:45:00Z',
    hiringStatus: 'Written Test Scheduled',
  },
  {
    id: 'app-5',
    studentId: 'stu-2',
    opportunityId: 'opp-3',
    companyId: 'co-amazon',
    seasonId: 'season-2025-dec',
    appliedAt: '2025-11-08T10:00:00Z',
    hiringStatus: 'Selected',
  },
  {
    id: 'app-6',
    studentId: 'stu-4',
    opportunityId: 'opp-6',
    companyId: 'co-deloitte',
    seasonId: 'season-2025-jun',
    appliedAt: '2025-06-20T13:00:00Z',
    hiringStatus: 'Rejected',
  },
];
