import type { StudentProfile } from '../types';

export const sampleStudentProfile: StudentProfile = {
  enrollmentNo: '0101CS211001',
  applicationNo: 'APP2026001',
  applicationDate: '15 Jan 2026',

  firstName: 'Ravi',
  middleName: 'Kumar',
  lastName: 'Sharma',
  email: 'ravi.sharma@university.edu',
  phone: '9876543210',
  gender: 'Male',
  dateOfBirth: '15 May 2006',
  age: 20,
  bloodGroup: 'O+',
  caste: 'General',
  casteCategory: 'GEN',
  nationality: 'Indian',
  religion: 'Hinduism',
  aadharNo: '1234-5678-9012',
  panNo: 'ABCDE1234F',
  ethnicity: 'Indian',
  residencyStatus: 'Resident',

  fatherName: 'Suresh Sharma',
  fatherOccupation: 'Private Service',
  fatherDesignation: 'Manager',
  fatherAnnualIncome: 500000,
  fatherContactNumber: '9876543211',

  motherName: 'Sunita Sharma',
  motherOccupation: 'Housewife',
  motherDesignation: 'N/A',
  motherAnnualIncome: 0,
  motherContactNumber: '9876543212',

  currentAddress: {
    addressType: 'Current',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    tehsil: 'Huzur',
    block: 'Phanda',
    addressLine1: '123, Shyamla Hills',
    addressLine2: 'Near Bhopal Talkies',
    landmark: 'Rose Garden',
    zipcode: '462002',
  },

  permanentAddress: {
    addressType: 'Permanent',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Raisen',
    tehsil: 'Raisen',
    block: 'Raisen Block',
    addressLine1: 'Village & Post - Barrai',
    addressLine2: 'Tehsil - Raisen',
    landmark: 'Near Gram Panchayat',
    zipcode: '464551',
  },

  programme: 'Bachelor of Technology',
  degreeLevel: 'Undergraduate',
  specialisation: 'Computer Science & Engineering',
  programmeMode: 'Regular (Full Time)',
  academicSession: '2026-2027',

  priorEducations: [
    {
      educationLevel: '10th',
      institutionName: 'Kendriya Vidyalaya No.1, Bhopal',
      boardOrUniversity: 'CBSE',
      passingYear: 2020,
      percentage: 88.5,
      cgpa: 9.2,
      subjectsOrStream: 'Science',
      documentType: '10th Marksheet',
      documentName: '10th_Marksheet_Ravi.pdf',
    },
    {
      educationLevel: '12th',
      institutionName: 'Kendriya Vidyalaya No.1, Bhopal',
      boardOrUniversity: 'CBSE',
      passingYear: 2022,
      percentage: 85.0,
      cgpa: 8.8,
      subjectsOrStream: 'Science (PCM)',
      documentType: '12th Marksheet',
      documentName: '12th_Marksheet_Ravi.pdf',
    },
    {
      educationLevel: 'Bachelor',
      institutionName: 'Government College of Engineering, Bhopal',
      boardOrUniversity: 'RGPV',
      passingYear: 2026,
      percentage: 82.3,
      cgpa: 8.5,
      subjectsOrStream: 'Computer Science',
      documentType: 'Degree Certificate',
      documentName: 'UG_Degree_Ravi.pdf',
    },
  ],

  documents: [
    {
      id: 'doc-1',
      name: '10th Marksheet',
      type: 'PDF',
      uploadedAt: '20 Jan 2026',
      size: '245 KB',
      status: 'Verified',
    },
    {
      id: 'doc-2',
      name: '12th Marksheet',
      type: 'PDF',
      uploadedAt: '20 Jan 2026',
      size: '312 KB',
      status: 'Verified',
    },
    {
      id: 'doc-3',
      name: 'UG Degree Certificate',
      type: 'PDF',
      uploadedAt: '25 Jan 2026',
      size: '456 KB',
      status: 'Pending',
    },
    {
      id: 'doc-4',
      name: 'Passport Photo',
      type: 'JPG',
      uploadedAt: '15 Jan 2026',
      size: '124 KB',
      status: 'Verified',
    },
    {
      id: 'doc-5',
      name: 'Aadhar Card',
      type: 'PDF',
      uploadedAt: '15 Jan 2026',
      size: '198 KB',
      status: 'Verified',
    },
    {
      id: 'doc-6',
      name: 'Migration Certificate',
      type: 'PDF',
      uploadedAt: '25 Jan 2026',
      size: '178 KB',
      status: 'Pending',
    },
  ],

  admissionDetails: {
    admissionDate: '01 Aug 2026',
    admissionQuota: 'Merit Based',
    enrollmentNo: '0101CS211001',
    rollNo: 'CS21001',
    batchYear: '2026-2030',
    semester: '1st Semester',
    campus: 'Main Campus, Bhopal',
    scheme: 'Choice Based Credit System (CBCS)',
  },

  applicationStatus: {
    currentStatus: 'Under Review',
    statusColor: 'pending',
    remarks: 'Your application is being processed by the admission committee.',
    lastUpdated: '28 Jan 2026',
  },

  feeSummary: {
    totalFee: 85000,
    paidFee: 25000,
    pendingFee: 60000,
    dueDate: '15 Mar 2026',
    lastPaymentDate: '20 Jan 2026',
    lastPaymentAmount: 25000,
  },

  timeline: [
    {
      date: '15 Jan 2026',
      title: 'Application Submitted',
      description:
        'Application form submitted successfully with all required details.',
      icon: 'pi-check-circle',
      status: 'completed',
    },
    {
      date: '18 Jan 2026',
      title: 'Documents Verified',
      description:
        'Initial document verification completed by the admission office.',
      icon: 'pi-verified',
      status: 'completed',
    },
    {
      date: '25 Jan 2026',
      title: 'Under Review',
      description:
        'Application is currently under review by the admission committee.',
      icon: 'pi-search',
      status: 'current',
    },
    {
      date: 'Pending',
      title: 'Admission Decision',
      description:
        'Final admission decision will be communicated via email and portal.',
      icon: 'pi-envelope',
      status: 'pending',
    },
    {
      date: 'Pending',
      title: 'Fee Payment',
      description: 'Remaining fee to be paid after admission confirmation.',
      icon: 'pi-credit-card',
      status: 'pending',
    },
  ],
};
