export const mockData = {
  // Mock endpoints and data for the Admission Portal feature
  'admission/protected/subject-selection/info': {
    programmeId: 101,
    programmeName: 'Bachelor of Technology (B.Tech)',
    specialisationId: 201,
    specialisationName: 'Computer Science & Engineering',
  },
  'admission/protected/subject-selection/subjects': [
    {
      pssId: 1,
      subjectCode: 'CS601',
      subjectName: 'Compiler Design',
      categoryName: 'Core Theory',
      totalCredits: 4,
      isSelected: true,
    },
    {
      pssId: 2,
      subjectCode: 'CS602',
      subjectName: 'Computer Networks',
      categoryName: 'Core Theory',
      totalCredits: 4,
      isSelected: true,
    },
    {
      pssId: 3,
      subjectCode: 'CS603',
      subjectName: 'Software Engineering',
      categoryName: 'Core Theory',
      totalCredits: 3,
      isSelected: false,
    },
    {
      pssId: 4,
      subjectCode: 'CS604L',
      subjectName: 'Computer Networks Lab',
      categoryName: 'Practical / Laboratory',
      totalCredits: 2,
      isSelected: true,
    },
    {
      pssId: 5,
      subjectCode: 'CS605E',
      subjectName: 'Cloud Computing Architecture',
      categoryName: 'Professional Elective',
      totalCredits: 3,
      isSelected: false,
    },
    {
      pssId: 6,
      subjectCode: 'HU601',
      subjectName: 'Professional Ethics & Human Values',
      categoryName: 'Humanities & Social Sciences',
      totalCredits: 2,
      isSelected: true,
    },
  ],
  'admission/protected/fee-payment/status': {
    isFeePaid: false,
    hasSubjectsSelected: true,
    studentName: 'Ravi Kumar',
    programmeName: 'B.Tech Computer Science & Engineering',
  },
};
