export const INITIAL_ESTATES: ResidentialAllocationManagement.Estate[] = [
  {
    code: 'EST-TAG-401',
    name: 'Tagore Enclave (Type-IV)',
    type: 'Type-IV',
    targetStaff: 'Associate Professors / Deputy Registrars',
    payLevelEligible: 'Level-12 to Level-13A',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'STU Residential Campus, North Wing Enclave',
    pincode: '462033',
    floors: 3,
    flatsCount: 24,
    occupancy: 18,
    available: 6,
    wardenName: 'Prof. S. K. Mukherjee',
    wardenMobile: '9425098765',
    wardenEmail: 'mukherjee.sk@stu.ac.in',
    securityDeposit: 15000,
    hraDeduction: 12000,
    maintenanceFee: 2500,
    waterCharges: 400,
    status: 'Active',
    synopsis:
      'Premium double-balcony apartments featuring solar water systems and gas pipeline support.',
  },
  {
    code: 'EST-ARY-502',
    name: 'Aryabhata Enclave (Type-V Bungalows)',
    type: 'Type-V',
    targetStaff: 'Professors / Deans / Registrar',
    payLevelEligible: 'Level-14 to Level-15',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'STU VVIP Campus, Bungalow Row 1',
    pincode: '462033',
    floors: 1,
    flatsCount: 8,
    occupancy: 7,
    available: 1,
    wardenName: 'Dr. Alok Prasad',
    wardenMobile: '9876543210',
    wardenEmail: 'alok.prasad@stu.ac.in',
    securityDeposit: 30000,
    hraDeduction: 22000,
    maintenanceFee: 5000,
    waterCharges: 800,
    status: 'Active',
    synopsis:
      'Independent bungalow configurations with personal gardens and dedicated server room connections.',
  },
  {
    code: 'EST-VIV-301',
    name: 'Vivekananda Block (Type-III)',
    type: 'Type-III',
    targetStaff: 'Assistant Professors / Section Officers',
    payLevelEligible: 'Level-10 to Level-11',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'STU East Enclave Road',
    pincode: '462033',
    floors: 4,
    flatsCount: 32,
    occupancy: 32,
    available: 0,
    wardenName: 'Shri Rajesh Kumar',
    wardenMobile: '9876543211',
    wardenEmail: 'rajesh.kumar@stu.ac.in',
    securityDeposit: 10000,
    hraDeduction: 8500,
    maintenanceFee: 1500,
    waterCharges: 300,
    status: 'Active',
    synopsis:
      'Mid-tier family apartments with close proximity to the STU Central Primary School.',
  },
];

export const INITIAL_STAFF_APPLICATIONS: ResidentialAllocationManagement.StaffApplication[] =
  [
    {
      id: 'APP-STAFF-2026-001',
      enrollmentNo: 'STU-FAC-102',
      name: 'Dr. Preeti Deshmukh',
      fatherName: 'Satish Deshmukh',
      motherName: 'Lata Deshmukh',
      gender: 'Female',
      dob: '1982-08-22',
      mobile: '9826078122',
      email: 'preeti.d@stu.ac.in',
      department: 'Department of Civil Engineering',
      designation: 'Associate Professor',
      payLevel: 'Level-13A',
      basicPay: 142000,
      dateOfJoining: '2012-06-15',
      permanentAddress: '45, Ring Road, Civil Lines, Jabalpur',
      district: 'Jabalpur',
      city: 'Jabalpur',
      pincode: '482001',
      blockPreference: 'EST-TAG-401',
      quarterPreference: 'Type-IV',
      familyDependents: '3',
      specialRequirement:
        'Medical Priority: Mother-in-law has joint mobility issues, ground floor preferred.',
      emergencyName: 'Dr. Anand Deshmukh',
      emergencyMobile: '9826078120',
      emergencyRelationship: 'Spouse',
      bloodGroup: 'B+',
      medicalCondition: 'None',
      disabilityDetails: 'None',
      allergies: 'None',
      documents: {
        photo: 'preeti_pic.jpg',
        salarySlip: 'pay_slip_may_2026.pdf',
        joiningLetter: 'stu_joining_2012.pdf',
        nocCertificate: 'noc_civil_dept.pdf',
      },
      declaration: true,
      signature: 'Preeti Deshmukh',
      status: 'Pending',
      adminRemarks: '',
      allottedEstate: '',
      allottedFlat: '',
      feeStatus: 'Unpaid',
    },
    {
      id: 'APP-STAFF-2026-002',
      enrollmentNo: 'STU-FAC-782',
      name: 'Dr. Sandeep Kothari',
      fatherName: 'Rajendra Kothari',
      motherName: 'Kamla Kothari',
      gender: 'Male',
      dob: '1978-04-12',
      mobile: '9425012345',
      email: 'sandeep.k@stu.ac.in',
      department: 'Department of Electronics & Communication',
      designation: 'Professor',
      payLevel: 'Level-14',
      basicPay: 182200,
      dateOfJoining: '2008-01-10',
      permanentAddress: 'B-23, Kasturba Nagar, Bhopal',
      district: 'Bhopal',
      city: 'Bhopal',
      pincode: '462022',
      blockPreference: 'EST-ARY-502',
      quarterPreference: 'Type-V',
      familyDependents: '4',
      specialRequirement: 'None',
      emergencyName: 'Smt. Sunita Kothari',
      emergencyMobile: '9425012340',
      emergencyRelationship: 'Spouse',
      bloodGroup: 'O+',
      medicalCondition: 'Hypertension',
      disabilityDetails: 'None',
      allergies: 'Dust',
      documents: {
        photo: 'sandeep_kothari.jpg',
        salarySlip: 'pay_slip_kothari.pdf',
        joiningLetter: 'joining_kothari_2008.pdf',
        nocCertificate: 'noc_ece_dept.pdf',
      },
      declaration: true,
      signature: 'Sandeep Kothari',
      status: 'Approved',
      adminRemarks:
        'Allocated standard Type-V unit based on premium pay eligibility row.',
      allottedEstate: 'EST-ARY-502',
      allottedFlat: 'Flat-V02',
      feeStatus: 'Paid',
    },
  ];

export const INITIAL_CHECKED_IN_LIST: ResidentialAllocationManagement.CheckedInRecord[] =
  [
    {
      appId: 'APP-STAFF-2026-002',
      staffName: 'Dr. Sandeep Kothari',
      enrollmentNo: 'STU-FAC-782',
      estateCode: 'EST-ARY-502',
      flatNo: 'Flat-V02',
      checkInDate: '2026-06-12',
      luggage: '4',
      remarks: 'Keys to Villa G05 handed over. Handover checklist verified.',
    },
  ];
