import type {
  PublishingCategory,
  SubCategory,
  ContentItem,
  ActivityLogItem,
  ReviewAction,
} from './types';

export const mockCategories: PublishingCategory[] = [
  {
    id: 1,
    title: 'Notices',
    description: 'General notices and declarations for students and staff.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-01-15',
  },
  {
    id: 2,
    title: 'Circulars',
    description: 'Official academic and administrative circulars.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-01-15',
  },
  {
    id: 3,
    title: 'Press Releases',
    description: 'Media and public communication materials.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-02-10',
  },
];

export const mockSubCategories: SubCategory[] = [
  {
    id: 1,
    parentId: 1,
    parentTitle: 'Notices',
    title: 'Admissions Notices',
    description: 'Announcements related to new admissions.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-01-16',
  },
  {
    id: 2,
    parentId: 1,
    parentTitle: 'Notices',
    title: 'Exams Notices',
    description: 'Announcements regarding examination dates & halls.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-01-16',
  },
  {
    id: 3,
    parentId: 2,
    parentTitle: 'Circulars',
    title: 'Academic Circulars',
    description: 'Circulars issued by Dean Academic affairs.',
    status: 'Active',
    createdBy: 'CFS Admin',
    createdDate: '2026-01-20',
  },
];

export const mockContent: ContentItem[] = [
  {
    id: 101,
    title: 'Admission Schedule for Academic Year 2026-27',
    publishingCategoryId: 1,
    publishingCategoryTitle: 'Notices',
    subCategoryId: 1,
    subCategoryTitle: 'Admissions Notices',
    organizationalUnitId: 10,
    organizationalUnitName: 'Admission Branch',
    contentType: 'Notice',
    description:
      '<h2>Admissions Notice</h2><p>This is to notify that the admission portal for the academic session 2026-27 will open on <strong>July 15, 2026</strong>. Candidates are requested to read the prospectus thoroughly.</p>',
    visibility: 'Public',
    startDate: '2026-07-01',
    endDate: '2026-08-31',
    expiryDate: '2026-09-05',
    priority: 'High',
    status: 'Published',
    tags: ['Admission', '2026', 'Registration'],
    attachments: [
      { name: 'admissions_guidelines.pdf', size: '1.2 MB', type: 'PDF' },
    ],
    createdBy: 'Admission Coordinator',
    createdDate: '2026-06-25',
    submittedBy: 'Admission Coordinator',
    submittedDate: '2026-06-25',
  },
  {
    id: 102,
    title: 'End Term Theory Exam Time Table Revised',
    publishingCategoryId: 1,
    publishingCategoryTitle: 'Notices',
    subCategoryId: 2,
    subCategoryTitle: 'Exams Notices',
    organizationalUnitId: 12,
    organizationalUnitName: 'Examination Wing',
    contentType: 'Notice',
    description:
      '<p>The End Term theory examinations scheduled from July 5th are revised. Refer to the attached sheet.</p>',
    visibility: 'Public',
    startDate: '2026-06-30',
    priority: 'High',
    status: 'Pending Review',
    tags: ['Exams', 'Revised', 'Theory'],
    attachments: [
      { name: 'Revised_Schedule_Final.pdf', size: '840 KB', type: 'PDF' },
    ],
    createdBy: 'Exam Superintendent',
    createdDate: '2026-06-29',
    submittedBy: 'Exam Superintendent',
    submittedDate: '2026-06-29',
  },
  {
    id: 103,
    title: 'Revised Hostel Fee Structure Draft',
    publishingCategoryId: 2,
    publishingCategoryTitle: 'Circulars',
    subCategoryId: 3,
    subCategoryTitle: 'Academic Circulars',
    organizationalUnitId: 15,
    organizationalUnitName: 'Hostel Administration Office',
    contentType: 'Circular',
    description:
      '<p>Drafting changes in hostel accommodation charges for incoming batches.</p>',
    visibility: 'Internal',
    startDate: '2026-07-10',
    priority: 'Normal',
    status: 'Draft',
    tags: ['Hostel', 'Fee'],
    attachments: [],
    createdBy: 'Hostel Clerk',
    createdDate: '2026-06-30',
  },
  {
    id: 104,
    title: 'Summer Vacation Declaration 2026',
    publishingCategoryId: 2,
    publishingCategoryTitle: 'Circulars',
    subCategoryId: 3,
    subCategoryTitle: 'Academic Circulars',
    organizationalUnitId: 2,
    organizationalUnitName: 'Vice Chancellor Office',
    contentType: 'Circular',
    description:
      '<p>University summer holidays declared from July 10th to August 1st.</p>',
    visibility: 'Public',
    startDate: '2026-06-01',
    endDate: '2026-08-01',
    priority: 'Normal',
    status: 'Approved',
    tags: ['Vacation', 'Holidays'],
    attachments: [],
    createdBy: 'VC Secretary',
    createdDate: '2026-05-20',
    submittedBy: 'VC Secretary',
    submittedDate: '2026-05-20',
  },
];

export const mockActivityLogs: ActivityLogItem[] = [
  {
    id: 1,
    timestamp: '2026-06-30 10:32:00',
    user: 'John Doe',
    role: 'CFS Admin',
    ou: 'Main Administration',
    action: 'Published Content',
    section: 'Content',
    affectedItem: 'Admission Schedule for Academic Year 2026-27',
    statusChange: 'Approved → Published',
  },
  {
    id: 2,
    timestamp: '2026-06-29 15:45:12',
    user: 'Ravi Kumar',
    role: 'CFS Reviewer',
    ou: 'Computer Science Department',
    action: 'Approved Content',
    section: 'Review',
    affectedItem: 'End Term Theory Exam Time Table Revised',
    statusChange: 'Submitted → Approved',
    remarks: 'Time table looks correct.',
  },
];

export const mockReviewHistory: ReviewAction[] = [
  {
    id: 1,
    contentId: 101,
    action: 'Approve',
    remarks: 'Approved for publishing.',
    performedBy: 'Jane Doe',
    performedRole: 'Reviewer',
    timestamp: '2026-03-02 11:30 AM',
  },
  {
    id: 2,
    contentId: 102,
    action: 'Return',
    remarks: 'Please add more details to the circular.',
    performedBy: 'Jane Doe',
    performedRole: 'Reviewer',
    timestamp: '2026-03-01 10:15 AM',
  },
  {
    id: 3,
    contentId: 105,
    action: 'Reject',
    remarks: 'Duplicate submission.',
    performedBy: 'John Smith',
    performedRole: 'Admin',
    timestamp: '2026-02-28 09:00 AM',
  },
];
