import type {
  CollegeApplicationOption,
  StandingCommitteeDecisionItem,
} from './types';

export const DUMMY_APPLICATIONS: CollegeApplicationOption[] = [
  {
    id: 1,
    name: 'Global Institute of Technology',
    applicationNo: 'APP-74921',
    collegeCode: 'GIT-401',
    collegeType: 'Private Self-Financed',
    district: 'Bhopal',
    coursesApplied: 'B.Tech (CSE, ME, EC), MCA',
    lastMeetingDate: new Date('2026-08-15'),
    committeeMembers: 'Dr. R. K. Sen, Dr. A. Sharma, Prof. K. Singh',
    preliminaryObservation:
      'Classroom infrastructure and laboratory equipment meet norms. Library journals and digital library subscriptions require minor expansion.',
  },
  {
    id: 2,
    name: 'National Science College',
    applicationNo: 'APP-18239',
    collegeCode: 'NSC-102',
    collegeType: 'Government Aided',
    district: 'Indore',
    coursesApplied: 'B.Sc (Physics, Chemistry, Maths), M.Sc (Biotech)',
    lastMeetingDate: new Date('2026-08-10'),
    committeeMembers: 'Dr. R. K. Sen, Prof. L. Verma',
    preliminaryObservation:
      'Land ownership titles verified. Fire safety certification renewed. Required additional faculty recruitments for postgraduate department.',
  },
  {
    id: 3,
    name: 'Sunrise Commerce Academy',
    applicationNo: 'APP-90234',
    collegeCode: 'SCA-209',
    collegeType: 'Private Self-Financed',
    district: 'Jabalpur',
    coursesApplied: 'B.Com (Honours), BBA, MBA',
    lastMeetingDate: new Date('2026-08-20'),
    committeeMembers: 'Dr. A. Sharma, Prof. S. N. Mukherjee, Dr. P. Joshi',
    preliminaryObservation:
      'Auditorium and computer center fully compliant. Faculty cadre ratio meets university statutory norms.',
  },
  {
    id: 4,
    name: 'Pioneer Engineering College',
    applicationNo: 'APP-48231',
    collegeCode: 'PEC-550',
    collegeType: 'Private Self-Financed',
    district: 'Gwalior',
    coursesApplied: 'B.Tech (Civil, EE, AI&DS)',
    lastMeetingDate: new Date('2026-08-22'),
    committeeMembers: 'Prof. K. Singh, Dr. V. Mishra',
    preliminaryObservation:
      'Civil engineering structural lab missing heavy testing equipment. Barrier-free ramps and disabled accessible facilities pending completion.',
  },
  {
    id: 5,
    name: 'Govt Engineering College',
    applicationNo: 'APP-33921',
    collegeCode: 'GEC-007',
    collegeType: 'Government',
    district: 'Ujjain',
    coursesApplied: 'B.Tech (CSE, IT, Electrical), M.Tech',
    lastMeetingDate: new Date('2026-08-25'),
    committeeMembers: 'Dr. R. K. Sen, Dr. A. Sharma, Prof. K. Singh',
    preliminaryObservation:
      'Campus infrastructure state-of-the-art. Hostels and sports complex verified. All norms fulfilled.',
  },
  {
    id: 6,
    name: 'Apex Institute of Pharmacy',
    applicationNo: 'APP-61204',
    collegeCode: 'AIP-331',
    collegeType: 'Private Self-Financed',
    district: 'Sagar',
    coursesApplied: 'B.Pharm (100 seats), D.Pharm (60 seats)',
    lastMeetingDate: new Date('2026-08-28'),
    committeeMembers: 'Dr. M. S. Rathore, Prof. S. K. Bansal',
    preliminaryObservation:
      'Animal house facility pending PCI inspection. Central instrumentation facility requires calibrated HPLC & FTIR.',
  },
];

export const INITIAL_DECISIONS: StandingCommitteeDecisionItem[] = [
  {
    id: 1,
    collegeId: 5,
    collegeName: 'Govt Engineering College',
    applicationNo: 'APP-33921',
    collegeCode: 'GEC-007',
    collegeType: 'Government',
    district: 'Ujjain',
    coursesApplied: 'B.Tech (CSE, IT, Electrical), M.Tech',
    meetingDate: new Date('2026-08-25'),
    committeeMembers: 'Dr. R. K. Sen, Dr. A. Sharma, Prof. K. Singh',
    discussionObservation:
      'Committee thoroughly examined inspection committee report, land ownership records, and faculty credentials. All statutory university affiliation guidelines and AICTE parameters are fully satisfied.',
    finalDecision: 'Approved',
    decisionRemarks:
      'Affiliation approved unconditionally for academic session 2026-27 with sanctioned intake of 300 seats across UG and PG engineering streams.',
    supportingDocumentName: 'Standing_Committee_Minutes_GEC_33921.pdf',
    decisionDate: new Date('2026-08-26'),
    decisionReferenceNo: 'UMS/AFF/SC/2026/089',
    recordedBy: 'Registrar / Standing Committee Convener',
  },
  {
    id: 2,
    collegeId: 2,
    collegeName: 'National Science College',
    applicationNo: 'APP-18239',
    collegeCode: 'NSC-102',
    collegeType: 'Government Aided',
    district: 'Indore',
    coursesApplied: 'B.Sc (Physics, Chemistry, Maths), M.Sc (Biotech)',
    meetingDate: new Date('2026-08-10'),
    committeeMembers: 'Dr. R. K. Sen, Prof. L. Verma',
    discussionObservation:
      'Land titles and building safety certificates are in order. However, 3 full-time faculty positions in Postgraduate Biotechnology department are currently vacant.',
    finalDecision: 'Returned for Compliance',
    decisionRemarks:
      'Affiliation withheld temporarily pending submission of sanctioned appointment letters for regular faculty members in M.Sc Biotechnology.',
    supportingDocumentName: 'Compliance_Notice_NSC_18239.pdf',
    decisionDate: new Date('2026-08-12'),
    decisionReferenceNo: 'UMS/AFF/SC/2026/072',
    recordedBy: 'Registrar / Standing Committee Convener',
  },
  {
    id: 3,
    collegeId: 3,
    collegeName: 'Sunrise Commerce Academy',
    applicationNo: 'APP-90234',
    collegeCode: 'SCA-209',
    collegeType: 'Private Self-Financed',
    district: 'Jabalpur',
    coursesApplied: 'B.Com (Honours), BBA, MBA',
    meetingDate: new Date('2026-08-20'),
    committeeMembers: 'Dr. A. Sharma, Prof. S. N. Mukherjee, Dr. P. Joshi',
    discussionObservation:
      'Committee observed that the institute has provided suitable classroom and administrative infrastructure. UGC guidelines for student-teacher ratio are met.',
    finalDecision: 'Approved',
    decisionRemarks:
      'Provisional affiliation granted for B.Com, BBA, and MBA programmes for 1 academic year subject to periodic surprise checks.',
    supportingDocumentName: 'Approval_Order_SCA_90234.pdf',
    decisionDate: new Date('2026-08-21'),
    decisionReferenceNo: 'UMS/AFF/SC/2026/084',
    recordedBy: 'Registrar / Standing Committee Convener',
  },
  {
    id: 4,
    collegeId: 4,
    collegeName: 'Pioneer Engineering College',
    applicationNo: 'APP-48231',
    collegeCode: 'PEC-550',
    collegeType: 'Private Self-Financed',
    district: 'Gwalior',
    coursesApplied: 'B.Tech (Civil, EE, AI&DS)',
    meetingDate: new Date('2026-08-22'),
    committeeMembers: 'Prof. K. Singh, Dr. V. Mishra',
    discussionObservation:
      'Significant deficiencies observed in laboratory setup and disabled accessibility infrastructure during scrutiny of inspection video and report.',
    finalDecision: 'Deferred',
    decisionRemarks:
      'Decision deferred to next standing committee meeting pending physical re-verification of Civil Engineering and AI laboratory infrastructure.',
    supportingDocumentName: 'Deferment_Order_PEC_48231.pdf',
    decisionDate: new Date('2026-08-23'),
    decisionReferenceNo: 'UMS/AFF/SC/2026/086',
    recordedBy: 'Registrar / Standing Committee Convener',
  },
  {
    id: 5,
    collegeId: 6,
    collegeName: 'Apex Institute of Pharmacy',
    applicationNo: 'APP-61204',
    collegeCode: 'AIP-331',
    collegeType: 'Private Self-Financed',
    district: 'Sagar',
    coursesApplied: 'B.Pharm (100 seats), D.Pharm (60 seats)',
    meetingDate: new Date('2026-08-28'),
    committeeMembers: 'Dr. M. S. Rathore, Prof. S. K. Bansal',
    discussionObservation:
      'Institute failed to produce statutory approvals from Pharmacy Council of India (PCI) and lacked mandatory animal house clearance certificates.',
    finalDecision: 'Rejected',
    decisionRemarks:
      'Application rejected due to non-fulfillment of statutory regulatory body norms and failure to submit basic mandatory documentation within permissible period.',
    supportingDocumentName: 'Rejection_Letter_AIP_61204.pdf',
    decisionDate: new Date('2026-08-29'),
    decisionReferenceNo: 'UMS/AFF/SC/2026/095',
    recordedBy: 'Registrar / Standing Committee Convener',
  },
];
