/**
 * Single source of truth for the *runtime* status & route strings the civil
 * pages actually read from / write to `civil_works` and related records.
 *
 * NOTE: `statusFlow.ts` holds the aspirational canonical enum (DRAFT/APPROVED/…)
 * used only by colour helpers. The pages, however, persist their own concrete
 * strings (`'AaApproved'`, `'Budget Locked'`, …). To stop those literals drifting
 * between the page that WRITES a status and the page that FILTERS on it (which
 * caused works to silently disappear between stages), every page now imports the
 * constants below instead of hardcoding the string. Change a value here and both
 * sides move together.
 */

/** Status values persisted on a `civil_works` record across its lifecycle. */
export const WORK_STATUS = {
  REGISTERED: 'Registered',
  REQUIREMENT_GENERATED: 'Requirement Generated',
  AA_APPROVED: 'AaApproved',
  TS_GRANTED: 'TsGranted',
  BUDGET_LOCKED: 'Budget Locked',
  TENDER_STAGE: 'Tender Stage',
  TENDER_AWARDED: 'Tender Awarded',
  WORK_ORDER_ISSUED: 'Work Order Issued',
  IN_PROGRESS: 'In Progress',
  SUSPENDED: 'Suspended',
  TERMINATED: 'Terminated',
  COMPLETED: 'Completed',
  DLP_ACTIVE: 'DLP Active',
  CLOSED: 'Closed',
} as const;
export type WorkStatus = (typeof WORK_STATUS)[keyof typeof WORK_STATUS];

/**
 * Statuses that make a work eligible for tender floating / agency-work mapping.
 * (TenderOversight's "Registered Work" dropdown filters on exactly these — kept
 * here so it stays in lock-step with the strings AdminApproval / TechnicalSanction
 * / BudgetLock actually write.)
 */
export const TENDER_ELIGIBLE_STATUSES: WorkStatus[] = [
  WORK_STATUS.REGISTERED,
  WORK_STATUS.REQUIREMENT_GENERATED,
  WORK_STATUS.AA_APPROVED,
  WORK_STATUS.TS_GRANTED,
  WORK_STATUS.BUDGET_LOCKED,
  WORK_STATUS.TENDER_STAGE,
];

/** RA-bill maker-checker ladder (finance RABillProcessing → PaymentRelease). */
export const RA_BILL_STATUS = {
  /** Freshly generated by the vendor E-MB page, awaiting EE certification. */
  SUBMITTED: 'Submitted',
  /** EE-certified; this is the first state Finance can audit & clear. */
  EE_APPROVED: 'EE Approved',
  FINANCE_CLEARED: 'Finance Cleared',
  DDO_PASSED: 'DDO Passed',
  PAID: 'Paid',
  REJECTED: 'Rejected',
} as const;
export type RaBillStatus = (typeof RA_BILL_STATUS)[keyof typeof RA_BILL_STATUS];

/** MB-entry verification ladder (vendor E-MB). */
export const MB_STATUS = {
  DRAFT: 'Draft',
  SUBMITTED: 'Submitted',
  VERIFIED_BY_AE: 'Verified by AE',
  APPROVED_BY_EE: 'Approved by EE',
  REJECTED: 'Rejected',
} as const;
export type MbStatus = (typeof MB_STATUS)[keyof typeof MB_STATUS];

/**
 * Execution routing. WorkRegistration normalizes every inbound variant
 * (`'External Agency'`, `'External'`, `'ExternalAgency'`) to `EXTERNAL_AGENCY`
 * on save, so readers must compare against these canonical values only.
 */
export const EXECUTION_ROUTE = {
  INTERNAL: 'Internal',
  EXTERNAL_AGENCY: 'ExternalAgency',
} as const;
export type ExecutionRoute =
  (typeof EXECUTION_ROUTE)[keyof typeof EXECUTION_ROUTE];
