import { useAuth } from 'auth';
import { useMemo } from 'react';
import { hasPermission } from 'shared/utils/permissionCheck';

export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Core Administrative Services',
    slug: 'core-administrative-services',
    category: 'Administrative',
    icon: 'school',
    colorScheme: 'red',
    description: 'Dashboard • Courses • Progress • Finance • Profile',

    children: [
      {
        label: 'User Management',
        slug: 'user-management',
        description:
          'Manage users, roles, role permissions, and user assignments.',
        path: '/home/sub-menu/user-management',
        icon: 'manage_accounts',
        colorScheme: 'blue',
        children: [
          {
            label: 'User',
            description: 'Manage users',
            path: '/master/user-management/users',
            icon: 'person',
            colorScheme: 'blue',
            feature: '@user-management/users',
            action: 'read',
          },
          {
            label: 'Role',
            description: 'Manage roles',
            path: '/master/user-management/roles',
            icon: 'badge',
            colorScheme: 'blue',
            feature: '@user-management/roles',
            action: 'read',
          },
          {
            label: 'Role Permissions',
            description: 'Manage role permissions mapping',
            path: '/master/user-management/role-permissions',
            icon: 'vpn_key',
            colorScheme: 'blue',
            feature: '@user-management/role-permissions',
            action: 'read',
          },
          {
            label: 'User Assignment',
            description: 'Manage user role assignments',
            path: '/master/user-management/user-assignments',
            icon: 'assignment_ind',
            colorScheme: 'blue',
            feature: '@user-management/user-assignment',
            action: 'read',
          },
        ],
      },
      {
        label: 'Location Management',
        slug: 'location',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/location',
        icon: 'edit_location',
        colorScheme: 'blue',
        children: [
          {
            label: 'State',
            description: 'Manage states and union territories',
            path: '/master/location/states',
            icon: 'globe',
            colorScheme: 'blue',
            feature: '@master/State',
            action: 'read',
          },
          {
            label: 'Division',
            description: 'Manage divisions',
            path: '/master/location/divisions',
            icon: 'folder',
            colorScheme: 'blue',
            feature: '@master/Division',
            action: 'read',
          },
          {
            label: 'District',
            description: 'Manage districts',
            path: '/master/location/districts',
            icon: 'map',
            colorScheme: 'blue',
            feature: '@master/District',
            action: 'read',
          },
          {
            label: 'Tehsil',
            description: 'Manage tehsils',
            path: '/master/location/tehsils',
            icon: 'location_city',
            colorScheme: 'blue',
            feature: '@master/Tehsil',
            action: 'read',
          },
          {
            label: 'Block',
            description: 'Manage blocks',
            path: '/master/location/blocks',
            icon: 'grid_view',
            colorScheme: 'blue',
            feature: '@master/Block',
            action: 'read',
          },
        ],
      },
      {
        label: 'Subject Management',
        slug: 'subject',
        description: 'Manage subject , categories, and more.',
        path: '/home/sub-menu/subject',
        icon: 'menu_book',
        colorScheme: 'purple',
        children: [
          {
            label: 'Mode Of Education',
            description: 'Manage Mode of Education',
            path: '/master/subject/programme-mode-of-education',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/ProgrammeModeOfEducation',
            action: 'write',
          },
          {
            label: 'Subject Category',
            description: 'Manage Subject Category',
            path: '/master/subject/subject-category',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/SubjectCategory',
            action: 'write',
          },
          {
            label: 'Subject ',
            description: 'Manage Subject',
            path: '/master/subject/subjects',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/Subjects',
            action: 'write',
          },
          {
            label: 'Programme Specialization Structure',
            description: 'Programme Specialization Structure',
            path: '/master/subject/programme-specialization-structure',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/ProgrammeSpecializationStructure',
            action: 'write',
          },
        ],
      },

      {
        label: 'Faculty Admin',
        slug: 'faculty-management',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/faculty-management',
        icon: 'apartment',
        colorScheme: 'green',
        children: [
          {
            label: 'Office Type',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/faculty-management/office-type',
            icon: 'apartment',
            colorScheme: 'green',
            feature: '@master/Faculties/OfficeType',
            action: 'write',
          },
          {
            label: 'Department',
            description: 'Manage departments',
            path: '/master/faculty-management/department',
            icon: 'domain',
            colorScheme: 'green',
            feature: '@master/Faculties/Department',
            action: 'write',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/faculty-management/designation',
            icon: 'badge',
            colorScheme: 'green',
            feature: '@master/Faculties/Designation',
            action: 'write',
          },
          {
            label: 'Faculty',
            description: 'Manage faculties',
            path: '/master/faculty-management/faculty',
            icon: 'groups',
            colorScheme: 'green',
            feature: '@master/Faculties/Faculty',
            action: 'write',
          },
        ],
      },
      {
        label: 'Human Resource',
        slug: 'hr',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/hr',
        icon: 'apartment',
        colorScheme: 'red',
        children: [
          {
            label: 'Caste',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/hr/caste',
            icon: 'apartment',
            colorScheme: 'red',
            feature: '@master/HR/Caste',
            action: 'read',
          },
          {
            label: 'Post',
            description: 'Manage posts and positions',
            path: '/master/hr/post',
            icon: 'work',
            colorScheme: 'red',
            feature: '@master/HR/Post',
            action: 'read',
          },
          {
            label: 'Religion',
            description: 'Manage religions',
            path: '/master/hr/religion',
            icon: 'domain',
            colorScheme: 'red',
            feature: '@master/HR/Religion',
            action: 'read',
          },
          {
            label: 'Qualification',
            description: 'Manage qualifications',
            path: '/master/hr/qualification',
            icon: 'badge',
            colorScheme: 'red',
            feature: '@master/HR/Qualification',
            action: 'read',
          },
          {
            label: 'Class',
            description: 'Manage classes',
            path: '/master/hr/class',
            icon: 'class',
            colorScheme: 'red',
            feature: '@master/HR/Class',
            action: 'read',
          },
          {
            label: 'Section',
            description: 'Manage sections',
            path: '/master/hr/section',
            icon: 'segment',
            colorScheme: 'red',
            feature: '@master/HR/Section',
            action: 'read',
          },
          {
            label: 'Designation Type',
            description: 'Manage designation types',
            path: '/master/hr/designation-type',
            icon: 'category',
            colorScheme: 'red',
            feature: '@master/HR/DesignationType',
            action: 'read',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/hr/designation',
            icon: 'badge',
            colorScheme: 'red',
            feature: '@master/HR/Designation',
            action: 'read',
          },
        ],
      },
      {
        label: 'College',
        slug: 'college',
        description: 'Manage college types and Categorys.',
        path: '/home/sub-menu/college',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'College Type',
            description: 'Manage college types',
            path: '/master/college/college-type',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/College/CollegeType',
            action: 'write',
          },
          {
            label: 'Category',
            description: 'Manage college categories',
            path: '/master/college/college-category',
            icon: 'school',
            colorScheme: 'red',
            feature: '@master/College/CollegeCategory',
            action: 'write',
          },
        ],
      },
      {
        label: 'Other Masters',
        slug: 'other',
        description: 'Manage masters.',
        path: '/home/sub-menu/other',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'Degree Level',
            description: 'Manage degree levels',
            path: '/master/other/degree-level',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/DegreeLevel',
            action: 'read',
          },
          {
            label: 'Academic Year',
            description: 'Manage academic year records and session details',
            path: '/master/other/academic-year',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/AcademicYear',
            action: 'read',
          },
          {
            label: 'Programme',
            description: 'Manage programmes',
            path: '/master/other/programme',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Programme',
            action: 'read',
          },
          {
            label: 'Specialisation',
            description: 'Manage specialisations',
            path: '/master/other/specialisation',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Specialisation',
            action: 'read',
          },
          {
            label: 'Nationality',
            description: 'Manage nationalities',
            path: '/master/other/nationality',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Nationality',
            action: 'read',
          },
        ],
      },
      {
        label: 'Grant',
        slug: 'grant',
        description: 'Manage grant types and categories.',
        path: '/home/sub-menu/grant',
        icon: 'workspace_premium',
        colorScheme: 'purple',
        children: [
          {
            label: 'Grant Type',
            description: 'Manage grant types',
            path: '/master/grant/grant-type',
            icon: 'workspace_premium',
            colorScheme: 'purple',
            feature: '@master/Grant/GrantType',
            action: 'write',
          },
          {
            label: 'Grant Category',
            description: 'Manage grant categories',
            path: '/master/grant/grant-category',
            icon: 'category',
            colorScheme: 'purple',
            feature: '@master/Grant/GrantCategory',
            action: 'write',
          },
          {
            label: 'Eligibility Application Process',
            description: 'Manage eligibility criteria and application process',
            path: '/master/grant/eligibility-application-process',
            icon: 'assignment_turned_in',
            colorScheme: 'purple',
            feature: '@master/Grant/EligibilityApplicationProcess',
            action: 'write',
          },
        ],
      },
      {
        label: 'Scheme',
        slug: 'scheme',
        description: 'Manage scheme types and categories.',
        path: '/home/sub-menu/scheme',
        icon: 'assignment',
        colorScheme: 'teal',
        children: [
          {
            label: 'Scheme Type',
            description: 'Manage scheme types',
            path: '/master/scheme/scheme-type',
            icon: 'assignment',
            colorScheme: 'teal',
            feature: '@master/Scheme/SchemeType',
            action: 'write',
          },
          {
            label: 'Scheme Category',
            description: 'Manage scheme categories',
            path: '/master/scheme/scheme-category',
            icon: 'category',
            colorScheme: 'teal',
            feature: '@master/Scheme/SchemeCategory',
            action: 'write',
          },
          {
            label: 'Schemes',
            description: 'Manage schemes',
            path: '/master/scheme/schemes',
            icon: 'assignment',
            colorScheme: 'teal',
            feature: '@master/Scheme/Schemes',
            action: 'write',
          },
        ],
      },
      {
        label: 'CMS Management',
        slug: 'cms-management',
        description:
          'Manage website content including courses, departments, faculty, news, downloads, gallery, facilities, stats, and notices.',
        path: '/home/sub-menu/cms-management',
        icon: 'web',
        colorScheme: 'blue',
        children: [
          {
            label: 'Courses',
            description: 'Manage courses and programs',
            path: '/master/cms-management/courses',
            icon: 'school',
            colorScheme: 'blue',
          },
          {
            label: 'Departments',
            description: 'Manage departments',
            path: '/master/cms-management/departments',
            icon: 'domain',
            colorScheme: 'blue',
          },
          {
            label: 'Faculty',
            description: 'Manage faculty members',
            path: '/master/cms-management/faculty',
            icon: 'groups',
            colorScheme: 'blue',
          },
          {
            label: 'News & Events',
            description: 'Manage news and events',
            path: '/master/cms-management/news',
            icon: 'feed',
            colorScheme: 'blue',
          },
          {
            label: 'Downloads',
            description: 'Manage downloadable forms and documents',
            path: '/master/cms-management/downloads',
            icon: 'download',
            colorScheme: 'blue',
          },
          {
            label: 'Gallery',
            description: 'Manage gallery images',
            path: '/master/cms-management/gallery',
            icon: 'image',
            colorScheme: 'blue',
          },
          {
            label: 'Facilities',
            description: 'Manage campus facilities',
            path: '/master/cms-management/facilities',
            icon: 'apartment',
            colorScheme: 'blue',
          },
          {
            label: 'Stats',
            description: 'Manage stats counter values',
            path: '/master/cms-management/stats',
            icon: 'bar_chart',
            colorScheme: 'blue',
          },
          {
            label: 'Notices',
            description: 'Manage scroll notices',
            path: '/master/cms-management/notices',
            icon: 'notifications',
            colorScheme: 'blue',
          },
        ],
      },
    ],
  },
  {
    label: 'Employee\nServices',
    slug: 'employee-services',
    category: 'Employee',
    icon: 'groups',
    colorScheme: 'red',
    description: 'Classes • Grades • Advising • Resources',
    children: [
      {
        label: 'Employee Management System',
        slug: 'employee-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/employee-management',
        icon: 'edit_location',
        colorScheme: 'red',
        navigationStyle: 'sidebar',
        children: [
          {
            label: 'Quick Onboarding',
            slug: 'quick-onboarding',
            description: 'Quick employee onboarding form.',
            path: '/employee-management/quick-onboarding',
            icon: 'person_add',
            colorScheme: 'red',
            feature: '@employee-management/quick-onboarding',
            action: 'write',
          },
          {
            label: 'Full Onboarding',
            slug: 'full-onboarding',
            description: 'Full employee onboarding form.',
            path: '/employee-management/full-onboarding',
            icon: 'person_add',
            colorScheme: 'red',
            feature: '@employee-management/full-onboarding',
            action: 'write',
          },
          {
            label: 'Manage Employee',
            slug: 'manage-employees',
            description: 'Manage and view employees list.',
            path: '/employee-management/manage-employees',
            icon: 'manage_accounts',
            colorScheme: 'blue',
            feature: '@employee-management/manage-employees',
            action: 'read',
          },
          {
            label: 'Settings',
            slug: 'settings',
            description:
              'Manage employee management system settings and masters.',
            path: '/home/sub-menu/settings',
            icon: 'settings',
            colorScheme: 'red',
            children: [
              {
                label: 'Nature of Employment',
                slug: 'nature-of-employment',
                description: 'Manage nature of employment master data.',
                path: '/employee-management/settings/nature-of-employment',
                icon: 'work',
                colorScheme: 'red',
                feature: '@employee/Settings/NatureOfEmployment',
                action: 'read',
              },
              {
                label: 'Organization Unit',
                slug: 'organization-unit',
                description: 'Manage organization unit master data.',
                path: '/employee-management/settings/organization-unit',
                icon: 'account_tree',
                colorScheme: 'red',
                feature: '@employee/Settings/OrganizationUnit',
                action: 'read',
              },
              {
                label: 'Document Option',
                slug: 'document-option',
                description: 'Manage document option master data.',
                path: '/employee-management/settings/document-option',
                icon: 'description',
                colorScheme: 'red',
                feature: '@employee/Settings/DocumentOption',
                action: 'read',
              },
              {
                label: 'Action Options',
                slug: 'action-option',
                description: 'Manage action options master data.',
                path: '/employee-management/settings/action-option',
                icon: 'settings_accessibility',
                colorScheme: 'red',
                feature: '@employee/Settings/ActionOption',
                action: 'read',
              },
              {
                label: 'Subject Specialization',
                slug: 'subject-specialization',
                description: 'Manage subject specialization master data.',
                path: '/employee-management/settings/subject-specialization',
                icon: 'menu_book',
                colorScheme: 'red',
                feature: '@employee/Settings/SubjectSpecialization',
                action: 'read',
              },
              {
                label: 'Action Option Reasons',
                slug: 'action-option-reasons',
                description: 'Manage action option reasons master data.',
                path: '/employee-management/settings/action-option-reason',
                icon: 'assignment_turned_in',
                colorScheme: 'red',
                feature: '@employee/Settings/ActionOptionReason',
                action: 'read',
              },
              {
                label: 'Separation Reasons',
                slug: 'separation-reason-type',
                description: 'Manage separation reasons master data.',
                path: '/master/employee/settings/separation-reason-type',
                icon: 'article',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Travel Purpose',
                slug: 'travel-purpose',
                description: 'Manage travel purpose master data.',
                path: '/employee-management/settings/travel-purpose',
                icon: 'travel_explore',
                colorScheme: 'red',
                feature: '@employee/Settings/TravelPurpose',
                action: 'read',
              },
              {
                label: 'Employee Group',
                slug: 'employee-group',
                description: 'Manage employee group master data.',
                path: '/master/employee/settings/employee-group',
                icon: 'groups',
                colorScheme: 'red',
                feature: '@employee/Settings/EmployeeGroup',
                action: 'read',
              },
            ],
          },
        ],
      },
      {
        label: 'Career Advancement',
        slug: 'career-advancement',
        description: 'Manage career advancement sessions and assessments.',
        path: '/home/sub-menu/career-advancement',
        icon: 'trending_up',
        colorScheme: 'orange',
        children: [
          {
            label: 'Sessions Management',
            slug: 'sessions-management',
            description:
              'Manage assessment sessions for career advancement programs.',
            path: '/career-advancement/sessions-management',
            icon: 'event',
            colorScheme: 'orange',
          },
          {
            label: 'APAR — All Applications',
            slug: 'apar-application',
            description: 'Initiate and manage APAR for all employees',
            path: '/career-advancement/apar-application/all',
            icon: 'list',
            colorScheme: 'orange',
          },
          {
            label: 'APAR — Process Setup',
            slug: 'apar-process',
            description: 'Configure and initiate APAR workflow.',
            path: '/career-advancement/apar-process',
            icon: 'settings',
            colorScheme: 'orange',
          },
          {
            label: 'Employee Self Assessment (APAR)',
            slug: 'employee-self-assessment',
            description:
              'APAR Employee Self Assessment and performance reviews.',
            path: '/career-advancement/employee-self-assessment',
            icon: 'description',
            colorScheme: 'orange',
          },
          {
            label: 'APAR Reporting Appraisal',
            slug: 'apar-reporting',
            description: 'Reporting officer assessment and verified scores.',
            path: '/career-advancement/apar-reporting',
            icon: 'assignment_ind',
            colorScheme: 'orange',
          },
          {
            label: 'APAR Reviewing Review',
            slug: 'apar-reviewing',
            description: 'Reviewing officer final grade authorization.',
            path: '/career-advancement/apar-reviewing',
            icon: 'rate_review',
            colorScheme: 'orange',
          },
          {
            label: 'APAR Track Application',
            slug: 'apar-track',
            description: 'Track APAR workflow timeline.',
            path: '/career-advancement/apar-track',
            icon: 'map',
            colorScheme: 'orange',
          },
          {
            label: 'PBAS/CAS Apply',
            slug: 'performance-appraisal-system',
            description: 'Create PBAS/CAS promotion application.',
            path: '/career-advancement/performance-appraisal-system',
            icon: 'military_tech',
            colorScheme: 'orange',
          },
          {
            label: 'PBAS HOD Approval',
            slug: 'pbas-hod',
            description: 'Department Head review and API score verification.',
            path: '/career-advancement/pbas-hod',
            icon: 'check_circle',
            colorScheme: 'orange',
          },
          {
            label: 'PBAS Dean Approval',
            slug: 'pbas-dean',
            description: 'School Dean review and API score verification.',
            path: '/career-advancement/pbas-dean',
            icon: 'check_circle',
            colorScheme: 'orange',
          },
          {
            label: 'PBAS IQAC Verification',
            slug: 'pbas-iqac',
            description: 'IQAC cell API verification and audit.',
            path: '/career-advancement/pbas-iqac',
            icon: 'verified',
            colorScheme: 'orange',
          },
          {
            label: 'PBAS Dean Academics Review',
            slug: 'pbas-dean-academics',
            description: 'Final screening and scoring approval.',
            path: '/career-advancement/pbas-dean-academics',
            icon: 'assignment_turned_in',
            colorScheme: 'orange',
          },
        ],
      },
    ],
  },
  {
    label: 'Admission\nManagement',
    slug: 'admission-management',
    category: 'Admission',
    icon: 'how_to_reg',
    colorScheme: 'red',
    description:
      'Manage student admissions, applications, and enrollment processes',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Admission Admin Guide',
        slug: 'admission-admin-guide',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Evaluation & Grading',
        slug: 'evaluation-&-grading',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Exam Management',
        slug: 'examination-management',
        description:
          'Manage examination cycles, centers, sessions, results and more.',
        path: '/home/sub-menu/examination-management',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [
          {
            label: 'Dashboard',
            slug: 'examination-dashboard',
            description: 'Examination overview and statistics.',
            path: '/examination-management/dashboard',
            icon: 'dashboard',
            colorScheme: 'red',
            feature: '@examination-management/dashboard',
            action: 'read',
          },
          {
            label: 'Configuration',
            slug: 'examination-configuration',
            description: 'Manage exam types, cycles, time slots, centers.',
            path: '/home/sub-menu/examination-configuration',
            icon: 'settings',
            colorScheme: 'red',
            children: [
              {
                label: 'Exam Types',
                description: 'Manage examination types.',
                path: '/examination-management/setup/exam-types',
                icon: 'assignment',
                colorScheme: 'red',
                feature: '@examination-management/exam-type',
                action: 'read',
              },
              {
                label: 'Exam Cycles',
                description: 'Manage examination cycles.',
                path: '/examination-management/setup/exam-cycles',
                icon: 'date_range',
                colorScheme: 'red',
                feature: '@examination-management/exam-cycle',
                action: 'read',
              },
              {
                label: 'Time Slots',
                description: 'Manage examination time slots.',
                path: '/examination-management/setup/time-slots',
                icon: 'schedule',
                colorScheme: 'red',
                feature: '@examination-management/time-slots',
                action: 'read',
              },
              {
                label: 'Session Templates',
                description: 'Manage examination session templates.',
                path: '/examination-management/setup/session-templates',
                icon: 'description',
                colorScheme: 'red',
                feature: '@examination-management/session-templates',
                action: 'read',
              },
              {
                label: 'Exam Centers',
                description: 'Manage examination centers.',
                path: '/examination-management/setup/centers',
                icon: 'location_on',
                colorScheme: 'red',
                feature: '@examination-management/centers',
                action: 'read',
              },
              {
                label: 'Duty Types',
                description: 'Manage invigilation duty types.',
                path: '/examination-management/setup/duty-types',
                icon: 'badge',
                colorScheme: 'red',
                feature: '@examination-management/duty-types',
                action: 'read',
              },
              {
                label: 'Admit Card Templates',
                description: 'Manage admit card templates.',
                path: '/examination-management/setup/admit-card-templates',
                icon: 'card_membership',
                colorScheme: 'red',
                feature: '@examination-management/admit-card-templates',
                action: 'read',
              },
              {
                label: 'Question Papers',
                description: 'Manage question papers and patterns.',
                path: '/examination-management/question-papers',
                icon: 'description',
                colorScheme: 'red',
                feature: '@examination-management/question-papers',
                action: 'read',
              },
            ],
          },
          {
            label: 'Fees',
            slug: 'examination-fees',
            description: 'Manage examination fees and late fees.',
            path: '/home/sub-menu/examination-fees',
            icon: 'payments',
            colorScheme: 'red',
            children: [
              {
                label: 'Exam Fee',
                description: 'Manage program-wise examination fees.',
                path: '/examination-management/fees/exam-fees',
                icon: 'receipt',
                colorScheme: 'red',
                feature: '@examination-management/fees',
                action: 'read',
              },
              {
                label: 'Late Fee',
                description: 'Manage late fee rules.',
                path: '/examination-management/fees/late-fees',
                icon: 'warning',
                colorScheme: 'red',
                feature: '@examination-management/late-fees',
                action: 'read',
              },
            ],
          },
          {
            label: 'Sessions',
            slug: 'examination-sessions',
            description: 'Manage examination sessions and applications.',
            path: '/home/sub-menu/examination-sessions',
            icon: 'event',
            colorScheme: 'red',
            children: [
              {
                label: 'All Sessions',
                description: 'Manage examination sessions.',
                path: '/examination-management/sessions',
                icon: 'list_alt',
                colorScheme: 'red',
                feature: '@examination-management/sessions',
                action: 'read',
              },
              {
                label: 'Student Applications',
                description: 'View student exam form applications.',
                path: '/examination-management/student-applications',
                icon: 'person',
                colorScheme: 'red',
                feature: '@examination-management/student-applications',
                action: 'read',
              },
              {
                label: 'Supplementary Setup',
                description: 'Setup supplementary examinations.',
                path: '/examination-management/supplementary',
                icon: 'add_task',
                colorScheme: 'red',
                feature: '@examination-management/supplementary-setup',
                action: 'read',
              },
            ],
          },
          {
            label: 'Marks',
            slug: 'examination-marks',
            description: 'Manage marks entry, verification and approval.',
            path: '/home/sub-menu/examination-marks',
            icon: 'edit_note',
            colorScheme: 'red',
            children: [
              {
                label: 'Marks Entry',
                description: 'Enter marks for examination sessions.',
                path: '/examination-management/marks/1',
                icon: 'edit',
                colorScheme: 'red',
                feature: '@examination-management/marks-entry',
                action: 'read',
              },
              {
                label: 'Marks Verification',
                description: 'Verify entered marks.',
                path: '/examination-management/marks/1/verify',
                icon: 'fact_check',
                colorScheme: 'red',
                feature: '@examination-management/marks-verification',
                action: 'read',
              },
              {
                label: 'Marks Approval',
                description: 'Approve verified marks.',
                path: '/examination-management/marks/1/approve',
                icon: 'approval',
                colorScheme: 'red',
                feature: '@examination-management/marks-approval',
                action: 'read',
              },
            ],
          },
          {
            label: 'Results & Processing',
            slug: 'examination-results',
            description:
              'Manage results, moderation, revaluation and grade cards.',
            path: '/home/sub-menu/examination-results',
            icon: 'grading',
            colorScheme: 'red',
            children: [
              {
                label: 'Result Processing',
                description: 'Process results for examination sessions.',
                path: '/examination-management/results/1',
                icon: 'calculate',
                colorScheme: 'red',
                feature: '@examination-management/result-processing',
                action: 'read',
              },
              {
                label: 'Moderation',
                description: 'Manage grace marks and moderation.',
                path: '/examination-management/results/moderation',
                icon: 'auto_fix_high',
                colorScheme: 'red',
                feature: '@examination-management/moderation',
                action: 'read',
              },
              {
                label: 'Result Publication',
                description: 'Publish finalized results.',
                path: '/examination-management/results/publication',
                icon: 'publish',
                colorScheme: 'red',
                feature: '@examination-management/result-publication',
                action: 'read',
              },
              {
                label: 'Grade Cards',
                description: 'Generate grade cards / transcripts.',
                path: '/examination-management/results/grade-cards',
                icon: 'assignment_ind',
                colorScheme: 'red',
                feature: '@examination-management/grade-cards',
                action: 'read',
              },
              {
                label: 'Revaluation',
                description: 'Manage revaluation applications.',
                path: '/examination-management/revaluation',
                icon: 'refresh',
                colorScheme: 'red',
                feature: '@examination-management/revaluation',
                action: 'read',
              },
              {
                label: 'Revaluation Evaluation',
                description: 'Evaluate revaluation requests.',
                path: '/examination-management/revaluation/evaluation',
                icon: 'fact_check',
                colorScheme: 'red',
                feature: '@examination-management/revaluation-evaluation',
                action: 'read',
              },
              {
                label: 'Duplicate Marksheet',
                description: 'Manage duplicate marksheet requests.',
                path: '/examination-management/duplicate-marksheet',
                icon: 'content_copy',
                colorScheme: 'red',
                feature: '@examination-management/duplicate-marksheet',
                action: 'read',
              },
            ],
          },
          {
            label: 'Evaluators',
            slug: 'examination-evaluators',
            description: 'Manage evaluators and sheet distribution.',
            path: '/home/sub-menu/examination-evaluators',
            icon: 'group',
            colorScheme: 'red',
            children: [
              {
                label: 'Evaluator List',
                description: 'Manage answer sheet evaluators.',
                path: '/examination-management/evaluator',
                icon: 'people',
                colorScheme: 'red',
                feature: '@examination-management/evaluator',
                action: 'read',
              },
              {
                label: 'Sheet Distribution',
                description: 'Distribute answer sheets to evaluators.',
                path: '/examination-management/evaluator/sheet-distribution',
                icon: 'assignment',
                colorScheme: 'red',
                feature: '@examination-management/evaluator-sheet-distribution',
                action: 'read',
              },
            ],
          },
          {
            label: 'Reports & Analytics',
            slug: 'examination-reports',
            description: 'View examination reports and dashboards.',
            path: '/home/sub-menu/examination-reports',
            icon: 'analytics',
            colorScheme: 'red',
            children: [
              {
                label: 'Reports Dashboard',
                description: 'Analytical reports for examinations.',
                path: '/examination-management/reports',
                icon: 'insert_chart',
                colorScheme: 'red',
                feature: '@examination-management/reports',
                action: 'read',
              },
            ],
          },
          {
            label: 'Student Portal',
            slug: 'examination-student',
            description: 'Student self-service portal for examinations.',
            path: '/home/sub-menu/examination-student',
            icon: 'school',
            colorScheme: 'red',
            children: [
              {
                label: 'Student Dashboard',
                description: 'Student examination overview.',
                path: '/examination-management/student',
                icon: 'dashboard',
                colorScheme: 'red',
                feature: '@examination-management/student-dashboard',
                action: 'read',
              },
              {
                label: 'Exam Form',
                description: 'Fill and submit exam form.',
                path: '/examination-management/student/exam-form',
                icon: 'assignment_ind',
                colorScheme: 'red',
                feature: '@examination-management/student-exam-form',
                action: 'read',
              },
              {
                label: 'Timetable',
                description: 'View personal exam timetable.',
                path: '/examination-management/student/timetable',
                icon: 'calendar_month',
                colorScheme: 'red',
                feature: '@examination-management/student-timetable',
                action: 'read',
              },
              {
                label: 'Admit Card',
                description: 'Download admit card.',
                path: '/examination-management/student/admit-card',
                icon: 'card_membership',
                colorScheme: 'red',
                feature: '@examination-management/student-admit-card',
                action: 'read',
              },
              {
                label: 'Seating Plan',
                description: 'View exam hall seating plan.',
                path: '/examination-management/student/seating-plan',
                icon: 'map',
                colorScheme: 'red',
                feature: '@examination-management/student-seating-plan',
                action: 'read',
              },
              {
                label: 'Results',
                description: 'View examination results.',
                path: '/examination-management/student/results',
                icon: 'assessment',
                colorScheme: 'red',
                feature: '@examination-management/student-results',
                action: 'read',
              },
              {
                label: 'Grade Cards',
                description: 'Download grade cards.',
                path: '/examination-management/student/grade-cards',
                icon: 'assignment',
                colorScheme: 'red',
                feature: '@examination-management/student-grade-cards',
                action: 'read',
              },
              {
                label: 'Revaluation',
                description: 'Apply for revaluation.',
                path: '/examination-management/student/revaluation',
                icon: 'refresh',
                colorScheme: 'red',
                feature: '@examination-management/student-revaluation',
                action: 'read',
              },
              {
                label: 'Duplicate Marksheet',
                description: 'Request duplicate marksheet.',
                path: '/examination-management/student/duplicate-marksheet',
                icon: 'content_copy',
                colorScheme: 'red',
                feature: '@examination-management/student-duplicate-marksheet',
                action: 'read',
              },
              {
                label: 'Track Applications',
                description: 'Track exam form and revaluation status.',
                path: '/examination-management/student/track-applications',
                icon: 'track_changes',
                colorScheme: 'red',
                feature: '@examination-management/student-track-applications',
                action: 'read',
              },
            ],
          },
        ],
      },
      {
        label: 'Certificate Management',
        slug: 'certificate-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },

      {
        label: 'Student Additional Information',
        slug: 'student-additional-information',
        description: 'Manage student additional details.',
        path: '/sis/student-additional-information',
        icon: 'person_add',
        colorScheme: 'red',
        feature: '@sis/StudentAdditionalInformation',
        action: 'read',
      },
      {
        label: 'Student Application Form',
        slug: 'student-application-form',
        description: 'Create and submit student applications.',
        path: '/sis/student-application-form',
        icon: 'assignment',
        colorScheme: 'red',
        feature: '@sis/StudentApplicationForm',
        action: 'read',
      },
      {
        label: 'Fee Payment Approval (Temp)',
        slug: 'student-fee-approval',
        description: 'Approve student application fee payments.',
        path: '/sis/student-fee-approval',
        icon: 'check_circle',
        colorScheme: 'red',
        feature: '@sis/StudentFeeApproval',
        action: 'read',
      },
    ],
  },
  {
    label: 'Accounts And Finance',
    slug: 'accounts-and-finance',
    category: 'Finance',
    icon: 'menu_book',
    colorScheme: 'red',
    description: 'Streamline curriculum management and approvals',
    children: [
      {
        label: 'Financial Supply Chain Management',
        slug: 'financial-supply-chain-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  {
    label: 'Hostel Management',
    slug: 'hostel-management',
    category: 'Hostel',
    description:
      'End-to-end hostel intake, room allotment, ledger invoicing and student check-in.',
    path: '/home/sub-menu/hostel-management',
    icon: 'domain',
    colorScheme: 'blue',
    children: [
      {
        label: 'Hostel Registry',
        slug: 'hostel-registry',
        description: 'Register and manage hostel buildings.',
        path: '/hostel-management/hostel-registry',
        icon: 'apartment',
        colorScheme: 'blue',
      },
      {
        label: 'Room Configuration',
        slug: 'room-configuration',
        description: 'Define wings, floors, and bed counts.',
        path: '/hostel-management/room-configuration',
        icon: 'grid_view',
        colorScheme: 'blue',
      },
      {
        label: 'Student Apply',
        slug: 'student-apply',
        description: 'Submit hostel intake application.',
        path: '/hostel-management/student-apply',
        icon: 'assignment',
        colorScheme: 'blue',
      },
      {
        label: 'Admin Desk',
        slug: 'admin-desk',
        description: 'Review and approve student applications.',
        path: '/hostel-management/admin-desk',
        icon: 'assignment_turned_in',
        colorScheme: 'blue',
      },
      {
        label: 'Room Allotment',
        slug: 'room-allotment',
        description: 'Map approved students to beds.',
        path: '/hostel-management/room-allotment',
        icon: 'manage_accounts',
        colorScheme: 'blue',
      },
      {
        label: 'Ledger Invoice',
        slug: 'ledger-invoice',
        description: 'Generate and confirm fee payments.',
        path: '/hostel-management/ledger-invoice',
        icon: 'description',
        colorScheme: 'blue',
      },
      {
        label: 'Joining / Check-In',
        slug: 'check-in',
        description: 'Physical key handoff and boarding registration.',
        path: '/hostel-management/check-in',
        icon: 'badge',
        colorScheme: 'blue',
      },
    ],
  },
  {
    label: 'Governance',
    slug: 'governance',
    category: 'Governance',
    icon: 'bolt',
    colorScheme: 'red',
    description: 'Track student competencies and skill development',
    children: [
      {
        label: 'Affiliation Management',
        slug: 'affiliation-Management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Communication System',
        slug: 'core-communication-system',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Grievance Management',
        slug: 'grievance-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Residential Allocation',
        slug: 'residential-allocation-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  {
    label: 'Affiliation Management System',
    slug: 'affiliation-management-system',
    category: 'Affiliation Management System',
    icon: 'groups',
    colorScheme: 'red',
    description: 'Classes • Grades • Advising • Resources',
    children: [
      {
        label: 'College Registration',
        slug: 'college-registration',
        description: 'Manage college registration processes.',
        path: '/affiliation-management-system/college-registration',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [
          {
            label: 'college Registration',
            slug: 'college-registration',
            description: 'Manage college registration processes.',
            path: '/affiliation-management-system/college-registration',
            icon: 'assignment',
            colorScheme: 'orange',
            // feature: '@affiliation/CollegeRegistration',
            // action: 'read',
          },
        ],
      },
      {
        label: 'Draft College Registration',
        slug: 'draft-registration-request',
        description: 'Manage draft college registration processes.',
        path: '/affiliation-management-system/draft-registration-request',
        icon: 'assignment',
        colorScheme: 'orange',
      },

      {
        label: 'College Registration Approvals',
        slug: 'registration-approval',
        description: 'Manage college registration Approvals.',
        path: '/affiliation-management-system/registration-approval',
        icon: 'edit_location',
        colorScheme: 'green',
        // feature: '@collegeaffiliation/collegeregistrationapproval',
        // action: 'read',
      },
      {
        label: 'College Profile Details',
        slug: 'profile-details',
        description: 'Manage college profile details.',
        path: '/affiliation-management-system/profile-details',
        icon: 'corporate_fare',
        colorScheme: 'purple',
      },
      {
        label: 'Inspection Details',
        slug: 'inspection-report',
        description: 'Fill the detailed inspection report.',
        path: '/affiliation-management-system/inspection-report',
        icon: 'assignment_turned_in',
        colorScheme: 'blue',
      },
      {
        label: 'Approval Status Report',
        slug: 'approval-status-report',
        description: 'View approval status of affiliations.',
        path: '/affiliation-management-system/approval-status-report',
        icon: 'check_circle',
        colorScheme: 'green',
      },
      {
        label: 'Inspection Status Report',
        slug: 'inspection-status-report',
        description: 'View the history of inspections.',
        path: '/affiliation-management-system/inspection-status-report',
        icon: 'policy',
        colorScheme: 'blue',
      },
      {
        label: 'Affiliation Settings',
        slug: 'affiliation-settings',
        description: 'Manage affiliation settings',
        path: '/home/sub-menu/affiliation-settings',
        icon: 'settings',
        colorScheme: 'red',
        children: [
          {
            label: 'Available Facility',
            slug: 'available-facility',
            description: 'Manage available facility',
            path: '/affiliation-management-system/affiliation-settings/available-facility',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/College/AvailableFacility',
            action: 'read',
          },
          {
            label: 'Establishment Year',
            slug: 'establishment-year',
            description: 'Manage Establishment Year',
            path: '/affiliation-management-system/affiliation-settings/establishment-year',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/EstablishmentYear',
            action: 'read',
          },
          {
            label: 'Programme Fee',
            description: 'Manage programme fees',
            path: '/affiliation-management-system/affiliation-settings/programme-fee',
            icon: 'money',
            colorScheme: 'blue',
            feature: '@master/Affiliation/ProgrammeFee',
            action: 'read',
          },
        ],
      },
    ],
  },
  {
    label: 'Academics',
    slug: 'academics',
    category: 'Academics',
    icon: 'school',
    colorScheme: 'green',
    description: 'Courses • Enrollment • Sessions • Evaluation • Grading',
    path: '/academics',
    children: [
      {
        label: 'Academic Management',
        slug: 'academic-management',
        description:
          'Manage courses, student enrollment, academic sessions, evaluation components, and grading scales.',
        path: '/academics',
        icon: 'school',
        colorScheme: 'green',
      },
    ],
  },
  {
    label: 'Programme\nManagement',
    slug: 'programme-management',
    category: 'Academics',
    icon: 'menu_book',
    colorScheme: 'blue',
    description: 'Programmes • Disciplines • UGC Degrees • Exam Schemes',
    children: [
      {
        label: 'Programme Management System',
        slug: 'programme-management-system',
        description:
          'Manage academic programmes, disciplines, UGC degrees, admission quotas, enrolment types, and exam schemes.',
        path: '/programme-management',
        icon: 'menu_book',
        colorScheme: 'blue',
      },
    ],
  },
  // {
  //   label: 'Career\nGateway',
  //   slug: 'career-gateway',
  //   category: 'HR',
  //   icon: 'work',
  //   colorScheme: 'red',
  //   description: 'Career services and job placement resources',
  // },
  // {
  //   label: 'ICON – Research Compliance',
  //   slug: 'icon-research-compliance',
  //   category: 'Academics',
  //   icon: 'science',
  //   colorScheme: 'orange',
  //   description: 'Manage research compliance and ethics approvals',
  // },
  // {
  //   label: 'Disability\nCenter',
  //   slug: 'disability-center',
  //   category: 'HR',
  //   icon: 'accessible',
  //   colorScheme: 'pink',
  //   description: 'Support services for students with disabilities',
  // },
  // {
  //   label: 'Student ID & Campus Allowance',
  //   slug: 'student-id-campus-allowance',
  //   category: 'Finance',
  //   icon: 'credit_card',
  //   colorScheme: 'blue',
  //   description: 'Manage student IDs and campus financial allowances',
  // },
  // {
  //   label: 'University Queue – Virtual Queuing',
  //   slug: 'university-queue-virtual-queuing',
  //   category: 'Operation',
  //   icon: 'desktop_windows',
  //   colorScheme: 'purple',
  //   description: 'Virtual queuing system for campus services',
  // },
  // {
  //   label: 'FIXIT — Facility Management',
  //   slug: 'fixit-facility-management',
  //   category: 'Operation',
  //   icon: 'build',
  //   colorScheme: 'teal',
  //   description: 'Report and manage facility maintenance issues',
  // },
  // {
  //   label: 'Scholarship&\nGrants',
  //   slug: 'scholarship-grants',
  //   category: 'Finance',
  //   icon: 'workspace_premium',
  //   colorScheme: 'indigo',
  //   description: 'Manage scholarship and grant applications',
  // },
  {
    label: 'Learning Management System',
    slug: 'lms',
    category: 'Academics',
    icon: 'school',
    colorScheme: 'blue',
    description: 'Manage courses, modules, assessments, and student progress.',
    children: [
      {
        label: 'Dashboard',
        description: 'Admin overview dashboard',
        path: '/lms/dashboard',
        icon: 'dashboard',
        colorScheme: 'blue',
      },
      {
        label: 'Masters',
        slug: 'lms-masters',
        description: 'Manage LMS masters',
        path: '/home/sub-menu/lms-masters',
        icon: 'settings',
        colorScheme: 'blue',
        children: [
          {
            label: 'Course Master',
            description: 'Manage courses',
            path: '/lms/masters/course',
            icon: 'school',
            colorScheme: 'blue',
          },
          {
            label: 'Course Category Master',
            description: 'Manage course categories',
            path: '/lms/masters/course-category',
            icon: 'category',
            colorScheme: 'blue',
          },
          {
            label: 'Content Type Master',
            description: 'Manage content types',
            path: '/lms/masters/content-type',
            icon: 'description',
            colorScheme: 'blue',
          },
          {
            label: 'Assessment Type Master',
            description: 'Manage assessment types',
            path: '/lms/masters/assessment-type',
            icon: 'assignment',
            colorScheme: 'blue',
          },
          {
            label: 'Certification Master',
            description: 'Manage certifications',
            path: '/lms/masters/certification',
            icon: 'workspace_premium',
            colorScheme: 'blue',
          },
        ],
      },
      {
        label: 'Configuration',
        slug: 'lms-configuration',
        description: 'Manage course configurations',
        path: '/home/sub-menu/lms-configuration',
        icon: 'settings_suggest',
        colorScheme: 'orange',
        children: [
          {
            label: 'Course Structure Mapping',
            description: 'Map Course to Modules and Topics',
            path: '/lms/configuration/course-structure',
            icon: 'account_tree',
            colorScheme: 'orange',
          },
          {
            label: 'Faculty Mapping',
            description: 'Assign Faculty to Courses',
            path: '/lms/configuration/faculty-mapping',
            icon: 'people',
            colorScheme: 'orange',
          },
          {
            label: 'Student Enrollment',
            description: 'Enroll Students into Courses',
            path: '/lms/configuration/student-enrollment',
            icon: 'group_add',
            colorScheme: 'orange',
          },
        ],
      },
      {
        label: 'Content Management',
        slug: 'lms-content-management',
        description: 'Manage course content',
        path: '/home/sub-menu/lms-content-management',
        icon: 'source',
        colorScheme: 'green',
        children: [
          {
            label: 'Module Management',
            description: 'Manage modules',
            path: '/lms/content-management/module',
            icon: 'view_module',
            colorScheme: 'green',
          },
          {
            label: 'Content Upload',
            description: 'Upload learning content',
            path: '/lms/content-management/content-upload',
            icon: 'cloud_upload',
            colorScheme: 'green',
          },
        ],
      },
      {
        label: 'Assessment Management',
        slug: 'lms-assessment',
        description: 'Manage quizzes and assignments',
        path: '/home/sub-menu/lms-assessment',
        icon: 'quiz',
        colorScheme: 'purple',
        children: [
          {
            label: 'Quiz Management',
            description: 'Manage quizzes',
            path: '/lms/assessment/quiz-management',
            icon: 'help_outline',
            colorScheme: 'purple',
          },
          {
            label: 'Assignment Submissions Review',
            description: 'Review submitted assignments',
            path: '/lms/assessment/assignment-submissions',
            icon: 'grading',
            colorScheme: 'purple',
          },
        ],
      },
      {
        label: 'Progress Tracking',
        slug: 'lms-progress-tracking',
        description: 'Track student progress',
        path: '/home/sub-menu/lms-progress-tracking',
        icon: 'trending_up',
        colorScheme: 'teal',
        children: [
          {
            label: 'Course Progress Report',
            description: 'View student progress percentages',
            path: '/lms/progress-tracking/course-progress',
            icon: 'bar_chart',
            colorScheme: 'teal',
          },
        ],
      },
      {
        label: 'Certification',
        slug: 'lms-certification',
        description: 'Manage certificates',
        path: '/home/sub-menu/lms-certification',
        icon: 'workspace_premium',
        colorScheme: 'indigo',
        children: [
          {
            label: 'Certificate Generation',
            description: 'Generate certificates for students',
            path: '/lms/certification/generate',
            icon: 'card_membership',
            colorScheme: 'indigo',
          },
          {
            label: 'Certificate View',
            description: 'View generated certificates',
            path: '/lms/certification/view',
            icon: 'preview',
            colorScheme: 'indigo',
          },
        ],
      },
    ],
  },
  {
    label: 'Fee Management',
    slug: 'fee-management',
    category: 'Finance',
    icon: 'payments',
    colorScheme: 'green',
    description: 'Configuration • Structure • Demand • Payments • Auditing',
    path: '/master/admission-fee/dashboard',
    children: [
      {
        label: 'Dashboard',
        description: 'Fee analytics and KPI dashboard',
        path: '/master/admission-fee/dashboard',
        icon: 'bar_chart',
        colorScheme: 'green',
      },
      {
        label: 'Fee Configuration',
        slug: 'fee-configuration',
        description:
          'Configure academic sessions, college mappings, course details, semester mappings, and fee heads.',
        path: '/master/admission-fee/configuration',
        icon: 'settings',
        colorScheme: 'green',
        children: [
          {
            label: 'Fee Dashboard',
            description: 'Go to Fee Dashboard',
            path: '/master/admission-fee/dashboard',
            icon: 'bar_chart',
            colorScheme: 'green',
          },
          {
            label: 'Academic Session Master',
            description: 'Manage academic sessions',
            path: '/master/admission-fee/academic-session',
            icon: 'calendar_today',
            colorScheme: 'green',
          },
          {
            label: 'College Mapping Master',
            description: 'Map colleges with courses',
            path: '/master/admission-fee/college-mapping',
            icon: 'apartment',
            colorScheme: 'green',
          },
          {
            label: 'Course Master',
            description: 'Manage courses',
            path: '/master/admission-fee/course',
            icon: 'school',
            colorScheme: 'green',
          },
          {
            label: 'Program Master',
            description: 'Manage academic programs',
            path: '/master/admission-fee/program',
            icon: 'assignment',
            colorScheme: 'green',
          },
          {
            label: 'Semester Master',
            description: 'Configure semesters',
            path: '/master/admission-fee/semester',
            icon: 'list_alt',
            colorScheme: 'green',
          },
          {
            label: 'Fee Head Master',
            description: 'Configure fee heads and frequencies',
            path: '/master/admission-fee/fee-head',
            icon: 'account_balance_wallet',
            colorScheme: 'green',
          },
        ],
      },
      {
        label: 'Fee Transactions',
        slug: 'fee-transactions',
        description:
          'Process structures, generate student demands, manage scholarship adjustments, payments, and reconciliations.',
        path: '/master/admission-fee/transactions',
        icon: 'receipt',
        colorScheme: 'green',
        children: [
          {
            label: 'Fee Dashboard',
            description: 'Go to Fee Dashboard',
            path: '/master/admission-fee/dashboard',
            icon: 'bar_chart',
            colorScheme: 'green',
          },
          {
            label: 'Fee Structure',
            description: 'Create, approve and view fee structures',
            path: '/master/admission-fee/fee-structure',
            icon: 'table_view',
            colorScheme: 'green',
          },
          {
            label: 'Fee Demand Generation',
            description: 'Generate and approve student fee demands',
            path: '/master/admission-fee/demand-generation',
            icon: 'receipt',
            colorScheme: 'green',
          },
          {
            label: 'Scholarship Management',
            description: 'Register and approve student scholarships',
            path: '/master/admission-fee/scholarship',
            icon: 'workspace_premium',
            colorScheme: 'green',
          },
          {
            label: 'Fee Concession',
            description: 'Apply and verify fee concessions',
            path: '/master/admission-fee/concession',
            icon: 'local_offer',
            colorScheme: 'green',
          },
          {
            label: 'Fee Collection',
            description: 'Record manual collections and process payments',
            path: '/master/admission-fee/collection',
            icon: 'point_of_sale',
            colorScheme: 'green',
          },
          {
            label: 'Receipt Register',
            description: 'View and download payment receipts',
            path: '/master/admission-fee/receipts',
            icon: 'print',
            colorScheme: 'green',
          },
          {
            label: 'Failed Transactions',
            description: 'Manage failed payments and reconciliation queue',
            path: '/master/admission-fee/failed-transactions',
            icon: 'error',
            colorScheme: 'green',
          },
          {
            label: 'Refund Management',
            description: 'Process and approve fee refunds',
            path: '/master/admission-fee/refunds',
            icon: 'undo',
            colorScheme: 'green',
          },
          {
            label: 'Bank Reconciliation',
            description: 'Verify statements and match collections',
            path: '/master/admission-fee/bank-reconciliation',
            icon: 'account_balance',
            colorScheme: 'green',
          },
        ],
      },
    ],
  },
  {
    label: 'Feedback\nManagement',
    slug: 'feedback',
    category: 'Feedback',
    icon: 'feedback',
    colorScheme: 'orange',
    description: 'Student and Employee Feedback Systems',
    children: [
      {
        label: 'Student Feedback Management',
        slug: 'student-feedback-management',
        description: 'Portal selector (role selection)',
        icon: 'feedback',
        colorScheme: 'orange',
        path: '/student-feedback-management',
        children: [
          {
            label: 'Admin Portal',
            slug: 'admin',
            description:
              'Admin portal (Dashboard/Templates/Question Bank tiles)',
            path: '/student-feedback-management/admin',
            icon: 'admin_panel_settings',
            colorScheme: 'orange',
            children: [
              {
                label: 'Dashboard',
                slug: 'dashboard',
                description: 'Stats dashboard with charts',
                path: '/student-feedback-management/admin/dashboard',
                icon: 'dashboard',
                colorScheme: 'orange',
              },
              {
                label: 'Templates',
                slug: 'templates',
                description: 'Template CRUD with all actions',
                path: '/student-feedback-management/admin/templates',
                icon: 'description',
                colorScheme: 'orange',
              },
              {
                label: 'Question Bank',
                slug: 'question-bank',
                description: 'Question CRUD with answer types',
                path: '/student-feedback-management/admin/question-bank',
                icon: 'help_outline',
                colorScheme: 'orange',
              },
            ],
          },
        ],
      },
    ],
  },
];

export function useMenu() {
  const { authenticated, permissions } = useAuth();

  return useMemo(() => {
    if (!authenticated) return [];

    const filterMenu = (items: Menu.MenuItem[]): Menu.MenuItem[] => {
      return items
        .filter(item => {
          if (item.feature && item.action) {
            return hasPermission(permissions, item.feature, item.action);
          }
          return true;
        })
        .map(item => {
          if (item.children) {
            return { ...item, children: filterMenu(item.children) };
          }
          return item;
        })
        .filter(item => {
          if (item.children) {
            // Parent menus/folders must have at least one visible child to be shown.
            // If all of their children are filtered out, the parent menu is also hidden.
            return item.children.length > 0;
          }
          return true;
        });
    };

    return filterMenu(menuConfig);
  }, [authenticated, permissions]);
}
