import { useAuth } from 'auth';
import { useMemo } from 'react';
import { hasPermission } from 'shared/utils/permissionCheck';

export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Core Administrative Services',
    slug: 'core-administrative-services',
    category: 'Administrative',
    icon: 'school',
    colorScheme: 'red',
    description: 'Dashboard • Courses • Progress • Finance • Profile',

    children: [
      {
        label: 'User Management',
        slug: 'user-management',
        description:
          'Manage users, roles, role permissions, and user assignments.',
        path: '/home/sub-menu/user-management',
        icon: 'manage_accounts',
        colorScheme: 'blue',
        children: [
          {
            label: 'User',
            description: 'Manage users',
            path: '/master/user-management/users',
            icon: 'person',
            colorScheme: 'blue',
            feature: '@user-management/users',
            action: 'read',
          },
          {
            label: 'Role',
            description: 'Manage roles',
            path: '/master/user-management/roles',
            icon: 'badge',
            colorScheme: 'blue',
            feature: '@user-management/roles',
            action: 'read',
          },
          {
            label: 'Role Permissions',
            description: 'Manage role permissions mapping',
            path: '/master/user-management/role-permissions',
            icon: 'vpn_key',
            colorScheme: 'blue',
            feature: '@user-management/role-permissions',
            action: 'read',
          },
          {
            label: 'User Assignment',
            description: 'Manage user role assignments',
            path: '/master/user-management/user-assignments',
            icon: 'assignment_ind',
            colorScheme: 'blue',
            feature: '@user-management/user-assignment',
            action: 'read',
          },
        ],
      },
      {
        label: 'Location Management',
        slug: 'location',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/location',
        icon: 'edit_location',
        colorScheme: 'blue',
        children: [
          {
            label: 'State',
            description: 'Manage states and union territories',
            path: '/master/location/states',
            icon: 'globe',
            colorScheme: 'blue',
            feature: '@master/State',
            action: 'read',
          },
          {
            label: 'Division',
            description: 'Manage divisions',
            path: '/master/location/divisions',
            icon: 'folder',
            colorScheme: 'blue',
            feature: '@master/Division',
            action: 'read',
          },
          {
            label: 'District',
            description: 'Manage districts',
            path: '/master/location/districts',
            icon: 'map',
            colorScheme: 'blue',
            feature: '@master/District',
            action: 'read',
          },
          {
            label: 'Tehsil',
            description: 'Manage tehsils',
            path: '/master/location/tehsils',
            icon: 'location_city',
            colorScheme: 'blue',
            feature: '@master/Tehsil',
            action: 'read',
          },
          {
            label: 'Block',
            description: 'Manage blocks',
            path: '/master/location/blocks',
            icon: 'grid_view',
            colorScheme: 'blue',
            feature: '@master/Block',
            action: 'read',
          },
        ],
      },
      {
        label: 'Subject Management',
        slug: 'subject',
        description: 'Manage subject , categories, and more.',
        path: '/home/sub-menu/subject',
        icon: 'menu_book',
        colorScheme: 'purple',
        children: [
          {
            label: 'Mode Of Education',
            description: 'Manage Mode of Education',
            path: '/master/subject/programme-mode-of-education',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/ProgrammeModeOfEducation',
            action: 'write',
          },
          {
            label: 'Subject Category',
            description: 'Manage Subject Category',
            path: '/master/subject/subject-category',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/SubjectCategory',
            action: 'write',
          },
          {
            label: 'Subject ',
            description: 'Manage Subject',
            path: '/master/subject/subjects',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/Subjects',
            action: 'write',
          },
          {
            label: 'Programme Specialization Structure',
            description: 'Programme Specialization Structure',
            path: '/master/subject/programme-specialization-structure',
            icon: 'apartment',
            colorScheme: 'purple',
            feature: '@master/Subject/ProgrammeSpecializationStructure',
            action: 'write',
          },
        ],
      },

      {
        label: 'Faculty Admin',
        slug: 'faculty-management',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/faculty-management',
        icon: 'apartment',
        colorScheme: 'green',
        children: [
          {
            label: 'Office Type',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/faculty-management/office-type',
            icon: 'apartment',
            colorScheme: 'green',
            feature: '@master/Faculties/OfficeType',
            action: 'write',
          },
          {
            label: 'Department',
            description: 'Manage departments',
            path: '/master/faculty-management/department',
            icon: 'domain',
            colorScheme: 'green',
            feature: '@master/Faculties/Department',
            action: 'write',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/faculty-management/designation',
            icon: 'badge',
            colorScheme: 'green',
            feature: '@master/Faculties/Designation',
            action: 'write',
          },
          {
            label: 'Faculty',
            description: 'Manage faculties',
            path: '/master/faculty-management/faculty',
            icon: 'groups',
            colorScheme: 'green',
            feature: '@master/Faculties/Faculty',
            action: 'write',
          },
        ],
      },
      {
        label: 'Human Resource',
        slug: 'hr',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/hr',
        icon: 'apartment',
        colorScheme: 'red',
        children: [
          {
            label: 'Caste',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/hr/caste',
            icon: 'apartment',
            colorScheme: 'red',
            feature: '@master/HR/Caste',
            action: 'read',
          },
          {
            label: 'Post',
            description: 'Manage posts and positions',
            path: '/master/hr/post',
            icon: 'work',
            colorScheme: 'red',
            feature: '@master/HR/Post',
            action: 'read',
          },
          {
            label: 'Religion',
            description: 'Manage religions',
            path: '/master/hr/religion',
            icon: 'domain',
            colorScheme: 'red',
            feature: '@master/HR/Religion',
            action: 'read',
          },
          {
            label: 'Qualification',
            description: 'Manage qualifications',
            path: '/master/hr/qualification',
            icon: 'badge',
            colorScheme: 'red',
            feature: '@master/HR/Qualification',
            action: 'read',
          },
          {
            label: 'Class',
            description: 'Manage classes',
            path: '/master/hr/class',
            icon: 'class',
            colorScheme: 'red',
            feature: '@master/HR/Class',
            action: 'read',
          },
          {
            label: 'Section',
            description: 'Manage sections',
            path: '/master/hr/section',
            icon: 'segment',
            colorScheme: 'red',
            feature: '@master/HR/Section',
            action: 'read',
          },
          {
            label: 'Designation Type',
            description: 'Manage designation types',
            path: '/master/hr/designation-type',
            icon: 'category',
            colorScheme: 'red',
            feature: '@master/HR/DesignationType',
            action: 'read',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/hr/designation',
            icon: 'badge',
            colorScheme: 'red',
            feature: '@master/HR/Designation',
            action: 'read',
          },
        ],
      },
      {
        label: 'College',
        slug: 'college',
        description: 'Manage college types and Categorys.',
        path: '/home/sub-menu/college',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'College Type',
            description: 'Manage college types',
            path: '/master/college/college-type',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/College/CollegeType',
            action: 'write',
          },
          {
            label: 'Category',
            description: 'Manage college categories',
            path: '/master/college/college-category',
            icon: 'school',
            colorScheme: 'red',
            feature: '@master/College/CollegeCategory',
            action: 'write',
          },
        ],
      },
      {
        label: 'Other Masters',
        slug: 'other',
        description: 'Manage masters.',
        path: '/home/sub-menu/other',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'Degree Level',
            description: 'Manage degree levels',
            path: '/master/other/degree-level',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/DegreeLevel',
            action: 'read',
          },
          {
            label: 'Academic Year',
            description: 'Manage academic year records and session details',
            path: '/master/other/academic-year',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/AcademicYear',
            action: 'read',
          },
          {
            label: 'Programme',
            description: 'Manage programmes',
            path: '/master/other/programme',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Programme',
            action: 'read',
          },
          {
            label: 'Specialisation',
            description: 'Manage specialisations',
            path: '/master/other/specialisation',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Specialisation',
            action: 'read',
          },
          {
            label: 'Nationality',
            description: 'Manage nationalities',
            path: '/master/other/nationality',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/Nationality',
            action: 'read',
          },
        ],
      },
      {
        label: 'Grant',
        slug: 'grant',
        description: 'Manage grant types and categories.',
        path: '/home/sub-menu/grant',
        icon: 'workspace_premium',
        colorScheme: 'purple',
        children: [
          {
            label: 'Grant Type',
            description: 'Manage grant types',
            path: '/master/grant/grant-type',
            icon: 'workspace_premium',
            colorScheme: 'purple',
            feature: '@master/Grant/GrantType',
            action: 'write',
          },
          {
            label: 'Grant Category',
            description: 'Manage grant categories',
            path: '/master/grant/grant-category',
            icon: 'category',
            colorScheme: 'purple',
            feature: '@master/Grant/GrantCategory',
            action: 'write',
          },
          {
            label: 'Eligibility Application Process',
            description: 'Manage eligibility criteria and application process',
            path: '/master/grant/eligibility-application-process',
            icon: 'assignment_turned_in',
            colorScheme: 'purple',
            feature: '@master/Grant/EligibilityApplicationProcess',
            action: 'write',
          },
        ],
      },
      {
        label: 'Scheme',
        slug: 'scheme',
        description: 'Manage scheme types and categories.',
        path: '/home/sub-menu/scheme',
        icon: 'assignment',
        colorScheme: 'teal',
        children: [
          {
            label: 'Scheme Type',
            description: 'Manage scheme types',
            path: '/master/scheme/scheme-type',
            icon: 'assignment',
            colorScheme: 'teal',
            feature: '@master/Scheme/SchemeType',
            action: 'write',
          },
          {
            label: 'Scheme Category',
            description: 'Manage scheme categories',
            path: '/master/scheme/scheme-category',
            icon: 'category',
            colorScheme: 'teal',
            feature: '@master/Scheme/SchemeCategory',
            action: 'write',
          },
          {
            label: 'Schemes',
            description: 'Manage schemes',
            path: '/master/scheme/schemes',
            icon: 'assignment',
            colorScheme: 'teal',
            feature: '@master/Scheme/Schemes',
            action: 'write',
          },
        ],
      },
      {
        label: 'CMS Management',
        slug: 'cms-management',
        description:
          'Manage website content including courses, departments, faculty, news, downloads, gallery, facilities, stats, and notices.',
        path: '/home/sub-menu/cms-management',
        icon: 'web',
        colorScheme: 'blue',
        children: [
          {
            label: 'Courses',
            description: 'Manage courses and programs',
            path: '/master/cms-management/courses',
            icon: 'school',
            colorScheme: 'blue',
          },
          {
            label: 'Departments',
            description: 'Manage departments',
            path: '/master/cms-management/departments',
            icon: 'domain',
            colorScheme: 'blue',
          },
          {
            label: 'Faculty',
            description: 'Manage faculty members',
            path: '/master/cms-management/faculty',
            icon: 'groups',
            colorScheme: 'blue',
          },
          {
            label: 'News & Events',
            description: 'Manage news and events',
            path: '/master/cms-management/news',
            icon: 'feed',
            colorScheme: 'blue',
          },
          {
            label: 'Downloads',
            description: 'Manage downloadable forms and documents',
            path: '/master/cms-management/downloads',
            icon: 'download',
            colorScheme: 'blue',
          },
          {
            label: 'Gallery',
            description: 'Manage gallery images',
            path: '/master/cms-management/gallery',
            icon: 'image',
            colorScheme: 'blue',
          },
          {
            label: 'Facilities',
            description: 'Manage campus facilities',
            path: '/master/cms-management/facilities',
            icon: 'apartment',
            colorScheme: 'blue',
          },
          {
            label: 'Stats',
            description: 'Manage stats counter values',
            path: '/master/cms-management/stats',
            icon: 'bar_chart',
            colorScheme: 'blue',
          },
          {
            label: 'Notices',
            description: 'Manage scroll notices',
            path: '/master/cms-management/notices',
            icon: 'notifications',
            colorScheme: 'blue',
          },
        ],
      },
    ],
  },
  {
    label: 'Employee\nServices',
    slug: 'employee-services',
    category: 'Employee',
    icon: 'groups',
    colorScheme: 'red',
    description: 'Classes • Grades • Advising • Resources',
    children: [
      {
        label: 'Employee Management System',
        slug: 'employee-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/employee-management',
        icon: 'edit_location',
        colorScheme: 'red',
        navigationStyle: 'sidebar',
        children: [
          {
            label: 'Quick Onboarding',
            slug: 'quick-onboarding',
            description: 'Quick employee onboarding form.',
            path: '/employee-management/quick-onboarding',
            icon: 'person_add',
            colorScheme: 'red',
            feature: '@employee-management/quick-onboarding',
            action: 'write',
          },
          {
            label: 'Full Onboarding',
            slug: 'full-onboarding',
            description: 'Full employee onboarding form.',
            path: '/employee-management/full-onboarding',
            icon: 'person_add',
            colorScheme: 'red',
            feature: '@employee-management/full-onboarding',
            action: 'write',
          },
          {
            label: 'Manage Employee',
            slug: 'manage-employees',
            description: 'Manage and view employees list.',
            path: '/employee-management/manage-employees',
            icon: 'manage_accounts',
            colorScheme: 'blue',
            feature: '@employee-management/manage-employees',
            action: 'read',
          },
          {
            label: 'Settings',
            slug: 'settings',
            description:
              'Manage employee management system settings and masters.',
            path: '/home/sub-menu/settings',
            icon: 'settings',
            colorScheme: 'red',
            children: [
              {
                label: 'Nature of Employment',
                slug: 'nature-of-employment',
                description: 'Manage nature of employment master data.',
                path: '/employee-management/settings/nature-of-employment',
                icon: 'work',
                colorScheme: 'red',
                feature: '@employee/Settings/NatureOfEmployment',
                action: 'read',
              },
              {
                label: 'Organization Unit',
                slug: 'organization-unit',
                description: 'Manage organization unit master data.',
                path: '/employee-management/settings/organization-unit',
                icon: 'account_tree',
                colorScheme: 'red',
                feature: '@employee/Settings/OrganizationUnit',
                action: 'read',
              },
              {
                label: 'Document Option',
                slug: 'document-option',
                description: 'Manage document option master data.',
                path: '/employee-management/settings/document-option',
                icon: 'description',
                colorScheme: 'red',
                feature: '@employee/Settings/DocumentOption',
                action: 'read',
              },
              {
                label: 'Action Options',
                slug: 'action-option',
                description: 'Manage action options master data.',
                path: '/employee-management/settings/action-option',
                icon: 'settings_accessibility',
                colorScheme: 'red',
                feature: '@employee/Settings/ActionOption',
                action: 'read',
              },
              {
                label: 'Subject Specialization',
                slug: 'subject-specialization',
                description: 'Manage subject specialization master data.',
                path: '/employee-management/settings/subject-specialization',
                icon: 'menu_book',
                colorScheme: 'red',
                feature: '@employee/Settings/SubjectSpecialization',
                action: 'read',
              },
              {
                label: 'Action Option Reasons',
                slug: 'action-option-reasons',
                description: 'Manage action option reasons master data.',
                path: '/employee-management/settings/action-option-reason',
                icon: 'assignment_turned_in',
                colorScheme: 'red',
                feature: '@employee/Settings/ActionOptionReason',
                action: 'read',
              },
              {
                label: 'Separation Reasons',
                slug: 'separation-reason-type',
                description: 'Manage separation reasons master data.',
                path: '/master/employee/settings/separation-reason-type',
                icon: 'article',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Travel Purpose',
                slug: 'travel-purpose',
                description: 'Manage travel purpose master data.',
                path: '/employee-management/settings/travel-purpose',
                icon: 'travel_explore',
                colorScheme: 'red',
                feature: '@employee/Settings/TravelPurpose',
                action: 'read',
              },
              {
                label: 'Employee Group',
                slug: 'employee-group',
                description: 'Manage employee group master data.',
                path: '/master/employee/settings/employee-group',
                icon: 'groups',
                colorScheme: 'red',
                feature: '@employee/Settings/EmployeeGroup',
                action: 'read',
              },
            ],
          },
        ],
      },
      {
        label: 'Career Advancement',
        slug: 'career-advancement',
        description: 'Manage career advancement sessions and assessments.',
        path: '/home/sub-menu/career-advancement',
        icon: 'trending_up',
        colorScheme: 'orange',
        children: [
          {
            label: 'APAR — All Applications',
            slug: 'apar-application',
            description: 'Initiate and manage APAR for all employees',
            path: '/career-advancement/apar-application/all',
            icon: 'assignment',
            colorScheme: 'orange',
            feature: '@CareerAdvancement/AparApplication',
            action: 'Write',
          },
          {
            label: 'Sessions Management',
            slug: 'sessions-management',
            description:
              'Manage assessment sessions for career advancement programs.',
            path: '/career-advancement/sessions-management',
            icon: 'event',
            colorScheme: 'orange',
            feature: '@CareerAdvancement/SessionsManagement',
            action: 'write',
          },
          {
            label: 'Employee Self Assessment',
            slug: 'employee-self-assessment',
            description:
              'APAR Employee Self Assessment and performance reviews.',
            path: '/career-advancement/employee-self-assessment',
            icon: 'assignment',
            colorScheme: 'red',
            feature: '@CareerAdvancement/EmployeeSelfAssessment',
            action: 'write',
          },
          {
            label: 'Performance Appraisal System',
            slug: 'performance-appraisal-system',
            description:
              'APAR Employee Self Assessment and performance reviews.',
            path: '/career-advancement/performance-appraisal-system',
            icon: 'assignment',
            colorScheme: 'red',
            feature: '@CareerAdvancement/PerformanceAppraisalSystem',
            action: 'write',
          },
        ],
      },
    ],
  },
  {
    label: 'Academics',
    slug: 'academics',
    category: 'Academics',
    icon: 'grid_view',
    colorScheme: 'red',
    description: 'Manage registrar and admin functions',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Programme Management',
        slug: 'programme-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Admission Admin Guide',
        slug: 'admission-admin-guide',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Academics',
        slug: 'academics',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Evaluation & Grading',
        slug: 'evaluation-&-grading',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Exam Management',
        slug: 'examination-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Certificate Management',
        slug: 'certificate-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Feedback Management',
        slug: 'student-feedback-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Student Additional Information',
        slug: 'student-additional-information',
        description: 'Manage student additional details.',
        path: '/sis/student-additional-information',
        icon: 'person_add',
        colorScheme: 'red',
        feature: '@sis/StudentAdditionalInformation',
        action: 'read',
      },
      {
        label: 'Student Application Form',
        slug: 'student-application-form',
        description: 'Create and submit student applications.',
        path: '/sis/student-application-form',
        icon: 'assignment',
        colorScheme: 'red',
        feature: '@sis/StudentApplicationForm',
        action: 'read',
      },
      {
        label: 'Fee Payment Approval (Temp)',
        slug: 'student-fee-approval',
        description: 'Approve student application fee payments.',
        path: '/sis/student-fee-approval',
        icon: 'check_circle',
        colorScheme: 'red',
        feature: '@sis/StudentFeeApproval',
        action: 'read',
      },
    ],
  },
  {
    label: 'Accounts And Finance',
    slug: 'accounts-and-finance',
    category: 'Finance',
    icon: 'menu_book',
    colorScheme: 'red',
    description: 'Streamline curriculum management and approvals',
    children: [
      {
        label: 'Financial Supply Chain Management',
        slug: 'financial-supply-chain-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  {
    label: 'Governance',
    slug: 'governance',
    category: 'Governance',
    icon: 'bolt',
    colorScheme: 'red',
    description: 'Track student competencies and skill development',
    children: [
      {
        label: 'Affiliation Management',
        slug: 'affiliation-Management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Communication System',
        slug: 'core-communication-system',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Grievance Management',
        slug: 'grievance-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Residential Allocation',
        slug: 'residential-allocation-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Hostel Managemnet',
        slug: 'hostel-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  {
    label: 'Affiliation Management System',
    slug: 'affiliation-management-system',
    category: 'Affiliation Management System',
    icon: 'groups',
    colorScheme: 'red',
    description: 'Classes • Grades • Advising • Resources',
    children: [
      {
        label: 'College Registration',
        slug: 'college-registration',
        description: 'Manage college registration processes.',
        path: '/affiliation-management-system/college-registration',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [
          {
            label: 'college Registration',
            slug: 'college-registration',
            description: 'Manage college registration processes.',
            path: '/affiliation-management-system/college-registration',
            icon: 'assignment',
            colorScheme: 'orange',
            // feature: '@affiliation/CollegeRegistration',
            // action: 'read',
          },
        ],
      },
      {
        label: 'Draft College Registration',
        slug: 'draft-registration-request',
        description: 'Manage draft college registration processes.',
        path: '/affiliation-management-system/draft-registration-request',
        icon: 'assignment',
        colorScheme: 'orange',
      },

      {
        label: 'College Registration Approvals',
        slug: 'registration-approval',
        description: 'Manage college registration Approvals.',
        path: '/affiliation-management-system/registration-approval',
        icon: 'edit_location',
        colorScheme: 'green',
        // feature: '@collegeaffiliation/collegeregistrationapproval',
        // action: 'read',
      },
      {
        label: 'Affiliation Settings',
        slug: 'affiliation-settings',
        description: 'Manage affiliation settings',
        path: '/home/sub-menu/affiliation-settings',
        icon: 'settings',
        colorScheme: 'red',
        children: [
          {
            label: 'Available Facility',
            slug: 'available-facility',
            description: 'Manage available facility',
            path: '/affiliation-management-system/affiliation-settings/available-facility',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/College/AvailableFacility',
            action: 'read',
          },
          {
            label: 'Establishment Year',
            slug: 'establishment-year',
            description: 'Manage Establishment Year',
            path: '/affiliation-management-system/affiliation-settings/establishment-year',
            icon: 'school',
            colorScheme: 'indigo',
            feature: '@master/Other/EstablishmentYear',
            action: 'read',
          },
          {
            label: 'Programme Fee',
            description: 'Manage programme fees',
            path: '/affiliation-management-system/affiliation-settings/programme-fee',
            icon: 'money',
            colorScheme: 'blue',
            feature: '@master/Affiliation/ProgrammeFee',
            action: 'read',
          },
        ],
      },
    ],
  },
  // {
  //   label: 'Career\nGateway',
  //   slug: 'career-gateway',
  //   category: 'HR',
  //   icon: 'work',
  //   colorScheme: 'red',
  //   description: 'Career services and job placement resources',
  // },
  // {
  //   label: 'ICON – Research Compliance',
  //   slug: 'icon-research-compliance',
  //   category: 'Academics',
  //   icon: 'science',
  //   colorScheme: 'orange',
  //   description: 'Manage research compliance and ethics approvals',
  // },
  // {
  //   label: 'Disability\nCenter',
  //   slug: 'disability-center',
  //   category: 'HR',
  //   icon: 'accessible',
  //   colorScheme: 'pink',
  //   description: 'Support services for students with disabilities',
  // },
  // {
  //   label: 'Student ID & Campus Allowance',
  //   slug: 'student-id-campus-allowance',
  //   category: 'Finance',
  //   icon: 'credit_card',
  //   colorScheme: 'blue',
  //   description: 'Manage student IDs and campus financial allowances',
  // },
  // {
  //   label: 'University Queue – Virtual Queuing',
  //   slug: 'university-queue-virtual-queuing',
  //   category: 'Operation',
  //   icon: 'desktop_windows',
  //   colorScheme: 'purple',
  //   description: 'Virtual queuing system for campus services',
  // },
  // {
  //   label: 'FIXIT — Facility Management',
  //   slug: 'fixit-facility-management',
  //   category: 'Operation',
  //   icon: 'build',
  //   colorScheme: 'teal',
  //   description: 'Report and manage facility maintenance issues',
  // },
  // {
  //   label: 'Scholarship&\nGrants',
  //   slug: 'scholarship-grants',
  //   category: 'Finance',
  //   icon: 'workspace_premium',
  //   colorScheme: 'indigo',
  //   description: 'Manage scholarship and grant applications',
  // },
];

export function useMenu() {
  const { authenticated, permissions } = useAuth();

  return useMemo(() => {
    if (!authenticated) return [];

    const filterMenu = (items: Menu.MenuItem[]): Menu.MenuItem[] => {
      return items
        .filter(item => {
          if (item.feature && item.action) {
            return hasPermission(permissions, item.feature, item.action);
          }
          return true;
        })
        .map(item => {
          if (item.children) {
            return { ...item, children: filterMenu(item.children) };
          }
          return item;
        })
        .filter(item => {
          if (item.children) {
            // Parent menus/folders must have at least one visible child to be shown.
            // If all of their children are filtered out, the parent menu is also hidden.
            return item.children.length > 0;
          }
          return true;
        });
    };

    return filterMenu(menuConfig);
  }, [authenticated, permissions]);
}
