const baseUrl = '/open-book-examination';

export const obeUrls = {
  admin: {
    dashboard: `${baseUrl}/admin/dashboard`,
    academicSessions: `${baseUrl}/admin/academic-sessions`,
    programs: `${baseUrl}/admin/programs`,
    courses: `${baseUrl}/admin/courses`,
    examTypes: `${baseUrl}/admin/exam-types`,
    policies: `${baseUrl}/admin/open-book-policies`,
    users: `${baseUrl}/admin/users`,
    eligibility: `${baseUrl}/admin/eligibility`,
    admitCards: `${baseUrl}/admin/admit-cards`,
    evaluators: `${baseUrl}/admin/evaluators`,
    submissionMonitor: `${baseUrl}/admin/submission-monitor`,
    moderation: `${baseUrl}/admin/moderation`,
    resultPublishing: `${baseUrl}/admin/result-publishing`,
    revaluation: `${baseUrl}/admin/revaluation`,
    config: `${baseUrl}/admin/config`,
    auditLogs: `${baseUrl}/admin/audit-logs`,
    gradeCards: `${baseUrl}/admin/grade-cards`,
  },
  teacher: {
    dashboard: `${baseUrl}/teacher/dashboard`,
    exams: `${baseUrl}/teacher/exams`,
    examCreate: `${baseUrl}/teacher/exams/create`,
    examEdit: (id: number) => `${baseUrl}/teacher/exams/${id}/edit`,
    questionBank: `${baseUrl}/teacher/question-bank`,
    questionCreate: `${baseUrl}/teacher/question-bank/create`,
    questionEdit: (id: number) => `${baseUrl}/teacher/question-bank/${id}/edit`,
    bulkImport: `${baseUrl}/teacher/question-bank/import`,
    paperBuilder: (examId: number) =>
      `${baseUrl}/teacher/paper-builder/${examId}`,
    resources: `${baseUrl}/teacher/resources`,
    approvals: `${baseUrl}/teacher/approvals`,
    evaluation: `${baseUrl}/teacher/evaluation`,
    answerViewer: (attemptId: number) =>
      `${baseUrl}/teacher/evaluation/${attemptId}`,
    rubrics: `${baseUrl}/teacher/rubrics`,
    evaluationProgress: `${baseUrl}/teacher/evaluation/progress`,
    reEvalRequests: `${baseUrl}/teacher/re-evaluation`,
    reEvalInterface: (id: number) => `${baseUrl}/teacher/re-evaluation/${id}`,
  },
  student: {
    dashboard: `${baseUrl}/student/dashboard`,
    registration: `${baseUrl}/student/registration`,
    schedule: `${baseUrl}/student/schedule`,
    examInstructions: (id: number) =>
      `${baseUrl}/student/exam/${id}/instructions`,
    resources: (id: number) => `${baseUrl}/student/exam/${id}/resources`,
    takeExam: (id: number) => `${baseUrl}/student/exam/${id}/take`,
    receipt: (id: number) => `${baseUrl}/student/exam/${id}/receipt`,
    results: `${baseUrl}/student/results`,
    resultDetail: (id: number) => `${baseUrl}/student/results/${id}`,
    revaluation: `${baseUrl}/student/revaluation`,
  },
  reports: {
    eligibilityAttendance: `${baseUrl}/reports/eligibility-attendance`,
    submissionStatus: `${baseUrl}/reports/submission-status`,
    evaluationProgress: `${baseUrl}/reports/evaluation-progress`,
    resultAnalysis: `${baseUrl}/reports/result-analysis`,
    departmentPerformance: `${baseUrl}/reports/department-performance`,
    bloomsTaxonomy: `${baseUrl}/reports/blooms-taxonomy`,
    copoAttainment: `${baseUrl}/reports/co-po-attainment`,
    gradeDistribution: `${baseUrl}/reports/grade-distribution`,
    historicalComparison: `${baseUrl}/reports/historical-comparison`,
    questionAnalysis: `${baseUrl}/reports/question-analysis`,
    auditLogReport: `${baseUrl}/reports/audit-log`,
    customReport: `${baseUrl}/reports/custom`,
  },
};
