import type {
  MembershipType,
  MembershipCardTemplate,
  UnitType,
  FacilityMaster,
  Facility,
  Hospital,
  DoctorSpeciality,
  Doctor,
  HealthRecordDay,
  ReferralTemplate,
  PrescriptionControl,
  Membership,
  Dependent,
  MedicineBrand,
  MedicineCompany,
  MedicineSalt,
  MedicineStockType,
  MedicalStock,
  PrescriptionCode,
  Prescription,
  Dispensary,
  Appointment,
  GuestUser,
  HealthRecord,
  Subscription,
  AuditLog,
} from './types';

export const membershipTypes: MembershipType[] = [
  {
    id: 'MT-001',
    name: 'Student Health Plan',
    memberType: 'Student',
    healthCenter: 'Campus Health Center',
    benefits: 'General OPD, Emergency Care, Annual Checkup',
    validityType: 'Valid Till',
    validityDays: 0,
    validityMonths: 0,
    validityYears: 1,
    status: 'Active',
    feeApplicable: 'Yes',
    feeAmount: 2500,
  },
  {
    id: 'MT-002',
    name: 'Faculty Family Plan',
    memberType: 'Employee',
    healthCenter: 'Campus Health Center',
    benefits: 'OPD, IPD, Maternity, Dental',
    validityType: 'Valid Till',
    validityDays: 0,
    validityMonths: 0,
    validityYears: 1,
    status: 'Active',
    feeApplicable: 'Yes',
    feeAmount: 5000,
  },
  {
    id: 'MT-003',
    name: 'Staff Wellness',
    memberType: 'Employee',
    healthCenter: 'Wellness Clinic',
    benefits: 'General OPD, Physiotherapy',
    validityType: 'Lifetime',
    validityDays: 0,
    validityMonths: 0,
    validityYears: 0,
    status: 'Active',
    feeApplicable: 'No',
    feeAmount: 0,
  },
  {
    id: 'MT-004',
    name: 'Guest Medical',
    memberType: 'Guest',
    healthCenter: 'University Hospital',
    benefits: 'Emergency Care Only',
    validityType: 'Valid Till',
    validityDays: 30,
    validityMonths: 0,
    validityYears: 0,
    status: 'Active',
    feeApplicable: 'Yes',
    feeAmount: 1000,
  },
];

export const membershipCardTemplates: MembershipCardTemplate[] = [
  {
    id: 'MCT-001',
    name: 'Standard Blue Card',
    templateBody:
      '<h2>University Health Services</h2><p>Member: {name}</p><p>Type: {type}</p><p>Valid Till: {validTill}</p>',
    backgroundColor: '#1e40af',
    status: 'Active',
  },
  {
    id: 'MCT-002',
    name: 'Green Wellness Card',
    templateBody:
      '<h2>Wellness Program</h2><p>Member: {name}</p><p>Validity: Lifetime</p>',
    backgroundColor: '#15803d',
    status: 'Active',
  },
];

export const unitTypes: UnitType[] = [
  {
    id: 'UT-001',
    type: 'Hospital',
    description: 'Full-service hospital with IPD facilities',
    status: 'Active',
  },
  {
    id: 'UT-002',
    type: 'Clinic',
    description: 'OPD clinic for general consultations',
    status: 'Active',
  },
  {
    id: 'UT-003',
    type: 'Dispensary',
    description: 'Medicine dispensing unit',
    status: 'Active',
  },
];

export const facilityMasters: FacilityMaster[] = [
  {
    id: 'FM-001',
    name: 'General Medicine',
    description: 'General medical consultations',
    status: 'Active',
  },
  {
    id: 'FM-002',
    name: 'Emergency',
    description: 'Emergency and trauma care',
    status: 'Active',
  },
  {
    id: 'FM-003',
    name: 'Maternity',
    description: 'Maternal and child health',
    status: 'Active',
  },
  {
    id: 'FM-004',
    name: 'Dental',
    description: 'Dental checkups and procedures',
    status: 'Active',
  },
  {
    id: 'FM-005',
    name: 'Physiotherapy',
    description: 'Rehabilitation and physio',
    status: 'Active',
  },
];

export const facilities: Facility[] = [
  {
    id: 'FAC-001',
    healthCenter: 'Campus Health Center',
    facilityName: 'General OPD',
    details: 'General outpatient consultations',
    status: 'Active',
  },
  {
    id: 'FAC-002',
    healthCenter: 'Campus Health Center',
    facilityName: 'Pharmacy',
    details: 'Medicine dispensing',
    status: 'Active',
  },
  {
    id: 'FAC-003',
    healthCenter: 'University Hospital',
    facilityName: 'Emergency & Trauma',
    details: '24x7 emergency services',
    status: 'Active',
  },
  {
    id: 'FAC-004',
    healthCenter: 'University Hospital',
    facilityName: 'Maternity Ward',
    details: 'Delivery and postnatal care',
    status: 'Active',
  },
  {
    id: 'FAC-005',
    healthCenter: 'Wellness Clinic',
    facilityName: 'Physiotherapy',
    details: 'Rehabilitation services',
    status: 'Active',
  },
];

export const hospitals: Hospital[] = [
  {
    id: 'HOS-001',
    name: 'University Hospital',
    registrationNo: 'UH-001-2020',
    affiliation: 'Affiliated',
    unitType: 'Hospital',
    facility: 'General Medicine',
    contactNo: '+91-1234567890',
    address: 'Main Campus, University Road',
    status: 'Active',
    remarks: 'Primary referral hospital',
  },
  {
    id: 'HOS-002',
    name: 'City General Hospital',
    registrationNo: 'CGH-002-2019',
    affiliation: 'Attached',
    unitType: 'Hospital',
    facility: 'Emergency',
    contactNo: '+91-9876543210',
    address: 'Civil Lines, City Center',
    status: 'Active',
    remarks: '',
  },
  {
    id: 'HOS-003',
    name: 'Sunrise Dental Clinic',
    registrationNo: 'SDC-003-2021',
    affiliation: 'Attached',
    unitType: 'Clinic',
    facility: 'Dental',
    contactNo: '+91-5551234567',
    address: 'Market Road, Phase 2',
    status: 'Active',
    remarks: 'Dental referrals only',
  },
];

export const doctorSpecialities: DoctorSpeciality[] = [
  {
    id: 'DS-001',
    speciality: 'Physician',
    description: 'General physician',
    status: 'Active',
  },
  {
    id: 'DS-002',
    speciality: 'Cardiologist',
    description: 'Heart specialist',
    status: 'Active',
  },
  {
    id: 'DS-003',
    speciality: 'Orthopedic',
    description: 'Bone and joint specialist',
    status: 'Active',
  },
  {
    id: 'DS-004',
    speciality: 'Ophthalmologist',
    description: 'Eye specialist',
    status: 'Active',
  },
  {
    id: 'DS-005',
    speciality: 'Dentist',
    description: 'Dental care specialist',
    status: 'Active',
  },
  {
    id: 'DS-006',
    speciality: 'Gynecologist',
    description: 'Women health specialist',
    status: 'Active',
  },
];

export const doctors: Doctor[] = [
  {
    id: 'DOC-001',
    isUniversityDoctor: 'Yes',
    universityDoctorName: 'Dr. Priya Mehta',
    profileId: '',
    name: '',
    contact: '+91-9876543211',
    address: 'Faculty Quarters, Campus',
    hospital: 'University Hospital',
    email: 'priya.mehta@university.edu.in',
    gender: 'Female',
    experience: 12,
    visitingHoursStart: '09:00',
    visitingHoursEnd: '17:00',
    visitingDays: 'Mon,Tue,Wed,Thu,Fri',
    visitingStatus: 'Available',
    speciality: 'Physician',
    extraInfo: 'Available for OPD consultations',
    status: 'Active',
  },
  {
    id: 'DOC-002',
    isUniversityDoctor: 'No',
    universityDoctorName: '',
    profileId: 'PROF-4231',
    name: 'Dr. Suresh Patel',
    contact: '+91-9876543212',
    address: '12, Green Park Colony',
    hospital: 'University Hospital',
    email: 'suresh.patel@cityhospital.com',
    gender: 'Male',
    experience: 18,
    visitingHoursStart: '10:00',
    visitingHoursEnd: '16:00',
    visitingDays: 'Mon,Wed,Fri',
    visitingStatus: 'Available',
    speciality: 'Cardiologist',
    extraInfo: 'Visiting consultant',
    status: 'Active',
  },
  {
    id: 'DOC-003',
    isUniversityDoctor: 'Yes',
    universityDoctorName: 'Dr. Ananya Gupta',
    profileId: '',
    name: '',
    contact: '+91-9876543213',
    address: 'Teachers Colony, Campus',
    hospital: 'Campus Health Center',
    email: 'ananya.gupta@university.edu.in',
    gender: 'Female',
    experience: 8,
    visitingHoursStart: '08:00',
    visitingHoursEnd: '14:00',
    visitingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    visitingStatus: 'Available',
    speciality: 'Orthopedic',
    extraInfo: '',
    status: 'Active',
  },
  {
    id: 'DOC-004',
    isUniversityDoctor: 'No',
    universityDoctorName: '',
    profileId: 'PROF-5678',
    name: 'Dr. Rohan Deshmukh',
    contact: '+91-9876543214',
    address: '34, Lake View Apartments',
    hospital: 'Sunrise Dental Clinic',
    email: 'rohan.deshmukh@dentalclinic.com',
    gender: 'Male',
    experience: 10,
    visitingHoursStart: '09:00',
    visitingHoursEnd: '18:00',
    visitingDays: 'Mon,Tue,Wed,Thu,Fri',
    visitingStatus: 'Available',
    speciality: 'Dentist',
    extraInfo: 'Dental surgeries available',
    status: 'Active',
  },
  {
    id: 'DOC-005',
    isUniversityDoctor: 'Yes',
    universityDoctorName: 'Dr. Kavita Nair',
    profileId: '',
    name: '',
    contact: '+91-9876543215',
    address: 'Faculty Housing, Block C',
    hospital: 'University Hospital',
    email: 'kavita.nair@university.edu.in',
    gender: 'Female',
    experience: 15,
    visitingHoursStart: '11:00',
    visitingHoursEnd: '15:00',
    visitingDays: 'Tue,Thu,Sat',
    visitingStatus: 'Available',
    speciality: 'Gynecologist',
    extraInfo: 'Appointment required',
    status: 'Active',
  },
];

export const healthRecordDays: HealthRecordDay[] = [
  { id: 'HRD-001', days: 10 },
];

export const referralTemplates: ReferralTemplate[] = [
  {
    id: 'RT-001',
    name: 'Standard Referral Letter',
    templateBody:
      '<h3>Medical Referral</h3><p>Patient: {patientName}</p><p>Referred to: {hospitalName}</p><p>Reason: {reason}</p>',
    backgroundColor: '#ffffff',
    status: 'Active',
  },
  {
    id: 'RT-002',
    name: 'Emergency Referral',
    templateBody:
      '<h3>Emergency Referral</h3><p>Patient: {patientName}</p><p>Urgent referral to: {hospitalName}</p>',
    backgroundColor: '#fee2e2',
    status: 'Active',
  },
];

export const prescriptionControl: PrescriptionControl[] = [
  { id: 'PC-001', showSignature: true },
];

export const dependents: Dependent[] = [
  { id: 'DEP-001', name: 'Smt. Sunita Verma', relation: 'Spouse' },
  { id: 'DEP-002', name: 'Master. Arjun Verma', relation: 'Son' },
];

export const memberships: Membership[] = [
  {
    id: 'MEM-001',
    memberType: 'Employee',
    memberId: 'USR-EMP-001',
    memberName: 'Mr. Amit Verma',
    program: 'B.Tech',
    academicYear: '2024-25',
    academicSession: 'Odd Semester',
    academicSection: 'A',
    healthCenter: 'Campus Health Center',
    membershipTypeId: 'MT-002',
    membershipTypeName: 'Faculty Family Plan',
    membershipDate: '2024-08-01',
    validFrom: '2024-08-01',
    validityType: 'Valid Till',
    validTill: '2025-07-31',
    dependents: [dependents[0], dependents[1]],
  },
  {
    id: 'MEM-002',
    memberType: 'Student',
    memberId: 'STU-001',
    memberName: 'Ms. Priya Sharma',
    program: 'M.Sc. Computer Science',
    academicYear: '2024-25',
    academicSession: 'Odd Semester',
    academicSection: 'B',
    healthCenter: 'Campus Health Center',
    membershipTypeId: 'MT-001',
    membershipTypeName: 'Student Health Plan',
    membershipDate: '2024-07-15',
    validFrom: '2024-08-01',
    validityType: 'Valid Till',
    validTill: '2025-07-31',
    dependents: [],
  },
  {
    id: 'MEM-003',
    memberType: 'Employee',
    memberId: 'USR-EMP-002',
    memberName: 'Dr. Neha Gupta',
    program: '',
    academicYear: '',
    academicSession: '',
    academicSection: '',
    healthCenter: 'Wellness Clinic',
    membershipTypeId: 'MT-003',
    membershipTypeName: 'Staff Wellness',
    membershipDate: '2024-01-01',
    validFrom: '2024-01-01',
    validityType: 'Lifetime',
    validTill: '',
    dependents: [],
  },
  {
    id: 'MEM-004',
    memberType: 'Guest',
    memberId: 'GST-001',
    memberName: 'Mr. Ravi Krishnan',
    program: '',
    academicYear: '',
    academicSession: '',
    academicSection: '',
    healthCenter: 'University Hospital',
    membershipTypeId: 'MT-004',
    membershipTypeName: 'Guest Medical',
    membershipDate: '2024-11-01',
    validFrom: '2024-11-01',
    validityType: 'Valid Till',
    validTill: '2024-11-30',
    dependents: [],
  },
];

export const medicineBrands: MedicineBrand[] = [
  { id: 'BR-001', brandName: 'Cipla', remarks: 'Leading pharma brand' },
  { id: 'BR-002', brandName: 'Sun Pharma', remarks: '' },
  { id: 'BR-003', brandName: "Dr. Reddy's", remarks: '' },
  { id: 'BR-004', brandName: 'Pfizer', remarks: 'Imported medicines' },
];

export const medicineCompanies: MedicineCompany[] = [
  { id: 'COMP-001', companyName: 'Cipla Ltd.', remarks: '' },
  { id: 'COMP-002', companyName: 'Sun Pharmaceutical Industries', remarks: '' },
  { id: 'COMP-003', companyName: "Dr. Reddy's Laboratories", remarks: '' },
  { id: 'COMP-004', companyName: 'Pfizer India', remarks: '' },
];

export const medicineSalts: MedicineSalt[] = [
  {
    id: 'SALT-001',
    saltName: 'Paracetamol',
    remarks: 'Analgesic and antipyretic',
  },
  { id: 'SALT-002', saltName: 'Amoxicillin', remarks: 'Antibiotic' },
  { id: 'SALT-003', saltName: 'Omeprazole', remarks: 'Proton pump inhibitor' },
  {
    id: 'SALT-004',
    saltName: 'Amlodipine',
    remarks: 'Calcium channel blocker',
  },
  { id: 'SALT-005', saltName: 'Metformin', remarks: 'Anti-diabetic' },
  { id: 'SALT-006', saltName: 'Cetirizine', remarks: 'Antihistamine' },
  { id: 'SALT-007', saltName: 'Ibuprofen', remarks: 'NSAID' },
  { id: 'SALT-008', saltName: 'Azithromycin', remarks: 'Antibiotic' },
];

export const medicineStockTypes: MedicineStockType[] = [
  {
    id: 'ST-001',
    name: 'Tablet',
    description: 'Solid oral dosage form',
    disabled: false,
  },
  {
    id: 'ST-002',
    name: 'Capsule',
    description: 'Encapsulated oral dosage',
    disabled: false,
  },
  {
    id: 'ST-003',
    name: 'Syrup',
    description: 'Liquid oral dosage',
    disabled: false,
  },
  {
    id: 'ST-004',
    name: 'Injection',
    description: 'Injectable dosage',
    disabled: false,
  },
  {
    id: 'ST-005',
    name: 'Cream',
    description: 'Topical cream',
    disabled: false,
  },
];

export const medicalStocks: MedicalStock[] = [
  {
    id: 'STK-001',
    brandId: 'BR-001',
    brandName: 'Cipla',
    companyId: 'COMP-001',
    companyName: 'Cipla Ltd.',
    saltId: 'SALT-001',
    saltName: 'Paracetamol',
    stockTypeId: 'ST-001',
    stockTypeName: 'Tablet',
    batchNo: 'CIP-PCM-2401',
    expiryDate: '2026-06-30',
    quantity: 500,
    unitPrice: 1.5,
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'STK-002',
    brandId: 'BR-002',
    brandName: 'Sun Pharma',
    companyId: 'COMP-002',
    companyName: 'Sun Pharmaceutical Industries',
    saltId: 'SALT-002',
    saltName: 'Amoxicillin',
    stockTypeId: 'ST-002',
    stockTypeName: 'Capsule',
    batchNo: 'SUN-AMX-2402',
    expiryDate: '2025-12-31',
    quantity: 200,
    unitPrice: 5.0,
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'STK-003',
    brandId: 'BR-001',
    brandName: 'Cipla',
    companyId: 'COMP-001',
    companyName: 'Cipla Ltd.',
    saltId: 'SALT-006',
    saltName: 'Cetirizine',
    stockTypeId: 'ST-001',
    stockTypeName: 'Tablet',
    batchNo: 'CIP-CTZ-2403',
    expiryDate: '2026-03-31',
    quantity: 300,
    unitPrice: 2.0,
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'STK-004',
    brandId: 'BR-003',
    brandName: "Dr. Reddy's",
    companyId: 'COMP-003',
    companyName: "Dr. Reddy's Laboratories",
    saltId: 'SALT-007',
    saltName: 'Ibuprofen',
    stockTypeId: 'ST-001',
    stockTypeName: 'Tablet',
    batchNo: 'DRL-IBU-2404',
    expiryDate: '2025-09-30',
    quantity: 150,
    unitPrice: 3.0,
    healthCenter: 'University Hospital',
  },
  {
    id: 'STK-005',
    brandId: 'BR-004',
    brandName: 'Pfizer',
    companyId: 'COMP-004',
    companyName: 'Pfizer India',
    saltId: 'SALT-008',
    saltName: 'Azithromycin',
    stockTypeId: 'ST-001',
    stockTypeName: 'Tablet',
    batchNo: 'PFZ-AZI-2405',
    expiryDate: '2026-01-31',
    quantity: 100,
    unitPrice: 8.0,
    healthCenter: 'University Hospital',
  },
  {
    id: 'STK-006',
    brandId: 'BR-002',
    brandName: 'Sun Pharma',
    companyId: 'COMP-002',
    companyName: 'Sun Pharmaceutical Industries',
    saltId: 'SALT-003',
    saltName: 'Omeprazole',
    stockTypeId: 'ST-002',
    stockTypeName: 'Capsule',
    batchNo: 'SUN-OME-2406',
    expiryDate: '2025-08-31',
    quantity: 0,
    unitPrice: 4.5,
    healthCenter: 'Campus Health Center',
  },
];

export const prescriptionCodes: PrescriptionCode[] = [
  { id: 'PC-001', code: 'OD', doseQuantity: '1', description: 'Once daily' },
  { id: 'PC-002', code: 'BD', doseQuantity: '1', description: 'Twice daily' },
  {
    id: 'PC-003',
    code: 'TDS',
    doseQuantity: '1',
    description: 'Three times daily',
  },
  {
    id: 'PC-004',
    code: 'QID',
    doseQuantity: '1',
    description: 'Four times daily',
  },
  { id: 'PC-005', code: 'HS', doseQuantity: '1', description: 'At bedtime' },
  { id: 'PC-006', code: 'SOS', doseQuantity: '1', description: 'As needed' },
];

export const prescriptions: Prescription[] = [
  {
    id: 'PRX-001',
    healthRecordId: 'HR-001',
    prescribedOn: '2024-11-15',
    patientName: 'Mr. Amit Verma',
    remarks: 'Take after meals',
    items: [
      {
        medicineId: 'STK-001',
        medicineName: 'Paracetamol 500mg',
        dose: '1',
        frequency: 'TDS',
        duration: '5 days',
      },
      {
        medicineId: 'STK-003',
        medicineName: 'Cetirizine 10mg',
        dose: '1',
        frequency: 'HS',
        duration: '3 days',
      },
    ],
    declaration: true,
    prescribedBy: 'Dr. Priya Mehta',
  },
  {
    id: 'PRX-002',
    healthRecordId: 'HR-002',
    prescribedOn: '2024-11-20',
    patientName: 'Ms. Priya Sharma',
    remarks: 'Complete the course',
    items: [
      {
        medicineId: 'STK-002',
        medicineName: 'Amoxicillin 500mg',
        dose: '1',
        frequency: 'BD',
        duration: '7 days',
      },
    ],
    declaration: true,
    prescribedBy: 'Dr. Suresh Patel',
  },
];

export const dispensaries: Dispensary[] = [
  {
    id: 'DSP-001',
    healthRecordId: 'HR-001',
    dispensedOn: '2024-11-15',
    patientName: 'Mr. Amit Verma',
    remarks: 'Dispensed as prescribed',
    items: [
      {
        medicineId: 'STK-001',
        medicineName: 'Paracetamol 500mg',
        dose: '1',
        frequency: 'TDS',
        duration: '5 days',
      },
      {
        medicineId: 'STK-003',
        medicineName: 'Cetirizine 10mg',
        dose: '1',
        frequency: 'HS',
        duration: '3 days',
      },
    ],
    declaration: true,
    dispensedBy: 'Mr. Rajesh Kumar',
  },
];

export const appointments: Appointment[] = [
  {
    id: 'APT-001',
    memberId: 'USR-EMP-001',
    memberName: 'Mr. Amit Verma',
    doctorId: 'DOC-001',
    doctorName: 'Dr. Priya Mehta',
    speciality: 'Physician',
    date: '2024-12-01',
    timeSlot: '09:00-09:30',
    status: 'Scheduled',
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'APT-002',
    memberId: 'STU-001',
    memberName: 'Ms. Priya Sharma',
    doctorId: 'DOC-003',
    doctorName: 'Dr. Ananya Gupta',
    speciality: 'Orthopedic',
    date: '2024-12-02',
    timeSlot: '10:00-10:30',
    status: 'Scheduled',
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'APT-003',
    memberId: 'USR-EMP-002',
    memberName: 'Dr. Neha Gupta',
    doctorId: 'DOC-001',
    doctorName: 'Dr. Priya Mehta',
    speciality: 'Physician',
    date: '2024-11-28',
    timeSlot: '11:00-11:30',
    status: 'Completed',
    healthCenter: 'Campus Health Center',
  },
  {
    id: 'APT-004',
    memberId: 'USR-EMP-001',
    memberName: 'Mr. Amit Verma',
    doctorId: 'DOC-005',
    doctorName: 'Dr. Kavita Nair',
    speciality: 'Gynecologist',
    date: '2024-11-25',
    timeSlot: '14:00-14:30',
    status: 'Cancelled',
    healthCenter: 'University Hospital',
  },
];

export const guestUsers: GuestUser[] = [
  {
    id: 'GST-001',
    name: 'Mr. Ravi Krishnan',
    email: 'ravi.krishnan@gmail.com',
    mobile: '+91-9988776655',
    dateOfBirth: '1985-06-15',
    gender: 'Male',
    bloodGroup: 'O+',
    status: 'Active',
    remarks: 'Conference visitor',
  },
  {
    id: 'GST-002',
    name: "Ms. Lisa D'Souza",
    email: 'lisa.dsouza@yahoo.com',
    mobile: '+91-8877665544',
    dateOfBirth: '1992-11-20',
    gender: 'Female',
    bloodGroup: 'A+',
    status: 'Active',
    remarks: 'Guest lecturer',
  },
];

export const healthRecords: HealthRecord[] = [
  {
    id: 'HR-001',
    membershipId: 'MEM-001',
    memberName: 'Mr. Amit Verma',
    membershipTypeName: 'Faculty Family Plan',
    healthCenter: 'Campus Health Center',
    isDependent: 'No',
    dependentId: '',
    dependentName: '',
    dependentRelation: '',
    dateOfVisit: '2024-11-15',
    timeOfVisit: '10:30',
    height: '172',
    weight: '75',
    bloodGroup: 'B+',
    pastMedicalHistory: 'Nil',
    regularMedicine: 'None',
    drugAllergy: 'None',
    chiefComplaint: 'Fever and cough since 3 days',
    examinationFindings: 'Temperature 101°F, throat congestion',
    prescription: 'Paracetamol 500mg TDS x 5 days, Cetirizine 10mg HS x 3 days',
    clinicalNoting: 'Upper respiratory tract infection',
    referredToHospital: 'No',
    approvedHospital: '',
    referralTemplate: '',
    createdBy: 'Dr. Priya Mehta',
    createdAt: '2024-11-15T10:45:00',
  },
  {
    id: 'HR-002',
    membershipId: 'MEM-002',
    memberName: 'Ms. Priya Sharma',
    membershipTypeName: 'Student Health Plan',
    healthCenter: 'Campus Health Center',
    isDependent: 'No',
    dependentId: '',
    dependentName: '',
    dependentRelation: '',
    dateOfVisit: '2024-11-20',
    timeOfVisit: '14:00',
    height: '160',
    weight: '55',
    bloodGroup: 'A+',
    pastMedicalHistory: 'Asthma',
    regularMedicine: 'Inhaler PRN',
    drugAllergy: 'Penicillin',
    chiefComplaint: 'Sore throat and fever',
    examinationFindings: 'Tonsillar swelling, temperature 100.4°F',
    prescription: 'Amoxicillin 500mg BD x 7 days',
    clinicalNoting: 'Acute tonsillitis',
    referredToHospital: 'No',
    approvedHospital: '',
    referralTemplate: '',
    createdBy: 'Dr. Suresh Patel',
    createdAt: '2024-11-20T14:30:00',
  },
  {
    id: 'HR-003',
    membershipId: 'MEM-001',
    memberName: 'Smt. Sunita Verma',
    membershipTypeName: 'Faculty Family Plan',
    healthCenter: 'Campus Health Center',
    isDependent: 'Yes',
    dependentId: 'DEP-001',
    dependentName: 'Smt. Sunita Verma',
    dependentRelation: 'Spouse',
    dateOfVisit: '2024-11-25',
    timeOfVisit: '09:00',
    height: '158',
    weight: '62',
    bloodGroup: 'O+',
    pastMedicalHistory: 'Nil',
    regularMedicine: 'None',
    drugAllergy: 'None',
    chiefComplaint: 'Joint pain in knees',
    examinationFindings: 'Mild swelling in both knees',
    prescription: 'Ibuprofen 400mg TDS x 5 days',
    clinicalNoting: 'Osteoarthritis suspected, advised physiotherapy',
    referredToHospital: 'No',
    approvedHospital: '',
    referralTemplate: '',
    createdBy: 'Dr. Ananya Gupta',
    createdAt: '2024-11-25T09:30:00',
  },
  {
    id: 'HR-004',
    membershipId: 'MEM-004',
    memberName: 'Mr. Ravi Krishnan',
    membershipTypeName: 'Guest Medical',
    healthCenter: 'University Hospital',
    isDependent: 'No',
    dependentId: '',
    dependentName: '',
    dependentRelation: '',
    dateOfVisit: '2024-11-28',
    timeOfVisit: '22:30',
    height: '175',
    weight: '80',
    bloodGroup: 'O+',
    pastMedicalHistory: 'Nil',
    regularMedicine: 'None',
    drugAllergy: 'None',
    chiefComplaint: 'Chest pain and shortness of breath',
    examinationFindings: 'ECG shows ST elevation',
    prescription: 'Referred to cardiology',
    clinicalNoting: 'Suspected myocardial infarction',
    referredToHospital: 'Yes',
    approvedHospital: 'City General Hospital',
    referralTemplate: 'Emergency Referral',
    createdBy: 'Dr. Priya Mehta',
    createdAt: '2024-11-28T23:00:00',
  },
];

export const subscriptions: Subscription[] = [
  {
    id: 'SUB-001',
    membershipId: 'MEM-001',
    memberName: 'Mr. Amit Verma',
    amount: 5000,
    transactionDate: '2024-08-01',
    paymentMethod: 'Online Transfer',
    status: 'Paid',
  },
  {
    id: 'SUB-002',
    membershipId: 'MEM-002',
    memberName: 'Ms. Priya Sharma',
    amount: 2500,
    transactionDate: '2024-07-15',
    paymentMethod: 'Cash',
    status: 'Paid',
  },
  {
    id: 'SUB-004',
    membershipId: 'MEM-004',
    memberName: 'Mr. Ravi Krishnan',
    amount: 1000,
    transactionDate: '2024-11-01',
    paymentMethod: 'Card',
    status: 'Pending',
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'LOG-001',
    action: 'Membership Created',
    performedBy: 'Dr. Admin Sharma',
    timestamp: '2024-08-01 09:15:00',
    details:
      'Created membership MEM-001 for Mr. Amit Verma (Faculty Family Plan)',
  },
  {
    id: 'LOG-002',
    action: 'Health Record Created',
    performedBy: 'Dr. Priya Mehta',
    timestamp: '2024-11-15 10:45:00',
    details: 'Created health record HR-001 for Mr. Amit Verma',
  },
  {
    id: 'LOG-003',
    action: 'Prescription Issued',
    performedBy: 'Dr. Priya Mehta',
    timestamp: '2024-11-15 10:50:00',
    details: 'Prescribed Paracetamol + Cetirizine for HR-001',
  },
  {
    id: 'LOG-004',
    action: 'Medicine Dispensed',
    performedBy: 'Mr. Rajesh Kumar',
    timestamp: '2024-11-15 11:00:00',
    details: 'Dispensed medicines for prescription PRX-001',
  },
  {
    id: 'LOG-005',
    action: 'Referral Made',
    performedBy: 'Dr. Priya Mehta',
    timestamp: '2024-11-28 23:00:00',
    details: 'Referred HR-004 to City General Hospital (Emergency)',
  },
  {
    id: 'LOG-006',
    action: 'Stock Updated',
    performedBy: 'Mr. Rajesh Kumar',
    timestamp: '2024-11-28 23:00:00',
    details: 'Updated medical stock - dispensed 10 Paracetamol tablets',
  },
  {
    id: 'LOG-007',
    action: 'Appointment Scheduled',
    performedBy: 'Mr. Amit Verma',
    timestamp: '2024-11-29 10:00:00',
    details: 'Booked appointment with Dr. Priya Mehta on 2024-12-01',
  },
];

export const settingsGeneral = {
  subscribedMembershipOnly: false,
};
