export const learningUrls = {
  portal: '/lms',
  dashboard: '/lms/dashboard',
  masters: '/lms/masters',
  configuration: '/lms/configuration',
  contentManagement: '/lms/content-management',
  assessment: '/lms/assessment',
  progressTracking: '/lms/progress-tracking',
  certification: '/lms/certification',
  faculty: {
    assignments: '/lms/faculty/assignments',
  },
  admin: {
    portal: '/lms/admin',
    dashboard: '/lms/admin/dashboard',
    masters: '/lms/admin/masters',
    configuration: '/lms/admin/configuration',
    reports: '/lms/admin/reports',
  },
  teacher: {
    portal: '/lms/teacher',
    dashboard: '/lms/teacher/dashboard',
    content: '/lms/teacher/content',
    assessment: '/lms/teacher/assessment',
    progress: '/lms/teacher/progress',
    certificate: '/lms/teacher/certificate',
    reports: '/lms/teacher/reports',
  },
  student: {
    portal: '/lms/student',
    dashboard: '/lms/student/dashboard',
    myLearning: '/lms/student/my-learning',
    assessments: '/lms/student/assessments',
    assignments: '/lms/student/assignments',
    progress: '/lms/student/progress',
    certificates: '/lms/student/certificates',
    reports: '/lms/student/reports',
  },
};
