export const admissionsUrls = {
  root: '/admissions-management',
  admin: {
    root: '/admissions-management/admin',
    dashboard: '/admissions-management/admin/dashboard',
    applications: '/admissions-management/admin/applications',
    feeApproval: '/admissions-management/admin/fee-approval',
    programmeConfig: '/admissions-management/admin/programme-config',
    feeConfig: '/admissions-management/admin/fee-config',
    portalSettings: '/admissions-management/admin/portal-settings',
    notifications: '/admissions-management/admin/notifications',
    cycleMaster: '/admissions-management/admin/cycle-master',
    eligibilityRules: '/admissions-management/admin/eligibility-rules',
    reservationMaster: '/admissions-management/admin/reservation-master',
    seatMatrix: '/admissions-management/admin/seat-matrix',
    meritRules: '/admissions-management/admin/merit-rules',
    documentMaster: '/admissions-management/admin/document-master',
  },
  student: {
    root: '/admissions-management/student',
    dashboard: '/admissions-management/student/dashboard',
    apply: '/admissions-management/student/apply',
    status: '/admissions-management/student/status',
    feePayment: '/admissions-management/student/fee-payment',
    subjectSelection: '/admissions-management/student/subject-selection',
    enquiry: '/admissions-management/student/enquiry',
    coursePreference: '/admissions-management/student/course-preference',
    documents: '/admissions-management/student/documents',
    preview: '/admissions-management/student/preview',
    tracking: '/admissions-management/student/tracking',
    meritList: '/admissions-management/student/merit-list',
    offer: '/admissions-management/student/offer',
    admissionLetter: '/admissions-management/student/admission-letter',
  },
  cell: {
    root: '/admissions-management/cell',
    dashboard: '/admissions-management/cell/dashboard',
    documents: '/admissions-management/cell/documents',
    meritList: '/admissions-management/cell/merit-list',
    seatAllocation: '/admissions-management/cell/seat-allocation',
    studentConversion: '/admissions-management/cell/student-conversion',
  },
};
