// ─── Seed Data — lifted from integrated_erp_system.tsx ───────────────────────

export const INITIAL_HOSTELS: HostelManagement.Hostel[] = [
  {
    code: 'HST-001',
    name: 'Swami Vivekananda Boys Hostel (H-1)',
    type: 'Boys',
    college: 'University Institute of Technology (UIT)',
    category: 'General',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'STU University Campus, Airport Road',
    pincode: '462033',
    floors: 4,
    rooms: 120,
    beds: 240,
    occupancy: 185,
    available: 55,
    wardenName: 'Dr. Alok Prasad',
    wardenMobile: '9876543210',
    wardenEmail: 'alok.prasad@stu.ac.in',
    assistantWarden: 'Shri Rajesh Kumar',
    assistantWardenMobile: '9876543211',
    facilities: ['Mess', 'WiFi', 'Security', 'CCTV', 'Water Cooler'],
    securityDeposit: 5000,
    hostelFee: 12000,
    messFee: 15000,
    electricityCharges: 2000,
    status: 'Active',
  },
  {
    code: 'HST-002',
    name: 'Rani Laxmibai Girls Hostel (H-2)',
    type: 'Girls',
    college: 'University Department of Sciences (UDS)',
    category: 'General',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    address: 'STU Girls Campus, Gandhi Nagar',
    pincode: '462036',
    floors: 3,
    rooms: 80,
    beds: 160,
    occupancy: 142,
    available: 18,
    wardenName: 'Dr. Suman Sharma',
    wardenMobile: '8765432109',
    wardenEmail: 'suman.sharma@stu.ac.in',
    assistantWarden: 'Smt. Sunita Verma',
    assistantWardenMobile: '8765432108',
    facilities: ['Mess', 'WiFi', 'Laundry', 'Security', 'CCTV', 'Water Cooler'],
    securityDeposit: 5000,
    hostelFee: 12000,
    messFee: 15000,
    electricityCharges: 2000,
    status: 'Active',
  },
];

export const INITIAL_ROOMS: HostelManagement.Room[] = [
  {
    hostelCode: 'HST-001',
    hostelName: 'Swami Vivekananda Boys Hostel (H-1)',
    roomNumber: '101',
    roomName: 'Ground Floor Block A - 101',
    floorNumber: '1',
    blockWing: 'A-Wing',
    roomType: 'Double Seater',
    totalBeds: 2,
    occupiedBeds: 2,
    availableBeds: 0,
    facilities: [
      'Attached Washroom',
      'Fan Count: 2',
      'Study Table',
      'Cupboard',
    ],
    category: 'Standard',
    additionalCharges: 0,
    status: 'Full',
    active: 'Active',
  },
  {
    hostelCode: 'HST-001',
    hostelName: 'Swami Vivekananda Boys Hostel (H-1)',
    roomNumber: '102',
    roomName: 'Ground Floor Block A - 102',
    floorNumber: '1',
    blockWing: 'A-Wing',
    roomType: 'Double Seater',
    totalBeds: 2,
    occupiedBeds: 1,
    availableBeds: 1,
    facilities: ['Fan Count: 2', 'Study Table', 'Cupboard'],
    category: 'Standard',
    additionalCharges: 0,
    status: 'Available',
    active: 'Active',
  },
  {
    hostelCode: 'HST-001',
    hostelName: 'Swami Vivekananda Boys Hostel (H-1)',
    roomNumber: '201',
    roomName: 'First Floor Block B - 201 (AC)',
    floorNumber: '2',
    blockWing: 'B-Wing',
    roomType: 'Single Seater',
    totalBeds: 1,
    occupiedBeds: 0,
    availableBeds: 1,
    facilities: [
      'Attached Washroom',
      'AC Available',
      'Fan Count: 1',
      'Study Table',
      'Cupboard',
    ],
    category: 'AC',
    additionalCharges: 3000,
    status: 'Available',
    active: 'Active',
  },
  {
    hostelCode: 'HST-002',
    hostelName: 'Rani Laxmibai Girls Hostel (H-2)',
    roomNumber: 'G05',
    roomName: 'Ground Floor Premium - G05',
    floorNumber: '0',
    blockWing: 'Main Wing',
    roomType: 'Double Seater',
    totalBeds: 2,
    occupiedBeds: 2,
    availableBeds: 0,
    facilities: [
      'Attached Washroom',
      'Fan Count: 2',
      'Study Table',
      'Cupboard',
    ],
    category: 'Premium',
    additionalCharges: 1500,
    status: 'Maintenance',
    active: 'Active',
  },
];

export const INITIAL_APPLICATIONS: HostelManagement.Application[] = [
  {
    id: 'APP-2026-0891',
    enrollmentNo: 'STU2024CS0120',
    name: 'Aditya Pratap Singh',
    fatherName: 'Rajendra Prasad Singh',
    motherName: 'Saraswati Singh',
    gender: 'Male',
    dob: '2005-04-12',
    mobile: '9123456780',
    email: 'aditya.singh@stu.ac.in',
    university: 'State Technological University',
    college: 'University Institute of Technology (UIT)',
    course: 'Bachelor of Technology',
    branch: 'Computer Science & Engineering',
    semester: 'IV Semester',
    admissionYear: '2024',
    permanentAddress: '12, Scheme No. 54, Vijay Nagar',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    pincode: '452010',
    distance: '195',
    hostelPreference: 'HST-001',
    roomPreference: 'Double',
    needMess: 'Yes',
    checkInDate: '2026-07-01',
    specialRequirement: 'None',
    guardianName: 'Vijay Kumar Singh',
    relationship: 'Uncle',
    guardianMobile: '9123456789',
    guardianAddress: 'B-23, Kasturba Nagar, Bhopal',
    emergencyName: 'Rajendra Prasad Singh',
    emergencyMobile: '9123456780',
    emergencyRelationship: 'Father',
    bloodGroup: 'O+',
    medicalCondition: 'None',
    disabilityDetails: 'None',
    allergies: 'None',
    documents: {
      photo: 'photo_aditya.jpg',
      aadhaar: 'aadhaar_redacted.pdf',
      admissionReceipt: 'rec_2024.pdf',
      collegeId: 'id_aditya.pdf',
    },
    declaration: true,
    signature: 'Aditya P. Singh',
    status: 'Pending',
    adminRemarks: '',
    allottedHostel: '',
    allottedRoom: '',
    allottedBed: '',
    feeStatus: 'Unpaid',
  },
  {
    id: 'APP-2026-0412',
    enrollmentNo: 'STU2025ME0043',
    name: 'Meera Deshmukh',
    fatherName: 'Satish Deshmukh',
    motherName: 'Lata Deshmukh',
    gender: 'Female',
    dob: '2006-08-22',
    mobile: '9823456711',
    email: 'meera.d@stu.ac.in',
    university: 'State Technological University',
    college: 'University Department of Sciences (UDS)',
    course: 'Master of Science',
    branch: 'Physics',
    semester: 'II Semester',
    admissionYear: '2025',
    permanentAddress: '45, Ring Road, Civil Lines',
    state: 'Madhya Pradesh',
    district: 'Jabalpur',
    city: 'Jabalpur',
    pincode: '482001',
    distance: '320',
    hostelPreference: 'HST-002',
    roomPreference: 'Single',
    needMess: 'Yes',
    checkInDate: '2026-07-02',
    specialRequirement: 'Requires desk near window',
    guardianName: 'Aarti Deshmukh',
    relationship: 'Aunt',
    guardianMobile: '9823456719',
    guardianAddress: 'H.No. 12, Arera Colony, Bhopal',
    emergencyName: 'Satish Deshmukh',
    emergencyMobile: '9823456711',
    emergencyRelationship: 'Father',
    bloodGroup: 'B+',
    medicalCondition: 'Asthma',
    disabilityDetails: 'None',
    allergies: 'Dust allergy',
    documents: {
      photo: 'meera_pic.jpg',
      aadhaar: 'aadhaar_redacted.pdf',
      admissionReceipt: 'rec_2025_me.pdf',
      collegeId: 'id_meera.pdf',
    },
    declaration: true,
    signature: 'Meera Deshmukh',
    status: 'Sent Back',
    adminRemarks:
      'Scanned local guardian address receipt was blurry. Resubmit.',
    allottedHostel: '',
    allottedRoom: '',
    allottedBed: '',
    feeStatus: 'Unpaid',
  },
];

export const INITIAL_CHECKINS: HostelManagement.CheckInRecord[] = [
  {
    appId: 'APP-2026-9912',
    studentName: 'Meera Deshmukh',
    enrollmentNo: 'STU2025ME0043',
    hostelCode: 'HST-002',
    roomNo: 'G05',
    bedNo: 'Bed-2',
    checkInDate: '2026-06-12',
    luggage: '2',
    remarks: 'Credentials verified manually. Ward key G05 issued.',
  },
];

// ─── Dropdown option lists ────────────────────────────────────────────────────

export const COLLEGE_OPTIONS = [
  'University Institute of Technology (UIT)',
  'University Department of Sciences (UDS)',
  'University Law College (ULC)',
  'Institute of Management Studies (IMS)',
];

export const FACILITY_OPTIONS = [
  'Mess',
  'WiFi',
  'Laundry',
  'Security',
  'CCTV',
  'Water Cooler',
  'Common Room',
  'Study Hall',
  'Gym',
];

export const ROOM_FACILITY_OPTIONS = [
  'Attached Washroom',
  'AC Available',
  'Fan Count: 1',
  'Fan Count: 2',
  'Study Table',
  'Cupboard',
  'Balcony',
  'Geyser',
];

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];

export const SEMESTERS = [
  'I Semester',
  'II Semester',
  'III Semester',
  'IV Semester',
  'V Semester',
  'VI Semester',
  'VII Semester',
  'VIII Semester',
];
