export const studentManagementUrls = {
  admin: {
    root: '/student-management/admin',
    dashboard: '/student-management/admin/dashboard',
    directory: '/student-management/admin/directory',
    import: '/student-management/admin/import',
  },
  student: {
    root: '/student-management/student',
    dashboard: '/student-management/student/dashboard',
    linkAbc: '/student-management/student/link-abc',
    profile: '/student-management/student/profile',
    applicationForm: '/student-management/student/application-form',
    semesterRegistration: '/student-management/student/semester-registration',
    attendance: '/student-management/student/attendance',
    timetable: '/student-management/student/timetable',
    lms: '/student-management/student/lms',
    assignments: '/student-management/student/assignments',
    academicHistory: '/student-management/student/academic-history',
    grievance: '/student-management/student/grievance',
    myCourses: '/student-management/student/my-courses',
    myGrades: '/student-management/student/my-grades',
    termReport: '/student-management/student/term-report',
    subjectSelection: '/student-management/student/subject-selection',
  },
  faculty: {
    root: '/student-management/faculty',
    dashboard: '/student-management/faculty/dashboard',
    students: '/student-management/faculty/students',
    attendance: '/student-management/faculty/attendance',
    internalAssessment: '/student-management/faculty/internal-assessment',
    assignments: '/student-management/faculty/assignments',
    progress: '/student-management/faculty/progress',
  },
  department: {
    root: '/student-management/department',
    dashboard: '/student-management/department/dashboard',
    batchAllocation: '/student-management/department/batch-allocation',
    sectionAllocation: '/student-management/department/section-allocation',
    subjectMapping: '/student-management/department/subject-mapping',
    promotion: '/student-management/department/promotion',
  },
};
