import type {
  StateItem,
  DivisionItem,
  DistrictItem,
  TehsilItem,
  BlockItem,
} from '../types';

export const states: StateItem[] = [
  { id: 1, name: 'Madhya Pradesh', code: 'MP', isActive: true },
  { id: 2, name: 'Maharashtra', code: 'MH', isActive: true },
  { id: 3, name: 'Gujarat', code: 'GJ', isActive: true },
  { id: 4, name: 'Uttar Pradesh', code: 'UP', isActive: true },
  { id: 5, name: 'Rajasthan', code: 'RJ', isActive: true },
  { id: 6, name: 'Delhi', code: 'DL', isActive: true },
  { id: 7, name: 'Karnataka', code: 'KA', isActive: true },
  { id: 8, name: 'Tamil Nadu', code: 'TN', isActive: true },
];

export const divisions: DivisionItem[] = [
  {
    id: 1,
    name: 'Bhopal',
    stateId: 1,
    stateName: 'Madhya Pradesh',
    isActive: true,
  },
  {
    id: 2,
    name: 'Indore',
    stateId: 1,
    stateName: 'Madhya Pradesh',
    isActive: true,
  },
  {
    id: 3,
    name: 'Gwalior',
    stateId: 1,
    stateName: 'Madhya Pradesh',
    isActive: true,
  },
  {
    id: 4,
    name: 'Jabalpur',
    stateId: 1,
    stateName: 'Madhya Pradesh',
    isActive: true,
  },
  {
    id: 5,
    name: 'Ujjain',
    stateId: 1,
    stateName: 'Madhya Pradesh',
    isActive: true,
  },
  { id: 6, name: 'Pune', stateId: 2, stateName: 'Maharashtra', isActive: true },
  {
    id: 7,
    name: 'Mumbai',
    stateId: 2,
    stateName: 'Maharashtra',
    isActive: true,
  },
  {
    id: 8,
    name: 'Nagpur',
    stateId: 2,
    stateName: 'Maharashtra',
    isActive: true,
  },
  {
    id: 9,
    name: 'Ahmedabad',
    stateId: 3,
    stateName: 'Gujarat',
    isActive: true,
  },
  {
    id: 10,
    name: 'Vadodara',
    stateId: 3,
    stateName: 'Gujarat',
    isActive: true,
  },
  {
    id: 11,
    name: 'Lucknow',
    stateId: 4,
    stateName: 'Uttar Pradesh',
    isActive: true,
  },
  {
    id: 12,
    name: 'Kanpur',
    stateId: 4,
    stateName: 'Uttar Pradesh',
    isActive: true,
  },
  {
    id: 13,
    name: 'Jaipur',
    stateId: 5,
    stateName: 'Rajasthan',
    isActive: true,
  },
  {
    id: 14,
    name: 'Jodhpur',
    stateId: 5,
    stateName: 'Rajasthan',
    isActive: true,
  },
];

export const districts: DistrictItem[] = [
  {
    id: 1,
    name: 'Bhopal',
    divisionId: 1,
    divisionName: 'Bhopal',
    isActive: true,
  },
  {
    id: 2,
    name: 'Raisen',
    divisionId: 1,
    divisionName: 'Bhopal',
    isActive: true,
  },
  {
    id: 3,
    name: 'Vidisha',
    divisionId: 1,
    divisionName: 'Bhopal',
    isActive: true,
  },
  {
    id: 4,
    name: 'Indore',
    divisionId: 2,
    divisionName: 'Indore',
    isActive: true,
  },
  {
    id: 5,
    name: 'Dewas',
    divisionId: 2,
    divisionName: 'Indore',
    isActive: true,
  },
  {
    id: 6,
    name: 'Dhar',
    divisionId: 2,
    divisionName: 'Indore',
    isActive: true,
  },
  {
    id: 7,
    name: 'Gwalior',
    divisionId: 3,
    divisionName: 'Gwalior',
    isActive: true,
  },
  {
    id: 8,
    name: 'Shivpuri',
    divisionId: 3,
    divisionName: 'Gwalior',
    isActive: true,
  },
  {
    id: 9,
    name: 'Jabalpur',
    divisionId: 4,
    divisionName: 'Jabalpur',
    isActive: true,
  },
  {
    id: 10,
    name: 'Katni',
    divisionId: 4,
    divisionName: 'Jabalpur',
    isActive: true,
  },
  {
    id: 11,
    name: 'Ujjain',
    divisionId: 5,
    divisionName: 'Ujjain',
    isActive: true,
  },
  {
    id: 12,
    name: 'Shajapur',
    divisionId: 5,
    divisionName: 'Ujjain',
    isActive: true,
  },
  { id: 13, name: 'Pune', divisionId: 6, divisionName: 'Pune', isActive: true },
  {
    id: 14,
    name: 'Mumbai City',
    divisionId: 7,
    divisionName: 'Mumbai',
    isActive: true,
  },
  {
    id: 15,
    name: 'Nagpur',
    divisionId: 8,
    divisionName: 'Nagpur',
    isActive: true,
  },
  {
    id: 16,
    name: 'Ahmedabad',
    divisionId: 9,
    divisionName: 'Ahmedabad',
    isActive: true,
  },
  {
    id: 17,
    name: 'Vadodara',
    divisionId: 10,
    divisionName: 'Vadodara',
    isActive: true,
  },
  {
    id: 18,
    name: 'Lucknow',
    divisionId: 11,
    divisionName: 'Lucknow',
    isActive: true,
  },
  {
    id: 19,
    name: 'Jaipur',
    divisionId: 13,
    divisionName: 'Jaipur',
    isActive: true,
  },
  {
    id: 20,
    name: 'Jodhpur',
    divisionId: 14,
    divisionName: 'Jodhpur',
    isActive: true,
  },
];

export const tehsils: TehsilItem[] = [
  {
    id: 1,
    name: 'Huzur',
    districtId: 1,
    districtName: 'Bhopal',
    isActive: true,
  },
  {
    id: 2,
    name: 'Berasia',
    districtId: 1,
    districtName: 'Bhopal',
    isActive: true,
  },
  {
    id: 3,
    name: 'Goharganj',
    districtId: 1,
    districtName: 'Bhopal',
    isActive: true,
  },
  {
    id: 4,
    name: 'Raisen',
    districtId: 2,
    districtName: 'Raisen',
    isActive: true,
  },
  {
    id: 5,
    name: 'Gairatganj',
    districtId: 2,
    districtName: 'Raisen',
    isActive: true,
  },
  {
    id: 6,
    name: 'Vidisha',
    districtId: 3,
    districtName: 'Vidisha',
    isActive: true,
  },
  {
    id: 7,
    name: 'Mhow',
    districtId: 4,
    districtName: 'Indore',
    isActive: true,
  },
  {
    id: 8,
    name: 'Depalpur',
    districtId: 4,
    districtName: 'Indore',
    isActive: true,
  },
  {
    id: 9,
    name: 'Dewas',
    districtId: 5,
    districtName: 'Dewas',
    isActive: true,
  },
  {
    id: 10,
    name: 'Sonkatch',
    districtId: 5,
    districtName: 'Dewas',
    isActive: true,
  },
  { id: 11, name: 'Dhar', districtId: 6, districtName: 'Dhar', isActive: true },
  {
    id: 12,
    name: 'Gwalior',
    districtId: 7,
    districtName: 'Gwalior',
    isActive: true,
  },
  {
    id: 13,
    name: 'Jabalpur',
    districtId: 9,
    districtName: 'Jabalpur',
    isActive: true,
  },
  {
    id: 14,
    name: 'Ujjain',
    districtId: 11,
    districtName: 'Ujjain',
    isActive: true,
  },
  {
    id: 15,
    name: 'Pune City',
    districtId: 13,
    districtName: 'Pune',
    isActive: true,
  },
];

export const blocks: BlockItem[] = [
  { id: 1, name: 'Phanda', tehsilId: 1, tehsilName: 'Huzur', isActive: true },
  {
    id: 2,
    name: 'Berasia Block',
    tehsilId: 2,
    tehsilName: 'Berasia',
    isActive: true,
  },
  {
    id: 3,
    name: 'Goharganj Block',
    tehsilId: 3,
    tehsilName: 'Goharganj',
    isActive: true,
  },
  {
    id: 4,
    name: 'Raisen Block',
    tehsilId: 4,
    tehsilName: 'Raisen',
    isActive: true,
  },
  {
    id: 5,
    name: 'Gairatganj Block',
    tehsilId: 5,
    tehsilName: 'Gairatganj',
    isActive: true,
  },
  {
    id: 6,
    name: 'Mhow Block',
    tehsilId: 7,
    tehsilName: 'Mhow',
    isActive: true,
  },
  {
    id: 7,
    name: 'Depalpur Block',
    tehsilId: 8,
    tehsilName: 'Depalpur',
    isActive: true,
  },
  {
    id: 8,
    name: 'Kannod',
    tehsilId: 10,
    tehsilName: 'Sonkatch',
    isActive: true,
  },
  { id: 9, name: 'Morar', tehsilId: 12, tehsilName: 'Gwalior', isActive: true },
  {
    id: 10,
    name: 'Panagar',
    tehsilId: 13,
    tehsilName: 'Jabalpur',
    isActive: true,
  },
];
