import type {
  CollegeCategoryItem,
  CollegeTypeItem,
  CollegeRegistrationItem,
} from '../types';

export const collegeCategories: CollegeCategoryItem[] = [
  { id: 1, name: 'Co-Education', code: 'COED', isActive: true },
  { id: 2, name: 'Women Only', code: 'WMN', isActive: true },
  { id: 3, name: 'Men Only', code: 'MEN', isActive: true },
];

export const collegeTypes: CollegeTypeItem[] = [
  { id: 1, name: 'Government', code: 'GOVT', isActive: true },
  { id: 2, name: 'Private', code: 'PVT', isActive: true },
  { id: 3, name: 'Autonomous', code: 'AUTO', isActive: true },
  { id: 4, name: 'Aided', code: 'AIDED', isActive: true },
  { id: 5, name: 'Self-Financed', code: 'SF', isActive: true },
];

export const allColleges: CollegeRegistrationItem[] = [
  {
    id: 1,
    collegeRegistrationId: 1,
    collegeName: 'Government College of Engineering, Bhopal',
    name: 'Government College of Engineering, Bhopal',
    district: 'Bhopal',
    city: 'Bhopal',
    isActive: true,
  },
  {
    id: 2,
    collegeRegistrationId: 2,
    collegeName: 'Maulana Azad National Institute of Technology, Bhopal',
    name: 'Maulana Azad National Institute of Technology, Bhopal',
    district: 'Bhopal',
    city: 'Bhopal',
    isActive: true,
  },
  {
    id: 3,
    collegeRegistrationId: 3,
    collegeName: 'Regional Institute of Education, Bhopal',
    name: 'Regional Institute of Education, Bhopal',
    district: 'Bhopal',
    city: 'Bhopal',
    isActive: true,
  },
  {
    id: 4,
    collegeRegistrationId: 4,
    collegeName: 'Indian Institute of Technology, Indore',
    name: 'Indian Institute of Technology, Indore',
    district: 'Indore',
    city: 'Indore',
    isActive: true,
  },
  {
    id: 5,
    collegeRegistrationId: 5,
    collegeName: 'Shri Govindram Seksaria Institute of Technology, Indore',
    name: 'Shri Govindram Seksaria Institute of Technology, Indore',
    district: 'Indore',
    city: 'Indore',
    isActive: true,
  },
  {
    id: 6,
    collegeRegistrationId: 6,
    collegeName: 'Holkar Science College, Indore',
    name: 'Holkar Science College, Indore',
    district: 'Indore',
    city: 'Indore',
    isActive: true,
  },
  {
    id: 7,
    collegeRegistrationId: 7,
    collegeName: 'Jiwaji University, Gwalior',
    name: 'Jiwaji University, Gwalior',
    district: 'Gwalior',
    city: 'Gwalior',
    isActive: true,
  },
  {
    id: 8,
    collegeRegistrationId: 8,
    collegeName: 'Madhav Institute of Technology, Gwalior',
    name: 'Madhav Institute of Technology, Gwalior',
    district: 'Gwalior',
    city: 'Gwalior',
    isActive: true,
  },
  {
    id: 9,
    collegeRegistrationId: 9,
    collegeName: 'Jabalpur Engineering College',
    name: 'Jabalpur Engineering College',
    district: 'Jabalpur',
    city: 'Jabalpur',
    isActive: true,
  },
  {
    id: 10,
    collegeRegistrationId: 10,
    collegeName: 'Pandit S.N. Shukla University, Shahdol',
    name: 'Pandit S.N. Shukla University, Shahdol',
    district: 'Jabalpur',
    city: 'Shahdol',
    isActive: true,
  },
  {
    id: 11,
    collegeRegistrationId: 11,
    collegeName: 'Vikram University, Ujjain',
    name: 'Vikram University, Ujjain',
    district: 'Ujjain',
    city: 'Ujjain',
    isActive: true,
  },
  {
    id: 12,
    collegeRegistrationId: 12,
    collegeName: 'College of Agriculture, Pune',
    name: 'College of Agriculture, Pune',
    district: 'Pune',
    city: 'Pune',
    isActive: true,
  },
  {
    id: 13,
    collegeRegistrationId: 13,
    collegeName: 'University of Mumbai',
    name: 'University of Mumbai',
    district: 'Mumbai City',
    city: 'Mumbai',
    isActive: true,
  },
  {
    id: 14,
    collegeRegistrationId: 14,
    collegeName: 'Visvesvaraya National Institute of Technology, Nagpur',
    name: 'Visvesvaraya National Institute of Technology, Nagpur',
    district: 'Nagpur',
    city: 'Nagpur',
    isActive: true,
  },
  {
    id: 15,
    collegeRegistrationId: 15,
    collegeName: 'Gujarat University, Ahmedabad',
    name: 'Gujarat University, Ahmedabad',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    isActive: true,
  },
  {
    id: 16,
    collegeRegistrationId: 16,
    collegeName: 'University of Lucknow',
    name: 'University of Lucknow',
    district: 'Lucknow',
    city: 'Lucknow',
    isActive: true,
  },
  {
    id: 17,
    collegeRegistrationId: 17,
    collegeName: 'University of Rajasthan, Jaipur',
    name: 'University of Rajasthan, Jaipur',
    district: 'Jaipur',
    city: 'Jaipur',
    isActive: true,
  },
  {
    id: 18,
    collegeRegistrationId: 18,
    collegeName: 'Dr. Hari Singh Gour University, Sagar',
    name: 'Dr. Hari Singh Gour University, Sagar',
    district: 'Raisen',
    city: 'Sagar',
    isActive: true,
  },
  {
    id: 19,
    collegeRegistrationId: 19,
    collegeName: 'Barkatullah University, Bhopal',
    name: 'Barkatullah University, Bhopal',
    district: 'Bhopal',
    city: 'Bhopal',
    isActive: true,
  },
  {
    id: 20,
    collegeRegistrationId: 20,
    collegeName: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal',
    name: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal',
    district: 'Bhopal',
    city: 'Bhopal',
    isActive: true,
  },
];
