import type { ApplicationFormData } from '../types';

export const sampleApplication: ApplicationFormData = {
  academicSession: '1',
  programme: '1',

  firstName: 'Ravi',
  middleName: 'Kumar',
  lastName: 'Sharma',
  email: 'ravi.sharma@example.com',
  phone: '9876543210',
  gender: '1',
  caste: '1',
  dateOfBirth: new Date('2006-05-15'),
  age: 20,
  fatherName: 'Suresh Sharma',
  fatherOccupation: '2',
  fatherDesignation: '3',
  fatherAnnualIncome: 500000,
  fatherContactNumber: '9876543211',
  motherName: 'Sunita Sharma',
  motherOccupation: '9',
  motherDesignation: '6',
  motherAnnualIncome: 0,
  motherContactNumber: '9876543212',
  residencyStatus: '1',
  ethnicity: 'Indian',
  nationality: '1',

  degreeLevel: '1',
  programOfStudy: '1',
  specialisation: '1',

  priorEducations: [
    {
      id: 'seed-edu-1',
      educationLevel: '10th',
      institutionName: 'Kendriya Vidyalaya No.1',
      boardOrUniversity: 'CBSE',
      passingYear: 2020,
      percentage: 88.5,
      cgpa: 9.2,
      subjectsOrStream: 'Science',
      documentType: '10th Marksheet',
      documentFile: null,
      documentId: 'doc-seed-10th',
    },
    {
      id: 'seed-edu-2',
      educationLevel: '12th',
      institutionName: 'Kendriya Vidyalaya No.1',
      boardOrUniversity: 'CBSE',
      passingYear: 2022,
      percentage: 85.0,
      cgpa: 8.8,
      subjectsOrStream: 'Science (PCM)',
      documentType: '12th Marksheet',
      documentFile: null,
      documentId: 'doc-seed-12th',
    },
  ],
  choiceFilling: [],

  addressType: '1',
  country: 'India',
  state: '1',
  division: '1',
  district: '1',
  tehsil: '1',
  block: '1',
  addressLine1: '123, Shyamla Hills',
  addressLine2: 'Near Bhopal Talkies',
  landmark: 'Rose Garden',
  zipcode: 462002,
};
